42organization/42gg.client

components/Layout/Layout.tsx
components/Layout/MenuBar.tsx
components/score/InputScoreModal.tsx
pages/score.tsx

- 레이아웃과 스코어 입력 모달창 연결(레이아웃에서 보여줘 모든 페이지에서 입력창을 띄웁니다.)
- 메뉴바 내정보 페이지 연결
- 레이아웃의 liveData에서 gameId가 있을 때 스코어 입력 모달창 보여주기
- 모든 창에서 보여주어 일단 주석처리해놨습니다 
- 메뉴바의 내정보 클릭시 내정보 페이지 연결

[Feat] 레이아웃에서 스코어 모달 연결 및 메뉴바 내정보 페이지 연결 #1

---

components/Layout/Layout.tsx
components/Layout/MenuBar.tsx
pages/api/pingpong/users/[userId]/live.ts
types/mainType.ts
utils/recoil/main.ts

- 레이아웃에서 현재매치정보 컴포넌트 연결
- liveData에 event 데이터 추가: match 이벤트 발생시 'match' 받아옴
- recoil, api, type 수정
- event: 'match'일 때 CurrentMatchInfo컴포넌트를 보여줌

[Faet] 레이아웃에서 현재매치정보 컴포넌트 연결

---

components/game/GameResultList.tsx
components/game/GameResultPath.tsx
pages/api/pingpong/users/[userId]/games/1.ts
pages/api/pingpong/users/[userId]/games/2.ts
pages/api/pingpong/users/[userId]/games/3.ts
pages/api/pingpong/users/[userId]/games/4.ts
pages/game.tsx
utils/infinityScroll.ts

- 서버데이터 연동
- 리스트 페이지 분기처리
- 수정사항 변경
- 서버 api에 맞춰서 데이터 연동
- 리스트 페이지에서 하던 분기처리를 ResultPath 컴포넌트를 만들어서 따로 처리후 list에 넘겨주기로 처리함
-  (수정사항)
- ResultPath에서 isMain과 user로 props를 받는게 아니라 router.asPath를 활용해서 현제 path를 받아 처리하는 방석으로 바꿈 그래서 따로 컴포넌트에 props를 넣을 필요 없이 컴포넌트만 선언하면 됨

[Feat] 서버데이터 연동 및 리스트 페이지 분기처리

---

components/game/small/GameResultSmallTeam.tsx

- GameResultSmallItem 컴포넌트 key 중첩 에러 수정
- GameResultSmallItem intra id 에 Link를 추가 할 때 key value가 Link태그 안에 있는 div에 들어있어서 key가 중첩되는 문제가 발생함 
- 해결하기위해 Link태그 안에 key value를 넣어줌

[Fix] GameResultSmallItem key 중첩 에러 수정

---

components/Layout/CurrentMatchInfo.tsx
components/Layout/Layout.tsx
components/match/MatchBoardList.tsx
styles/match/MatchBoardList.module.scss
utils/axios.ts
utils/recoil/match.ts

- 현재배치정보배너 상대팀 있을 때 5분 임박시 뜨게 하기, 매치페이지 새로고침버튼과 연결
- 현재배치정보배너 상대팀 있을 때 5분 임박시 뜨게 하기
- useEffect 추가해 path가 바뀔때, 5분 임을 확인하고, 5분 전일 때 상대 표시하는 함수(makeEnemyTeamInfo) 실행
- 매치페이지 새로고침버튼과 연결
- 매치페이지, 현재 매치정보 배너에 recoil matchRefreshBtn을 추가해 매치페이지 새로고침 누를 때 true 로 상태를 바꿔 배너도 새로고침버튼에  연결
- 매치 없을 때 안내문 스타일링

[Fix] 현재배치정보배너 상대팀 있을 때 5분 임박시 뜨게 하기, 매치페이지 새로고침버튼과 연결 #171

---

components/match/MatchBoardList.tsx
components/match/MatchItem.tsx
components/match/MatchManualModal.tsx
components/modal/MatchEnrollModal.tsx
components/modal/MatchRejectModal.tsx
pages/match.tsx
pages/users/[intraId].tsx
utils/recoil/match.ts

- match 페이지의 모달 :  뒤로가기시 사라지도록 수정
- match 취소 모달은 Layout 에 있어서 아직 작업하지 않았음
- match 페이지에 속한 모달들 상태 하나로 묶음
(enroll, reject, manual)
- useEffect return 을 사용하여 언마운트시 모달 상태를 false로 만듬

[Fix] match 페이지의 모달 :  뒤로가기 시 사라지도록 수정

---

components/Layout/CurrentMatchInfo.tsx

- 현재매치정보배너를 매치페이지 새로고침버튼, 스코어입력 모달과 연결
- 현재매치정보 컴포넌트의 데이터 요청 함수(getCurrentMatchHandler) 안에서 경기 5분 임박인지 확인하고 경기 상대를 보여주기
- path가 바뀌거나 매치페이지 새로고침버튼을 눌렀을 때, 경기 시작 시간이 지났다면 라이브 데이터의 event 상태를 game으로 만들어 스코어 입력 모달 띄우기

[Fix] 현재매치정보배너를 매치페이지 새로고침버튼, 스코어입력 모달과 연결 close #203 #207

---

components/Layout/CurrentMatchInfo.tsx

- 경기 시간 지난 후 현재매치정보 불러오기에서 시간에 null이 들어가는 문제
- time이 null일 때, 함수를 콜하지 않음

[Fix] 경기 시간 지난 후 현재매치정보 불러오기에서 시간에 null이 들어가는 문제

---

pages/login.tsx

- 로그인 안했을 경우 어떤 path에서도 로그인페이지로 진입하게 되는데 원래 입력한 url 이 살아있는 문제
- login 페이지에서 router.replace 사용

[fix] login page에서 기존 url이 유효한 문제

---

components/Layout/CurrentMatchInfo.tsx
components/match/MatchBoardList.tsx
components/match/MatchItem.tsx
components/modal/cancel/CancelModal.tsx
utils/recoil/match.ts

- 매칭이 안된 경기 취소시 페널티 메시지 삭제
- currentMatchInfo를 리코일 스테이트로 변경했습니다.
- 매치아이템 클릭시 currentMatchInfo를 새로 받아옵니다.
- 매치보드 배열이 비어있을 때 표시할 메시지를 추가했습니다.

[Fix] 매칭이 안된 경기 취소시 페널티 메시지 삭제 #273

---

components/modal/EditProfileModal.tsx
components/modal/Modal.tsx
components/user/Profile.tsx
pages/users/detail.tsx
utils/recoil/user.ts

- 모달 바깥 클릭시 모달 닫기
- 모달 관련 recoilstate 들을 Modal.tsx 에 가져와서 (InputScore 제외)
- 모달 바깥 클릭 시 useSetRecoilState 를 통해 false 혹은 null 처리
- ProfileEdit Recoil 변수명 `isEditProfileState`에서 `editProfileModalState` 로 변경
```typescript
// Modal.tsx
const modalCloseHandler = (e: React.MouseEvent) => {
if (e.target instanceof HTMLDivElement && e.target.id === 'modalOutside') {
setLogoutModal(false);
setEditProfileModal(false);
setMatchModal(null);
setCancelModal(false);
setNewLogin(false);
}
};
```
MouseEvent 에는 e.target에 id라는 속성이 없어서
if 문에 `e.target instanceof HTMLDivElement` 조건을 넣어서
TypeScript 에게 e.target이 id 라는 속성을 가지고 있음을 알려줌
참고 : https://velog.io/@e_juhee/TypeScript-EventType

[feat] 모달 바깥 클릭시 모달 닫기

---

components/game/GameResult.tsx
components/rank/RankList.tsx
components/rank/RankListFrame.tsx
components/rank/RankListItem.tsx
components/rank/topRank/RankListItemMain.tsx
components/rank/topRank/RankListMain.tsx
styles/rank/RankList.module.scss
styles/rank/RankListMain.module.scss

- 메인페이지에서 쓰는 랭크 컴포넌트 분리
- topRank 폴더 생성: 매 컴포넌트마다 메인페이지를 확인하는 과정이 불필요하다고 생각되어 메인페이지에서 쓰는 컴포넌트 분리해서 넣어놨습니다
- #390 : 수정된 모드 타입 적용
- #393 : 랭크 모드 일반전일 때 다른 스타일링 적용

[Fix] 메인페이지에서 쓰는 랭크 컴포넌트 분리#391

---

components/game/GameResult.tsx
components/game/GameResultList.tsx
components/mode/GameMode.tsx
components/mode/ProfileMode.tsx
components/mode/modeItems/UserGameSearchBar.tsx
pages/game.tsx
pages/users/detail.tsx
styles/game/GameResultItem.module.scss
styles/main/SearchBar.module.scss
styles/mode/IsMineCheckBox.module.scss
styles/user/user.module.scss

- 게임페이지 검색추가 및 프로필페이지와 연결
- detail 페이지:  'recent record' 클릭하면  `Link query` 로 해당 유저 아이디를 담아 `/game` 페이지로 이동하는 코드 추가
- game 페이지: 페이지명 'record' 클릭시 최신 데이터로 다시 렌더링 되도록 변경
- game 페이지 - gameResult: `query`에 따라 데이터 요청 path 변경
- game 페이지 - gameMode: 검색창 추가 <= 이후 컴포넌트 재사용을 위해 리팩토링 예정!!
- ‼️이후: 리팩토링 및 css 다듬을 예정입니다!!

[Feat] 게임페이지 검색추가 및 프로필페이지와 연결 #410

---

components/game/GameResultList.tsx
components/mode/modeItems/UserGameSearchBar.tsx
pages/game.tsx
utils/infinityScroll.ts

- 게임페이지 더보기 오류 및 깜박임 수정
- game.tsx: `router.push` `shallow:true`로 새로고침이 아니라 재렌더링 하도록 수정
- infinityScroll: `keepPreviousData: true`로 이전 데이터를 킵해두어 깜박임 줄임
- gameResultList
- 데이터를 받았을 때, 데이터가 있으면 0번째 Id를 BigItem으로 저장해두기, 
- 마지막 isLast를 isLast로 저장해 더보기 버튼 보이게 만들기

[Fix] 게임페이지 더보기 오류 및 깜박임 수정#437

---

components/Layout/CurrentMatch.tsx
components/Layout/Layout.tsx
components/match/MatchBoard.tsx
components/match/MatchSlot.tsx
components/match/MatchSlotList.tsx
components/modal/ModalProvider.tsx
components/modal/afterGame/exp/ExpChangeModal.tsx
components/modal/match/MatchEnrollModal.tsx
components/modal/matchCancel/CancelController.tsx
components/modal/matchCancel/CancelModal.tsx
components/mode/modeWraps/GameModeWrap.tsx
components/mode/modeWraps/MatchMode.tsx
components/mode/modeWraps/MatchModeWrap.tsx
components/mode/modeWraps/ProfileModeWrap.tsx
components/mode/modeWraps/RankModeWrap.tsx
components/user/RankProfile.tsx
pages/game.tsx
pages/match.tsx
pages/rank.tsx
types/modalTypes.ts

- 매치 등록/취소 시 live 상태 업데이트
- 매치 enrollInfo(現 enroll), cancelInfo(現 cancel)에 상태 업데이트를 위한 함수 타입을 추가했습니다.
- 매치 페이지에서 매치 등록/취소 시 페이지 전체 새로고침이 이루어지지 않고 match, live 상태만 비동기적으로 업데이트 됩니다.
- currentMatch 에서 매치 취소할 경우에는 원래 로직대로 페이지 전체가 새로고침 됩니다.

[Fix] 매치 등록/취소 시 live 상태 업데이트 #443

---

components/mode/modeWraps/GameModeWrap.tsx
pages/game.tsx
utils/infinityScroll.ts

- 게임페이지 url로 잘못된 유저 이름 접근시 에러코드 받아 에러페이지로 넘기기, 타이틀 클릭시 초기화
- 없는 유저이름 url 접근시 UF001 에러코드 받아 에러페이지로 넘기기(alert으로 처리하려고 했으나 너무 강력해서 에러코드 받아서 에러페이지로 넘기기로 했어융!)
- 게임페이지 타이틀 클릭시 모드, 시즌 초기화 시키기

[Fix] 게임페이지 url로 잘못된 유저 이름 접근시 에러코드 받아 에러페이지로 넘기기, 타이틀 클릭시 초기화  #434

---

components/rank/RankList.tsx
components/rank/RankListFrame.tsx
components/rank/RankListItem.tsx

- 랭크페이지 표 구분 및 유저데이터 객체로 한번에 관리하도록 리팩토링
- 표 구분 랭크/일반일 때 객체로 만들어서 한번에 관리, 추가 및 재사용 가능!
- RankList -> RankItem 유저 데이터 보낼 때, 객체로 만들어 보내 확인과정 줄이기!

[Refactor] 랭크페이지 표 구분 및 유저데이터 객체로 한번에 관리하도록 리팩토링 #447

---

components/game/GameResult.tsx
components/modal/matchCancel/CancelRejectModal.tsx
utils/recoil/seasons.ts

- 시즌 기본값 랭크로, 유저 게임 api 수정사항 반영, 모달 새로고침 깜박임 수정
- 메인페이지에서 새로고침시 vip가 반짝 보이는 문제 -> 시즌 기본값 랭크로 수정함
- 유저 게임 api 수정사항 반영: user/intraId/games?~ -> games/user/IntraId?~
- 모달 새로고침 깜박임 수정: router.reload() -> reloadMatch 리코일을 사용해 재렌더링 시킴

[Fix] 시즌 기본값 랭크로, 유저 게임 api 수정사항 반영, 모달 새로고침 깜박임 수정

---

components/modal/afterGame/exp/ExpCelebration.tsx
components/modal/afterGame/exp/ExpGuage.tsx
styles/modal/ExpGameModal.module.scss

- 컴퓨터 모드에서 celebrate애니메이션이 잘려서 보이는 문제
- css의 position 이 absolute라 위치가 모달에 종속되어서 모달의 시작 부분 부터 나오는 문제 발견
- position:absolute -> position:fixed 로 변경
- 사용하지 않는 컴포넌트 제거

[fix] 컴퓨터 모드에서 celebrate애니메이션이 잘려서 보이는 문제

---

components/match/MatchBoard.tsx
components/modal/ModalProvider.tsx
components/modal/match/MatchManualModal.tsx
components/mode/modeItems/ModeToggle.tsx
components/mode/modeWraps/MatchModeWrap.tsx
pages/match.tsx
styles/modal/MatchManualModal.module.scss
types/modalTypes.ts

- 매뉴얼 모달에 토글 추가
- 매뉴얼 내용 추가 및 스타일 수정
- 매치에서 일반전 / 랭크전 토글 상태에 따라 맞는 토글의 매뉴얼 모달 오픈
- 모달 닫으면 돌아가는 매치페이지에서는 모달의 토글과 상관없이 모달 진입시의 토글 상태 유지

[Feat] 매치매뉴얼 모달에 일반전 매뉴얼 추가 #487

---

components/modal/match/MatchManualModal.tsx
components/mode/modeWraps/RankModeWrap.tsx

- 랭크페이지 토글 작동 안하는 문제 #502
- 매치매뉴얼 모달에 일반전 매뉴얼 추가 #487 추가하면서 변경된 토글 컴포넌트 rank에서 작동 안하는 문제 수정

[Fix] 랭크페이지 토글 작동 안하는 문제 #502

---

components/user/BasicProfile.tsx

- 프로필 페이지에서 42레벨의 경우 경험치를 (현재 경험치) / Max Exp 로 수정
- MAX_LEVEL = 42 추가

[Fix]프로필 페이지 42레벨일 경우 경험치 Max Exp로 수정 #496

---

components/game/big/GameResultBigItem.tsx
components/game/small/GameResultSmallItem.tsx

- 게임페이지 리스트 클릭할 때마다 모든 컴포넌트 리렌더링되는 문제
- `React.memo`를 사용해 리스트를 클릭해도 리렌더링이 되지 않게 만들었습니다.
- `React.memo`는 프롭스가 바뀌지 않으면 다시 렌더링되지 않습니다!!
- 참고: https://reactjs.org/docs/react-api.html#reactmemo

[Refactor] 게임페이지 리스트 클릭할 때마다 모든 컴포넌트 리렌더링되는 문제#516

---

components/game/GameResultList.tsx
components/mode/modeWraps/GameModeWrap.tsx

- 게임페이지 기록 없을 때 터지는 버그 및 검색시 초기화 안되는 문제 해결
- GameResultList: 빅 아이템 초기 셋팅시 기록 있는지 확인하는 조건 추가
- gameModeWrap: 쿼리의 인트라 아이디 바뀔 때, 초기화되도록 수정

[Fix] 게임페이지 기록 없을 때 터지는 버그 및 검색시 초기화 안되는 문제 해결 #535

---

components/modal/statChange/StatChangeModal.tsx

- 경험치 모달 다음 알림 확인 시 에러페이지로 넘어가는 현상 처리
- statChangeModal return에 setReloadMatch 추가

[Fix] 경험치 모달 다음 알림 확인 시 에러페이지로 넘어가는 현상 처리 #508

---

components/rank/RankList.tsx

- 랭크 리스트에서 내 순위 바로가기 누를 때 스크롤이 먼저 된 다음 리스트 바뀌는 문제 해결
-  내 순위 바로가기를 눌렀을 때, async await 으로 변경된 페이지의 리스트 로드 기다린 다음 .then에서 스크롤 실행하도록 수정

[Fix] 랭크 리스트에서 내 순위 바로가기 스크롤이 먼저 된 다음 리스트 바뀌는 문제

---

components/modal/admin/AdminNotiAllModal.tsx
components/toastmsg/toastmsg.tsx

- 관리자 전체 알림 모달에 토스트 메시지 기능 추가
1. `npm i & npm run dev`
2. 브라우저 열기 (localhost:3000/admin) & `알림 관리` 선택
3. 우측 상단에 있는 [All] 버튼 클릭
4. 전체 알림 모달 내에 있는 [적용] 버튼 클릭 후 토스트 메시지 정상 작동 확인
- #655 
- #650

Feat/toast message 기능 추가 #655

---

components/modal/ModalProvider.tsx
components/modal/admin/AdminProfileModal.tsx
hooks/useUploadImg.ts
package-lock.json
pages/admin/users.tsx
pages/api/admin/users/index.ts
styles/admin/modal/AdminProfile.module.scss
types/admin/adminUserTypes.ts
types/modalTypes.ts

- 코멘트 주신 내용 적용
- console.log 제거 및 수정
- import 및 css 정렬 수정
지금 api 정보가 email로 보내서 이메일이 수정이 안되는데 오늘내로 고쳐질 것 같습니다 (명세는 eMail)
유저 role 타입도 한글 string으로 보내고 있어 바꿔주신다고 했습니다
이 두가지 내용 제외하고는 get요청, put요청 보내보시면 잘 바뀌는지 확인가능해요!

Feat/관리자 유저 모달 개선 #647

---

components/Layout/Layout.tsx
components/admin/AdminReject.tsx
styles/admin/AdminReject.module.scss

- 관리자 페이지 권한 없이 접근했을 때 접근이 가능했던 문제 수정했습니다
- 관리자 권한이 없을 경우 권한 없다는 메시지를 띄우고 홈으로 돌아가도록 하는 페이지가 보이도록 변경
- [Bug] admin에서 배경화면 깜빡임 현상 #654 이슈는 아직 해결 안됨

Fix/일반 유저가 관리자 페이지 접근 가능한 문제 #665

---

components/admin/users/UserManagementTable.tsx
components/modal/admin/AdminProfileModal.tsx
hooks/useUploadImg.ts
pages/admin/penalty.tsx
styles/admin/modal/AdminProfile.module.scss
types/admin/adminUserTypes.ts

이미지 압축기능 추가
토스트로 오류 처리 (아직 토스트가 완성되지 않아서 주석으로 처리)
여러가지 에러 처리
이메일 eMail->email로 변경 (eMail로 작성해도 백에서 자동으로 email로 바꿔준다고 합니다)
<details>
- 정보가 수정되지 않았을 때 보내는 방식 수정   
- 이미지는 수정되지 않으면 폼데이터에서 제거   
- 이미지 제외 모든 정보는 수정 여부에 상관없이 폼데이터에 추가   
- 에러 수정
- 404 에러 수정 (유저 이미지 초기값이 null인 상태로 렌더링하여 띄워주려해서 생긴 현상)
- 이미지 정보를 받아도 모달에 뜨지 않는 현상 해결
(이미지 태그의 width, height 값이 실제 이미지 크기보다 작아서 생김 -> 압축으로 크기 지정)
- 압축 기능 추가
- browser-image-compression 라이브러리를 사용하는데 에러 발생 해결
(현재 custom hook으로 파일 업로드를 따로 빼서 관리하는데 export하는 함수에 async를 제거하여 해결)
- 압축하고 보내는데 타입 관련해서 문제가 지속적으로 발생 해결
(압축된 imgData를 제대로 보내지 않아 생긴 문제)
- 에러 상태 수정
(200 정상, 207 랭크정보만 없어서 수정 불가, 400 잘못된 요청, 401 권한 없음, 413 파일 용량제한 에러, 415 파일 확장자 에러)
- 토스트 메시지로 처리
- 프로필 이미지가 없는 경우
- 현재 유저에게 보여지는 프로필은 돔의 규격에 맞지 않으면 다스베이더를 보여줍니다
하지만 관리자에게 다스베이더를 보여줄 필요는 없다고 판단하여 alt 메세지 수정 …

Feat/유저 모달 에러 관리 #666

---

components/admin/common/AdminSearchBar.tsx

- 유저 검색 기능 intraID 고정 안되는 에러 수정
1. `npm i && npm run dev` 실행
2. 관리자 페이지의 알림 관리 카데고리로 이동
3. "유저 검색하기" 입력창에 intraID 아무거나 검색
4. 추천 검색어로 뜨는 intraID 중 원하는 intraID 클릭
5. 클릭 시에 유저 검색하는 입력창에 클릭한 intraID가 자동으로 고정이 되는지 확인 
- #701

[Fix] 유저 검색 intraID 고정 안되는 에러 수정 #701

---

components/admin/notification/CreateNotiButton.tsx
components/modal/ModalProvider.tsx
components/modal/admin/AdminNotiAllModal.tsx
components/modal/admin/AdminNotiUserModal.tsx
styles/admin/modal/AdminNoti.module.scss

- 관리자 페이지의 특정 유저 알림 모달 내의 "유저 검색하기" 기능의 에러를 수정하였습니다.
**Before**
Before 사진에서는 일치하는 intra ID를 클릭하고 나서도 하단의 dropDown 부분이 사라지지 않는 상태인 것을 확인할 수 있습니다
**After**
코드를 수정한 뒤 정상적으로 dropDown 부분이 사라진 것을 확인할 수 있습니다
label로 감싸져 있었던 부분을 div 태그로 변경해주었습니다.
**Before**
**After**
- 불필요한 주석 삭제
- 불필요한 prop 삭제
- #706

 [Fix] 관리자 특정 유저 알림 모달 내 유저 검색하기 기능 에러 수정 #669

---

components/modal/admin/AdminProfileModal.tsx

- 0승 0패일 때 ppp 1000으로 고정. 승 패가 바뀌지 않는데 ppp가 바뀌면 랭크 정렬이 되면서 순위가 -로 뜨는 현상 때문에 예외처리 하였습니다. 나중에 백에서 로직을 바꾸면서 같이 수정될 부분입니다!

[Feat] 승,패가 0일 때 ppp 1000으로 고정 #733

---

README.md
components/Layout/MenuBar.tsx
components/Layout/NotiItem.tsx
components/admin/games/GamesTable.tsx
components/admin/notification/NotificationTable.tsx
components/admin/slot/SlotCurrent.tsx
components/admin/slot/SlotMain.tsx
components/game/big/GameResultBigTeam.tsx
components/match/MatchBoard.tsx
components/modal/admin/AdminPenaltyModal.tsx
components/modal/profile/EditProfileModal.tsx
styles/admin/common/Pagination.module.scss
styles/admin/feedback/FeedbackTable.module.scss
styles/admin/games/GamesTable.module.scss
styles/admin/modal/AdminFeedbackCheck.module.scss
styles/admin/modal/AdminNoti.module.scss
styles/admin/modal/AdminPenalty.module.scss
styles/admin/modal/AdminProfile.module.scss
styles/admin/modal/DeletePenaltyModal.module.scss
styles/admin/notification/NotificationTable.module.scss
styles/globals.css
styles/load/CommingSoon.module.scss
styles/modal/afterGame/AfterGameModal.module.scss
styles/modal/afterGame/StatChangeModal.module.scss
types/admin/gameLogTypes.ts
types/admin/tableTypes.ts
utils/infinityScroll.ts

- 몇몇 error 해결 및 리팩토링
- ts error 수정
- type error 수정
- css error 수정
- css 중복 프로퍼티 리팩토링
- 중복변수 인라인화 해 리팩토링
- 사용하지 않은 import 삭제
- 기타 자잘한 리팩토링
- #740

Fix/몇몇 ts error 해결 및 리팩토링 #740

---

components/admin/feedback/FeedbackTable.tsx
components/modal/admin/AdminFeedbackCheckModal.tsx

- **관리자 피드백** 페이지 api 수정
- 🛠 **피드백 처리 상태 변경** 🛠
수정 전: pingpong/admin/feedback/is-solved
수정 후: pingpong/admin/feedback/{feedbackid}
- 🛠 **피드백 유저명 검색 조회** 🛠
수정 전: pingpong/admin/feedback/users?q=${keyword}&page=${pageNumber}
수정 후: pingpong/admin/feedback?intraId=${intraId}&page=${pageNumber}&size={size}
- 🛠 **피드백 전체 조회** 🛠
수정 전: pingpong/admin/feedback?page=${pageNumber}&size?=${recordSize}
수정 후: pingpong/admin/feedback?page=${page}&size?=${size}
-

[GGFE-13] Admin - Feedback

---

components/Layout/MenuBar.tsx
components/Layout/NewMenuBar/MenuBarElement.tsx
components/Layout/NewMenuBar/MenuBarProvider.tsx
components/modal/match/MatchManualModal.tsx
components/mode/modeItems/SeasonDropDown.tsx
components/mode/modeWraps/MatchModeWrap.tsx
components/rank/RankList.tsx
components/rank/topRank/RankListItemMain.tsx
components/rank/topRank/RankListMain.tsx
hooks/Layout/useGetUserSeason.ts
hooks/mode/useSeasonDropDown.ts
pages/rank.tsx
types/mainType.ts
types/seasonTypes.ts
utils/recoil/seasons.ts

- seasonlist api 변경
- 시즌별 이름 리스트 조회
수정전
/pingpong/seasonlist
```
seasonmode: 'both'
[{
id: number
name: string
},{…}]
```
수정후
```
/pingpong/seasons
{
"seasonList": [
{
"id": 0,
"name": "string"
}
]
}
```
---
- 수정 전에는 seasonList[0]에 최신 시즌이 있었으나 수정후 마지막에 오는 것으로 바뀌었습니다.
- seasonMode를 주던 방식에서 삭제하고 기본으로 rank를 사용
-

[GGFE-36] seasonlist

---

components/modal/statChange/StatChangeModal.tsx
hooks/modal/aftergame/useCurrentGame.ts
hooks/modal/aftergame/useSubmitModal.ts
hooks/useAxiosGet.ts
types/gameTypes.ts
types/scoreTypes.ts

**게임 종료 후 결과 등록**과 **게임 결과 조회** api 수정
- 전 : /pingpong/games/result/rank
- 후 : /pingpong/games/rank
request body가 본인/상대 점수만 보내주던 방식에서 **본인/상대 점수 포함 게임 ID와 본인 팀/상대 팀 ID까지 보내주는 것으로 변경**되어 해당 부분 수정하였습니다.
관련된 타입의 속성명들을 api 명세와 동일하게 수정하였습니다 (teams -> players)
- 전 : /pingpong/games/result/normal
- 후 : /pingpong/games/normal
request body가 기존 아무것도 보내지 않던 것에서 **게임 ID와 본인 팀/상대 팀 ID 보내주는 것으로 변경** 되어 해당 부분 수정하였습니다.
❗️추가되는 팀 ID는 이후에 작업할 API에서 새로 받아오게 되어 현재는 타입만 (`types/scoreTypes.ts` 의 `Team`) 추가해두었습니다.
api 변경사항은 없고 `GameResult` 타입으로 response body에 대한 타입만 지정해주었습니다.
---
**❗️ 백에 아직 해결되지 않은 이슈가 있어서 테스트 전입니다 ❗️**
-

[GGFE-16] Game - 게임 결과 등록과 조회

---

components/mode/modeWraps/GameModeWrap.tsx
hooks/game/useGameResult.ts
next.config.js

- 게임 결과 목록 테스트 중 발견된 버그 "일부" 수정했습니다.
- 전체 게임 목록에서 시즌 드롭다운이 보이는 문제
→ radioMode 조건이 잘못되어있어 수정했습니다.
- 랭크 게임 목록에서 api 요청이 안되는 문제
→ query key 값을 잘못 전달하고 있어서 수정했습니다.
- 목록 조회 시에 더보기를 눌렀을 때 Error: Invalid src prop 발생
→ next.config.js domain에 'cdn.intra.42.fr' 추가해주었습니다.
---
❗️ **전체 / 랭크 게임 목록에서 유저 검색 시에도 전체 게임이 나오는 문제**는 api response 자체에 문제가 있어서 확인 부탁드린 상태입니다...
-

[GGFE-55] 게임 결과 목록 버그 수정

---

hooks/game/useGameResult.ts

- 게임 목록 리스트 요청 시에 발생하는 문제들을 수정했습니다.
- 메인 화면의 최근 게임 3개를 보여주는 부분에서 임의로 첫번째 페이지를 보여주도록 `page=1`을 넣어 주었는데, `InfScroll`에서 초깃값으로 `page=1` 을 넣게 되어 쿼리가 중복되는 문제가 있어서 임의로 `page=1`을 넣어주는 부분을 삭제해주었습니다.
- `mode`에 대한 예외처리가 덜 되어있어 undefined error가 나는 부분을 수정했습니다.
-

[GGFE-55] 게임 목록 리스트에서 발생하는 문제 수정

---

components/match/MatchBoard.tsx

- matchSlot 버튼 스타일 + headCount 잘못나오던 부분 수정
- matchSlot에서 본인이 잡은 경기를 기존에는 mytable로 받던 것에서 close로 status를 변경되면서 close status의 경우 currentMatch와 startTime을 비교하여 버튼 스타일 적용하는 부분 추가
- headCount는 괄호 수정
-

[GGFE-59] Match button 스타일 +  headcount 수정

---

components/mode/modeWraps/RankModeWrap.tsx
components/rank/MyRank.tsx
components/rank/RankList.tsx
components/rank/RankListFrame.tsx
components/rank/RankListItem.tsx
hooks/mode/useModeToggle.ts
hooks/mode/useSeasonDropDown.ts
hooks/rank/useRankList.ts
pages/rank.tsx
types/rankTypes.ts
utils/recoil/myRank.ts

- myrank api가 -1로 변경되어 수정, togglemode 타입 변경 
- myrank의 시즌에 게임을 한번도 안했다면 주는 값이  0에서 -1로 변경되어 주정했습니다
- togglemode의 타입을 matchmode로 사용했었는데 toggle특성상 normal, rank두개 만 사용함으로 변경했습니다. 
- togglemode의 타입을 대문자로 변경하였습니다.
-

[GGFE-42] 0->-1로 변경 togglemode 타입 변경

---

components/modal/afterGame/Guide.tsx
components/modal/afterGame/NormalGame.tsx
components/modal/statChange/StatChangeModal.tsx
hooks/modal/aftergame/useSubmitModal.ts
types/gameTypes.ts

- 게임 후 결과 입력에 대한 api 변경사항 적용
- 변경이 덜 되었던 api url 변경사항과 MatchMode 타입 변경사항 적용했습니다.
- modalMode 타입을 MatchMode 타입으로 사용하면 'BOTH' 값이 없는 것에 문제가 있어서 따로 리터럴 타입으로 만들었습니다.
- modalMode 중 confirm modal을 사용하는 부분이 없는 것 같은데, 모든 경우를 테스트해본게 아니라 일단 주석으로 남겨두었습니다.
~~❗️ statChangeModal에 표시되는 값이 이상한 것은 api response 가 이상했던 것이라 수정된 api 배포되면 확인해보고 수정사항 있을 시에 다시   PR 올리겠습니다!!~~
확인 완료

[GGFE-39] 게임 결과 입력

---

components/Layout/NotiBar/NotiElements.tsx
components/Layout/NotiBar/NotiItem.tsx

- Noti Imminent일 때 메세지 파싱이 안되고 빈 문자열만 반환되던 것 수정
-  Noti type에 따라 조건부 파싱하던 것에서 메세지 생성하는 부분에서 파싱하도록 변경
- message null인 경우 noti item map으로 돌 때 따로 다른 컴포넌트 생성하게 변경
- 그 외에 noti title style에서 에러나는 것은 지금은 쓰지 않는 canceledbyman같은 타입이 들어오면 없는 타입이라 에러가 뜸
- 새로 올릴 때는 백에서 기존 사용자들 노티 다 날려달라고 말해놨습니다.
-

[GGFE-61] Noti Imminent일 때 메세지 파싱 안되던 부분 수정

---

components/modal/ModalProvider.tsx
components/modal/match/MatchManualModal.tsx
components/mode/modeItems/ModeRadiobox.tsx
components/mode/modeWraps/GameModeWrap.tsx
components/mode/modeWraps/MatchModeWrap.tsx
stories/game/ModeRadiobox.stories.tsx
stories/modal/MatchManualModal.stories.tsx
styles/common.scss
styles/modal/match/MatchManualModal.module.scss
styles/mode/ModeRadiobox.module.scss

- Match 페이지의 게임 매뉴얼 모달 디자인 적용
**ModeRadioBox 사용 때문에 46번 브랜치에서 분기해서 작업했습니다!!!**
- 게임 매뉴얼 모달 디자인 적용했습니다. 
- 매뉴얼 모달의 라디오 버튼과 Match 페이지의 라디오 버튼의 id가 겹쳐서 label 태그가 동작하지 않는 문제가 있어서 label 태그의 for 속성을 제거했습니다.
- Modal 디자인에서 자주 쓰일 것으로 보이는 CSS들을 mixin으로 분리했습니다.
**❗️ 기존과 겹치는 Mixin들이 있어 완전히 정리하지 못했습니다..!
❗️ "전체" 매치 모드에 대한 매뉴얼 작성 필요합니다!!**

[GGFE-64] 게임 매뉴얼 모달 스타일 적용

---

components/match/MatchBoard.tsx
components/mode/modeWraps/MatchModeWrap.tsx
hooks/match/useGetReloadMatchHandler.ts
pages/match.tsx
styles/common.scss
styles/match/MatchBoard.module.scss
styles/match/match.module.scss

- match slot 스타일 적용
- 메뉴얼, 리로딩 버튼을 라디오 버튼 윗쪽으로 위치 수정
- status가 mytable일 때 로직 수정. (신청한 모드가 아닌 다른 모드일 때 색만 초록색, 버튼 클릭 불가)
- 슬롯 색 변경
-

[GGFE-48] 슬롯 스타일 적용

---

components/Layout/Layout.tsx
styles/Layout/Layout.module.scss

- Play 버튼이 레이아웃 헤더 아래에 공간 차지하던 문제 해결
- 기존에 헤더와 layout의 본문 사이에 존재하던 빈 공간(play button이 차지하던 공간) 없앰
- div로 button 한 번 더 감싸고 기존 css  적용
-

[GGFE-76] Style Play Button 레이아웃 헤더 아래 공간차지 문제 해결

---

components/modal/afterGame/Guide.tsx
components/modal/afterGame/RankGame.tsx
hooks/modal/aftergame/useSubmitModal.ts
stories/modal/AfterGameModalNormal.stories.tsx
stories/modal/AfterGameModalRank.stories.tsx

- 랭크 게임의 결과를 중복으로 제출했을 때 에러로 처리되던 부분을 수정했습니다.
- 기존과 중복된 제출을 처리하는 방식이 달라져서 alert을 띄우는 방식을 수정했습니다.
- 중복된 제출시에 발생하는 에러 코드는 2개인데 (저장된 점수와 입력한 점수가 다름, 이미 저장된 점수가 있음) 동일한 의미라 생각해서 같은 메시지를 띄우게 했습니다.
- 사용하고 있지 않던 `CONFIRM` 가이드를 점수가 존재하는 경우에 보여주게 수정했습니다.
- 저장된 점수가 존재하는 경우에는 한번 더 모달을 띄워서 점수를 확인할 수 있게 했습니다.
❗️ 일반게임의 경우에는 제출한 뒤에 한번 더 모달이 뜨는 문제가 있는데, users/live의 응답이 맞지 않는 문제라 나중에 확인 필요합니다!
-

[GGFE-65] 점수 중복 제출시 에러 해결

---

components/Layout/NotiBar/NotiBar.tsx
hooks/Layout/useSetAfterGameModal.ts
styles/Layout/MenuBar.module.scss
styles/Layout/NotiBar.module.scss
styles/Layout/NotiItem.module.scss

-  Noti reload 읽음상태 변경으로 바뀌지 않았던 부분 수정
- Match 취소하면 opencurrentMatch 다시 false로 바뀌게 수정
- put 요청과 get요청 동시에 들어갔던 부분 async await 추가
- live event - match 상태에서 매칭 취소해서 null로 변하면 openCurrentMatch가 다시 false로 바뀌게 수정)
-

[GGFE-68] Noti reload error + currentMatch error 수정

---

components/Layout/Layout.tsx
components/mode/modeWraps/GameModeWrap.tsx
components/mode/modeWraps/MatchModeWrap.tsx
hooks/useColorMode.ts
pages/game.tsx
pages/match.tsx
styles/Layout/Layout.module.scss
styles/main/SearchBar.module.scss
utils/recoil/colorMode.ts
utils/recoil/toggle.ts

- Game페이지와 Match페이지에서 선택한 모드에 따라 배경색이 바뀌도록 했습니다.
- `colorModeState`에서 배경색 상태를 관리합니다! 토글에서 사용할 수 있을 것 같은 selector를 만들어보긴 했는데 잘 동작할지는 모르겠어요..
- `useColorMode` 훅에서 마운트시에 사용한 페이지에 따라 초기 `colorMode`를 설정해주고 언마운트시에 reset하도록 했습니다. rank페이지 다시 작업할 때 초깃값 설정해주시면 될 것 같아요.
- 그리고 import 순서가 좀 뒤죽박죽인 부분이 있어서 보이는 것들만 조금 수정했습니다!
- SearchBar 부분이 기존 보라색 배경 기준으로 되어있었어서 season dropdown 배경색과 동일하게 반투명한 배경으로 수정했습니다!

[GGFE-89] 선택한 모드에 따라 배경색 변경하기

---

styles/PlayerImage.module.scss
styles/game/GameResultItem.module.scss

- GameResultItem 속 글자들의 크기를 수정했습니다.
- 큰 화면(ex: 클러스터 맥)에서 봤을 때 `GameResultItem` 속 글자들이 너무 작게 보여서 전반적으로 크기를 수정했습니다.
- 추가로  figma의 px을 그대로 rem으로 변환하느라 소수점 자릿수가 지저분한 값들을 수정했고
- 불필요해보이는 `line-height` 설정과 `letter-spacing` 설정을 삭제하고
- `GameResultBigItem` 의 `height`로 설정해둔 값이 내부 컴포넌트보다 작아서 정렬이 잘 안되는 문제가 있어 `min-height`로 수정했습니다.
-

[GGFE-101] GameResultItem 폰트 크기 수정

---

components/main/Section.tsx
styles/Layout/CurrentMatchInfo.module.scss
styles/main/Section.module.scss

- main Searchbar-ranking 간격 수정
- sectionWrap에서 ranking 일 때만 margin-top 크기 줄였습니다
- currentMatch 3개 잡았을 때 드롭다운이 클릭이 안되는 경우가 있어서 z-index를 searchbar와 동일한 2로 부여해줬습니다.
- 추가로 currentMatch 드롭다운 버튼에 cursor: pointer 추가했습니다
-

[GGFE-104] main Searchbar-ranking 간격 수정

---

components/modal/afterGame/InputScore.tsx
hooks/modal/aftergame/useRankGame.ts

점수를 입력했다 지우면 `NaN`이 되는 문제를 수정했습니다
fix #768 
- input의 값이  `''`가 된 경우에 `intValue`의 값이 `NaN`이 되어서 발생했던 문제라 `intValue`가 `NaN`인 경우에는 `''`로 `value`를 설정하는 조건을 추가했습니다.
- input 옆의 화살표를 눌렀을 때 입력할 수 있는 값의 범위를 추가했습니다.
-

[GGFE-100] 점수 입력 NaN 에러

---

hooks/modal/match/useMatchEnrollModal.ts
hooks/modal/useEditProfileModal.ts

- 메인에서 카카오 로그인으로 인한 에러일시 error 페이지가 아닌 alert 문구를 띄우게 수정
- JH05/JH02 error 일때 403 (권한) 에러면 alert 문구를 띄우게 했습니다!
-

[GGFE-83] 메인 403에러 alert 추가

---

components/admin/games/GamesTable.tsx

- 게임 관리에서 예전 데이터 처리 안되던 문제 수정
game mode가 소문자 형식 ('rank', 'normal')에서 대문자 형식 ('RANK', 'NORMAL')으로 바뀌었는데, 예전 데이터의 정보는 그대로라 처리되지 않는 문제였습니다.
game mode를 대문자로 바꾼 뒤에 처리하도록 수정했습니당
-

[GGFE-111] 게임 관리 에러 수정

---

pages/match.tsx
styles/match/match.module.scss

- match slot 열린 슬롯이 없습니다 로직 수정
- getFirstOpenSlot 로직 적용안되던 부분 수정
- 열린 슬롯이 없습니다 css 수정
-

[GGFE-117] bug match slot

---

cypress/e2e/game.cy.ts
cypress/e2e/match.cy.ts
cypress/support/commands.ts

- Game 테스트 코드 수정했습니다.
- Game 테스트코드 변경된 컴포넌트에 맞춰서 수정했습니다.
---
Match 테스트 코드는 당장 모든 테스트 시나리오를 정의하기 어려워서 일단은 그대로 두었습니다.. 😇
정리해둔 테스트 시나리오대로 직접 테스트해봐야 할 것 같아요
-

[GGFE-99] game 테스트 코드 수정

---

README.md

- 3기 정보, 이번에 업데이트 된 내용에 대한 내용 추가
- 상단 로고 사진을 favicon 이미지로 바꾸었는데 괜찮은지 모르겠네요...
- 3기 정보 추가했습니다. 정보 제대로 적혀 있는지 확인해주세요!
- 업데이트 된 디자인이랑 기능에 대한 스크린샷이랑 설명 추가했습니다. 기존에 적혀있던 설명에는 말투(?)가 좀 섞여 있어서 어색한거같기도 한데 어떤 식으로 적는게 좋을지 모르겠네요...
- 이 외에도 읽어보시고 뭔가 추가하거나 수정하고 싶은 내용 있으시면 말씀해주세용
- 상단 로고 사진을 favicon 이미지 + 글자 로고 이미지로 넣었는데 두개 같이 넣으니까 제가 보기엔 좀 어색한 것 같습니다.. 둘 중 하나만 넣거나 다른 방법으로 넣는게 좋을 것 같아요..;;

[GGFE-129] readme 업데이트

---

hooks/game/useGameResult.ts

- 카톡 연동 이후 ranklist 목록 오류 수정
- 카카오톡 연동을 하면 로그인을 새로 시켜서 token을 쿼리에 붙여주는데 
이때를 main으로 간주해서 프로필에서 전체 최근 목록을 불러오는 현상 수정
- dev.42gg.kr에 수정된 코드 올라와있어서 카카오톡 연동 후에 하단 ranklist 목록이 어떻게 다른지 비교해보시면 될 것 같아요
-

[BUG] [GGFE-136] kakao 연동 이후 ranklist 목록 오류 수정

---

.husky/pre-commit
.husky/prepare-commit-msg

- 배포하면서 사라졌던 husky 설정을 복구하고 지라 이슈 키를 커밋메시지에 포함시키는 스크립트를 추가했습니다.
prepare-commit-msg 내용
- main, dev,(저흰 dev 브랜치가 없지만 혹시 몰라 추가해뒀습니다), deploy를 제외한 브랜치명은 GGFE-숫자 로 시작해야 합니다. (지라에서 브랜치 만들면 규칙대로 만들어집니다)
- [Feat] [issue_key] commit message 형식으로 커밋 메시지를 만들어줍니다.
- 만약에 커밋 메시지에 이슈 키가 있으면 브랜치명의 이슈 키와 비교해서 동일하면 바로 커밋하고, 아닌 경우에는 에러를 띄웁니다.
-

[GGFE-139] husky prepare-commit-msg 추가

---

components/Layout/Layout.tsx
components/Layout/MenuBar/MenuBarElement.tsx
components/mode/modeItems/ModeRadiobox.tsx
components/mode/modeItems/RadioBoxWrapper.tsx
components/mode/modeItems/StoreModeRadioBox.tsx
components/mode/modeWraps/StoreModeWrap.tsx
hooks/useAxiosGet.ts
pages/api/pingpong/users/coin.ts
pages/store.tsx
styles/mode/ModeRadiobox.module.scss
styles/mode/StoreModeWrap.module.scss
styles/store/StoreContainer.module.scss
types/storeTypes.ts
types/userTypes.ts
utils/mockAxios.ts

- 상점 페이지에 필요한 레이아웃을 구현하고, mock api를 사용하기 위한 설정을 추가했습니다.
- 상점 페이지 레이아웃
- 상점 페이지 이동은 현재 새로고침시에 로그인이 풀리는 문제가 있어서 사이드바 버튼으로 이동해야 로그인 페이지로 리다이렉트되지 않습니다.. (대충 만든거라 이미지는 랭크와 동일해요)
- `/store` 안에서 state에 따라 상점, 구매 컴포넌트를 보여주는 방식입니다.
- 디자인은 대부분 다른 페이지에서 사용된 디자인을 가져왔습니다... (대부분 match 페이지) 이후에 구현하실 때 적절하게 수정해주시면 될 듯 합니다.
- useMockAxiosGet
- api 폴더에 정의된 api들을 불러오기 위한 훅입니다.
- useAxiosGet이랑 완전히 동일하게 동작하도록 했어요.
- get 외에 다른 메소드를 사용할 때에는 mockInstance 를 사용해서 기존 instance와 동일하게 사용하면 됩니다.
-

[GGFE-143] 상점 페이지 레이아웃

---

components/modal/ModalProvider.tsx
components/modal/store/purchase/BuyModal.tsx
components/modal/store/purchase/GiftModal.tsx
components/shop/ItemCard.tsx
components/shop/ItemsList.tsx
hooks/modal/store/purchase/useBuyModal.ts
hooks/modal/store/purchase/useGiftModal.ts
pages/api/pingpong/items/store.ts
pages/store.tsx
styles/modal/store/BuyModal.module.scss
styles/modal/store/GiftModal.module.scss
styles/store/ItemCard.module.scss
types/itemTypes.ts
types/modalTypes.ts

- 상점 페이지 구매 가능 아이템 목록
- useMockAxiosGet 사용하여 아이템 리스트를 받아옴
- 아이템 카드 컴포넌트에서 아이템 별 상세 정보 띄움
- 선물, 구매 버튼 클릭시 각 모달 띄워줌
- CSS 디자인 논의 후 추후 수정 필요할 것 같습니다

[GGFE-145] 상점 구매페이지

---

components/mode/modeWraps/StoreModeWrap.tsx
components/store/InfiniteScrollComponent.tsx
components/store/Inventory.tsx
components/store/InventoryItem.tsx
components/store/InventoryList.tsx
pages/api/pingpong/items/index.ts
pages/store.tsx
styles/store/Inventory.module.scss
types/storeTypes.ts
utils/infinityScroll.ts

- 상점 보관함 아이템 페이지의 기본적인 기능과 디자인을 추가했습니다.
- 상점 보관함 데이터 api를 이용해서 유저가 가지고 있는 아이템 목록을 보여주게 했습니다.
아래 주석 수정해서 빈 경우, 페이지가 1개인 경우, 페이지가 2개인 경우 테스트 해 볼수 있어요,
```typescript
// NOTE: 테스트 케이스에 맞춰서 다른 데이터를 보내주면 됩니다.
// const InventoryData: InventoryData = InventoryDataEmpty;
// const InventoryData: InventoryData = InventoryDataSingle;
const InventoryData: InventoryData = InventoryDataDouble;
```
- 무한 스크롤 기능을 추가해서 가장 아래로 스크롤이 내려가면 새로 api를 불러오게 했습니다.
- **❗️ 상점 아이템 디자인 피드백 부탁드립니다!!! ❗️** (피그마에 정의해놨던 디자인으로는 아이템 설명이 없을 때 허전해져서 구조를 바꾸었어요)
- 선물받은 아이템은 상단에 선물상자 아이콘이 뜨고, hover하면 선물한 사람의 intra id가 뜹니다.
- 사용중인 아이템은 상단에 사용중 표시가 뜹니다.
- 아이템 컴포넌트에 hover했을 때 사용전인 아이템에는 사용하기, 사용중인 아이템에는 편집하기 버튼이 뜹니다. (버튼 기능은 아직 구현 전)
- **❗️ 아이템 이미지 css 속성을 `object-fit: cover;` 로 할지 `object-fit: contain;` 로 할지 고민중인데 의견 부탁드립니다❗️**
-

[GGFE-144] 상점 아이템 보관함 페이지

---

components/modal/ModalProvider.tsx
components/modal/store/inventory/ChangeIdColorModal.tsx
components/modal/store/inventory/ColorPicker.tsx
components/modal/store/inventory/IdPreviewComponent.tsx
components/rank/RankList.tsx
components/rank/RankListItem.tsx
package-lock.json
package.json
pages/api/pingpong/items/index.ts
pages/api/pingpong/users/text-color.ts
styles/modal/store/ColorPicker.module.scss
types/inventoryTypes.ts

- 랭크 페이지의 이름 색상 변경 아이템을 사용하기 위한 모달
- 미리보기
- 기존 `RankListItem` 컴포넌트를 이용해서 미리보기 블록을 만드려고 했었는데 `RankListItem` 컴포넌트가 너무 복잡해서,, 바로 수정이 안될 것 같아 일단은 배경이랑 글씨 색만 확인할 수 있게 대강 만들어 두었습니다... (글씨 삐져나와있는 점 미리 죄송합니다...)
- `RankListItem` 컴포넌트를 활용하게 된다면 기존의 RANK와 NORMAL 모드를 같은 컴포넌트에서 처리하던 방식에서 두 모드를 각각 처리하는 식으로 변경하려고 하고, 색깔 미리보기에서는 상태메시지를 제외한 정보만 보여줄까 합니다!
- 색깔 선택
- `<input type="color">` 를 사용하게 되면 버튼 스타일링이 어렵고, hex color 코드를 직접 입력받기 까다로워져서 **react-colorful** 라이브러리를 설치했습니다! **❗️실행 전에 npm install 실행해주세요❗️**
- 색깔 버튼을 눌러서 컬러 팔레트를 열고 닫을 수 있게 했습니다. 열고 닫는게 좋을지 아니면 기본적으로 보여주고 있는게 나을지는 잘 모르겠어요 🥲
- hex color 코드를 직접 입력할 수 있습니다! 빈 경우에는 기본값인 `#000` 이 들어가고 유효하지 않은 입력의 경우에는 _아마도_ 가장 가까운 유효한 입력으로 들어가는 것 같아요.
- 변경하기
- 적용 결과를 직접 확인하기는 어려워서 응답 결과를 확인하게만 했습니다..
- 추가로 rank api 응답 결과에도 색깔 항목이 들어가야 하는데 이 부분은 api 명세가 아직 안나와서 …

[GGFE-154] 상점 이름 색상 변경 모달

---

components/Layout/MenuBar/MenuBar.tsx
components/user/BasicProfile.tsx
pages/api/pingpong/users/intraId.ts
styles/Layout/MenuBar.module.scss
styles/common.scss
styles/user/Profile.module.scss
utils/recoil/tierColor.ts

- tier 배경 색상 변경
- 배경 투명도를 내려서 가독성을 올렸습니다.
- 넘버로 값을 받는 대신 스트링으로 받아서 무슨 색상인지 확인이 편하실것같습니다.
-

[GGFE-179] tier 색상부분 수정

---

styles/admin/common/Pagination.module.scss
styles/globals.css

closes #769
페이지네이션 페이지 크기가 커졌을 때 숫자가 겹치는 부분을 수정했습니다.
기존 문제는 관리자 페이지에서 발생하고 있었는데 이 부분은 예전 PR에서 해결되었던 문제였습니다 😂
관리자 페이지에서 해결한 방법은 페이지 번호 태그의 너비를 넓혀주는 방법인데요.
이렇게 하면 자릿수에 상관없이 페이지네이션 자체의 너비가 고정되는 장점이 있지만 나중에 자릿수가 더 커지면 또 다시 동일한 문제가 발생할 것 같아서 너비를 고정하지 않고 margin을 주는 방식도 관리자 페이지와 일반 페이지 모두에 추가해보았습니다.
둘 다 확인해보시고 괜찮은 방법 알려주시면 그 방법으로 적용할게요.
-

[GGFE-181] 페이지네이션 겹침현상

---

components/mode/modeWraps/StoreModeWrap.tsx
pages/store.tsx

- 유저 보유 코인 조회 api 연결했습니다.
- 기존 mock api로 되어있던 코인 api를 실제 api로 변경했습니다.
- 상점 페이지 내에서 코인을 사용하는 경우 코인이 줄어든 내역을 새로 받아올 수 있게 state를 만들었습니다. 코인을 사용한 뒤에 `setUpdateCoin`로 `updateCoin` 값을 `true`로 설정하면 코인을 새로 받아옵니다.
(서버 측에 업데이트 된 매치 정보를 다시 받아오는 로직도 `reloadMatchState`라는 리코일로 관리하고 있어서 코인 업데이트 방식도 동일하게 프론트에서 관리하는 식으로 처리했는데 나중에 여유 되면 react-query 로 관리하는 쪽으로 바꾸는 것도 좋을 것 같습니다 ^_ㅜ)
-

[GGFE-205] 유저 보유 코인 조회 api 연결

---

components/modal/CoinPopcon.tsx

- 코인팝콘 에러부분 수정
- MouseEvent를 react로 사용하고 있어서 에러가 발생해서 수정했습니다.
-

[GGFE-212] 코인팝콘 에러 수정

---

components/EmptyImage.tsx
components/store/InventoryItem.tsx
components/store/InventoryList.tsx
styles/EmptyImage.module.scss
styles/store/Inventory.module.scss

- 아이템 보관함 조회 api 연결했습니다
- 보관함 페이지에서 현재 유저의 보관함 내역을 확인할 수 있습니다.
- 아직 구매, 아이템 사용 api가 연결된게 없어서 구매랑 사용은 swagger로 테스트해보셔야 합니다 🥲
- **🤔 빈 보관함인 경우의 메시지가 기존에는 리스트 상단에 있었는데 가운데로 옮겼습니다. 뭔가 비어있는 느낌이 드는 것 같은데 좋은 아이디어 받습니다 ㅎㅎ.. 😥**
-

[GGFE-206] 아이템 보관함 조회 api 연결

---

hooks/modal/store/purchase/useBuyModal.ts
hooks/modal/store/purchase/useGiftModal.ts
pages/store.tsx
utils/recoil/updateCoin.ts

- 구매/선물 이후에 업데이트된 코인을 받아올 수 있도록 했습니다.
- store 페이지 내에서 구매/선물 성공시에 `updateCoin(true)`를 호출해서 최상위 페이지 컴포넌트에서 새로 coin api를 호출할 수 있게 했습니다.
- 나중에 업데이트 방식을 react-query로 변경할 가능성도 있습니다 😇
-

[GGFE-223] 코인 업데이트 로직 추가

---

components/Layout/MegaPhone.tsx
styles/Layout/MegaPhone.module.scss

- 확성기 개수 제한 없이 작동하는  로직으로 변경
- ~~기존에 확성기 10개로 생각하고 작성하였던 확성기 css를 최대 1000개까지 받을 수 있게 변경했습니다.~~
- ~~1000개는 임의로 설정한 값이라 더 큰 값이 필요하다면 바꾸기만 하면 됩니다.~~
- 피드백 주신 내용 반영하여 div에 style 직접 주는 방식으로 변경했습니다!
- megaphone 기본값을 관리자 멘트 -> 관리자 + 아이템 설명으로 변경해봤습니다.(피드백 환영합니다)
- megaphone.tsx 파일에서 테스트용 temp로 확성기 내용 개수 조절해서 테스트 해보실 수 있습니다.
- (66번 줄 for문 조작하시면 됩니다. 넘어가는 시간은 78번 줄의 useInterval 값 조정해주시면 됩니다.)
- 주석과 temp는 리뷰 끝나면 merge하기 전에 다 지우겠습니다
-

[GGFE-225] 확성기 개수 제한 없이 작동하게 css 변경

---

components/modal/store/inventory/EditMegaphoneModal.tsx

- 확성기 데이터 기본 문구를 ‘오류’로 해서 로딩 전에도 ‘오류’문구가 떠서 어색한 문제 해결
기존에는 `content  === ''` 인 경우에 `failMessage`를 띄우게 했었는데요.
데이터 로딩이 실패하는 경우에는 `setError`로 에러 페이지로 리다이렉트 되도록 처리되어있어서 실제로 에러가 발생했을 때 `failMessage`를 보는 상황이 없었습니다.
그래서 `failMessage` 대신 `loadingMessage`로 변경해서 실제 데이터 로드 전에 로딩 메시지를 띄우도록 했습니다.
-

[GGFE-242] 확성기 데이터 로딩 문구 수정

---

components/rank/topRank/RankListItemMain.tsx
styles/rank/RankListMain.module.scss

- 일반랭커인경우 티어표시되는 문제 수정
- 일반랭커인경우 (트로피에) 티어표시가 안되게 수정했습니다.
- 이름이 너무 길경우 가운데 정렬이 안되는 부분 수정했습니다.
-

[GGFE-246] 일반랭커 트로피에 티어 표시 제거

---

styles/modal/match/MatchManualModal.module.scss
styles/modal/store/StoreManualModal.module.scss

- 매뉴얼 스타일 수정
- 가운데 매뉴얼 내용 컨테이너 상하 길이를 더 키웠습니다
-

[GGFE-250] 매뉴얼 스타일 수정

---

components/error/Error.tsx
components/modal/store/purchase/BuyModal.tsx
components/modal/store/purchase/GiftModal.tsx
components/store/InventoryList.tsx
constants/store/purchaseAlertMessage.ts
styles/common.scss
styles/modal/store/CoinHistoryDetails.module.scss

- 상점 모달 에러 메시지 정리 및 기타 수정
- 상점 에러메시지를 purchaseAlertMessage에 정리했습니다
- 선물 모달 주의사항 문구가 길어서 수정했습니다
- 에러 페이지에서 resetModal을 호출해 모달을 끄도록 했습니다.
- 보관함 무한 스크롤에서 page가 null일 때 에러를 page=1로 수정해서 해결했습니다
- 코인 내역 히스토리에 단어기준 줄바꿈 적용했습니다
-

[GGFE-254] 상점 모달 에러 메시지 정리 및 기타 수정

---

components/store/InventoryList.tsx
utils/infinityScroll.ts

- 보관함 무한스크롤에서 발생하는 버그를 수정했습니다.
마지막 페이지의 마지막 아이템을 사용하는 경우에 해당 페이지가 삭제되고 마지막 페이지가 달라지면서 `page=null`을 요청하는 문제가 있었습니다. 그래서 `page=null`인 경우에 1페이지를 요청하도록 고치기로 해서 #1012 에 같이 올려주셨는데요. 이렇게 고쳤더니 마지막 페이지에 이어서 다시 1페이지를 불러오는 문제가 발생했습니다..
알아보니 이 문제는 `useInfiniteQuery`에서 `pageParam`이 `null`이 아니라 `undefined`인 경우를 마지막 페이지로 판단했기 때문이었어서
`getNextPageParam` 함수에서 마지막 페이지일 경우에 `null`이 아닌 `undefined`를 반환하도록 고쳐서 문제 해결했습니다 
-

[GGFE-260] 보관함 무한스크롤 버그 수정

---

components/modal/store/UserCoinHistoryModal.tsx
components/modal/store/inventory/BackgroundPreview.tsx
components/modal/store/inventory/ChangeIdColorModal.tsx
components/modal/store/inventory/ChangeProfileBackgroundModal.tsx
components/modal/store/inventory/ChangeProfileEdgeModal.tsx
components/modal/store/inventory/EdgePreview.tsx
components/modal/store/inventory/EditMegaphoneModal.tsx
components/modal/store/inventory/GachaModal.tsx
components/modal/store/inventory/NewMegaphoneModal.tsx
components/modal/store/inventory/ProfileImageModal.tsx
components/store/InventoryItem.tsx
components/store/InventoryList.tsx
components/store/purchase/ItemCard.tsx
styles/ProfileColor.scss
styles/modal/store/EdgePreview.module.scss
styles/modal/store/GachaModal.module.scss
types/colorModeTypes.ts
types/inventoryTypes.ts
types/modalTypes.ts

- 보관함 모달 제목 수정 및 엣지 미리보기 이름 추가
- 보관함 모달에서 itemName을 받아 제목에 반영했습니다.
- 확성기 모달은 itemName을 수정할 경우가 없을 것 같아서 건드리지 않았습니다.
- 엣지 뽑기 미리보기에도 색상 이름을 추가했습니다. EdgePreview 컴포넌트에서 edge를 바꿔가면서 테스트해보실 수 있습니다
- 보관함 모달에서 이미지가 널일 때 스톰트루퍼 대신 not_found이미지가 뜨도록 수정했습니다
-

[GGFE-259] 보관함 모달 제목 수정 및 엣지 미리보기 이름 추가

---

components/modal/store/UserCoinHistoryModal.tsx
components/store/InventoryList.tsx
components/store/StoreLoading.tsx
components/store/purchase/ItemsList.tsx
styles/modal/store/CoinHistoryDetails.module.scss
styles/modal/store/UserCoinHistoryModal.module.scss

- 상점페이지 로딩 처리
- 상점, 보관함 탭에서 로딩상태일 때 탁구채 이모지 띄우도록 했습니다.
- 상점 판매 아이템 api 요청 시 로딩처리를 간단히 하기 위해 useQuery 사용하는 것으로 수정했습니다
- 그 외에 코인 내역 모달에서 로딩 애니메이션 컨테이너 높이를 고정해서 높이가 왔다갔다하지 않도록 수정했습니다.
-

[GGFE-263] 상점 로딩 처리

---

components/modal/store/inventory/ProfileImageModal.tsx
styles/modal/store/InventoryModal.module.scss

- 프로필 이미지 수정 결과 반영에 시간이 걸린다는 안내 메시지를 추가했습니다.
- 메인 페이지에서 확인할 수 있는 게임 결과 데이터의 캐시 refresh 시간 간격이 30분이기 때문에 프로필 이미지 수정 결과가 전체 사이트에 반영되는데 30분 정도 걸릴 수 있다는 안내 메시지를 추가했습니다.
- 주의사항 리스트 스타일에 들여쓰기를 추가했습니다!
-

[GGFE-266] 프로필 이미지 수정 안내 메시지 추가

---

styles/mode/ModeWrap.module.scss

- `modeWrapBasic`의 내부 요소들 사이에 `gap` 속성을 사용해서 좌우 간격을 추가했습니다.
- 모바일 환경에서 game page 위의 검색바와 시즌 드롭다운 사이의 간격이 없이 딱 붙는 문제가 있어 수정했습니다.
- 크롬 개발자 도구에서는 위의 문제가 발생하지 않아서 정확한 적용 결과는 배포 후에 확인해봐야 할 것 같아요 🥲
-

[GGFE-264] modeWrapBasic 내부 요소들 사이에 좌우 간격 추가

---

components/modal/store/inventory/ChangeIdColorModal.tsx
components/modal/store/inventory/ColorPicker.tsx
components/rank/NormalListItem.tsx
components/rank/RankListItem.tsx
styles/modal/store/ColorPicker.module.scss
styles/modal/store/InventoryModal.module.scss

- 색상 프리뷰 클릭 시 색상 선택기 open close 방식으로 변경
- pc에서 모달 위아래 잘림 문제로 색상 선택기를 클릭 시 open close 방식으로 변경했습니다.
- 처음 사용하는 사람에게는 색상선택기를 열 수 있다는 걸 알려줘야하는데 어떻게 알려줘야할 지 모르겠습니다.
- ex) 주의사항 추가, 색상프리뷰 상단 색상선택 문구 옆에 클릭하라는 문구 추가 등 피드백 부탁드립니다
-

[GGFE-262] ID 색깔 변경 모달 - 색상 프리뷰 클릭 시 색상 선택기 open close 방식으로 변경

---

components/Layout/MegaPhone.tsx
package-lock.json
package.json
styles/Layout/MegaPhone.module.scss

- 확성기 컴포넌트에 가상 리스트 라이브러리(https://github.com/petyosi/react-virtuoso) 를 적용했습니다.
- 기존에 사용하려던 react-window 라이브러리는 애니메이션 적용에 시간이 많이 들 것 같아서 기능이 좀 더 많고 document가 잘 정리되어 있는 react-virtuoso로 적용했습니다.
- 기존에 애니메이션으로 처리되어 있던 기능을 라이브러리의 "부드러운(?) 스크롤"기능으로 대체했습니다.
---
- 기존 데이터 로드 방식으로는 확성기가 삭제되었을 때 새로고침해야만 변경된 데이터를 확인할 수 있어서 path가 바뀔 때 마다 새로 받아오도록 수정해봤습니다.
- 모든 확성기 데이터 끝에 adminContent를 추가해보았습니다.
---
- 모든 환경에서 잘 돌아간다는 확신이 없어서 일단은 기존 코드 주석을 유지한채로 main에 머지하겠습니다.. 🥲 배포 직전에 주석 정리하도록 하겠습니다!! ㅜㅜ 
-

[GGFE-265] 확성기 가상 리스트 적용

---

components/modal/store/StoreManualModal.tsx
styles/modal/store/StoreManualModal.module.scss

- 상점 매뉴얼 뽑기 확률표 링크 추가
- 상점 매뉴얼 상점이용 탭 마지막 부분에 뽑기 확률표 링크 추가했습니다
- tag 문자열 비교로 뽑기확률표인지 확인해서 링크를 걸도록 했습니다
- 현재 링크는 권한 제한이 되어있는데, 배포 직전에 정리해서 링크 교체하면 될 것 같습니다!
-

[GGFE-272] 상점 매뉴얼 뽑기 확률표 링크 추가

---

pages/tournament-record.tsx
styles/tournament-record/TournamentRecord.module.scss

- 유저 토너먼트 전적 페이지의 기본적인 레이아웃을 작업하였습니다.
- /tournament-record 페이지를 생성하였습니다.
- 리그 선택 버튼, 우승자 게임 정보, 브라켓 뷰 컨테이너 등을 스타일링하였습니다.

Feat/유저 토너먼트 전적 페이지 레이아웃 #1077

---

components/tournament-record/WinnerSwipeView.tsx
package-lock.json
package.json
pages/tournament-record.tsx
styles/tournament-record/WinnerSwipeView.module.scss

- Swiper 라이브러리를 사용하여 우승자 프로필 사진을 확인할 수 있는 슬라이드를 구현하였습니다.

Feat/유저 토너먼트 전적 페이지 우승자 스와이프 뷰 #1070

---

components/modal/ModalButton.tsx
components/modal/tournament/TournamentRegistryModal.tsx
components/tournament/TournamentCard.tsx
pages/tournament.tsx
styles/common.scss
styles/modal/event/TournamentRegistryModal.module.scss

- 현재 api가 아직 없어서 더미데이터를 이용해서 보여주도록 만들었기 때문에  msw등을 사용해 목데이터를 추가해서 추가적인 테스트할 필요가있습니다.
api로 부터 받아오는 정보로부터  현재 진행중인 토너먼트 확인 및 모달창을 통해 정보를 볼 수 있도록 만들었습니다.

[Feat] 토너먼트 페이지 api#1083

---

pages/api/pingpong/tournaments/index.ts

- 토너먼트 전체조회 mock API를 구현하였습니다.
- page, status, type, size 쿼리 파라미터에 따라 필터링한 결과를 반환하도록 하였습니다.

[Feat] 토너먼트 전체조회 API mock #1089

---

components/admin/tournament/TournamentEdit.tsx
components/admin/tournament/TournamentList.tsx
components/modal/admin/AdminEditTournamentBraket.tsx
constants/admin/table.ts
hooks/tournament/useTournamentEditInfo.ts
pages/admin/tournament.tsx
pages/api/pingpong/tournament/dummyTournamentData.ts
styles/admin/modal/AdminEditTournamentBraket.module.scss
styles/admin/tournament/Tournament.module.scss
styles/admin/tournament/TournamentEdit.module.scss
styles/admin/tournament/TournamentList.module.scss
types/admin/adminTournamentTypes.ts

- 관리자 토너먼트 페이지의 생성, 수정, 삭제 버튼의 기능을 추가하였습니다.
- 기존 기획에서 변경하여 토너먼트 내용 수정과 인원 수정 버튼을 분리하였습니다.
- 수정할 토너먼트를 클릭하고 상단 quill뷰에서 내용을 수정한뒤 수정 요청을 보냅니다.
-

Feat/관리자 토너먼트 페이지 생성수정삭제 버튼 #1112

---

pages/api/pingpong/admin/tournament/[tournamentId]/users/[userId].ts
pages/api/pingpong/admin/tournament/[tournamentId]/users/index.ts
types/admin/adminTournamentTypes.ts

- 관리자 토너먼트 유저 전체조회, 추가 및 삭제 mock API를 구현하였습니다.
- 관리자 토너먼트 유저 전체조회 mock API
- 관리자 토너먼트 유저 추가 mock API
- 관리자 토너먼트 유저 삭제 mock API
- 관리자 토너먼트 유저 타입 `ITournamentUser` 추가

Feat/관리자 토너먼트 유저 전체조회, 추가 및 삭제 mock api #1119

---

components/tournament/TournamentMatch.tsx
pages/tournament.tsx

- 모바일에서도 하이라이트가 잘 클릭될 수 있도록 만들었습니다.
- HighLightUser를 Recoil을 통해 관리하고있는데, 해당 사항을 Context 로 변경하니 계속해서 새로고침을 해서 브라켓 뷰의 zoom 이 초기화 되는 문제가 있어서 일단은 Recoil을 그대로 사용하고있습니다.
- 
-

[Fix] 모바일 환경에서 브라켓 뷰 하이라이트 안됨#1161

---

components/modal/tournament/TournamentRegistryModal.tsx
components/tournament/TournamentCard.tsx
pages/tournament.tsx
styles/tournament/TournamentCard.module.scss

-  토너먼트 Card의 Style 이 변경 되었습니다
-  인원수가 모두 꽉 찼을시 빨간색, 아닐 경우 파란색으로 현재 인원을 확인할 수 있습니다.
-  미 참여 / 대기 중 / 참여 중 3가지 상태로 현재 토너먼트에 대한 나의 상태를 확인할 수 있습니다
-  회색 / 주황색 / 초록색 3가지 색상을 사용하고있습니다.
-  더 좋은 단어 표현 추천 받습니다 ..
-
-

[Fix] 토너먼트 card style 수정#1159

---

components/modal/statChange/StatChangeModal.tsx
components/tournament/TournamentMatch.tsx

- 리팩토링을 위해 Fragment로 대체했던 div를 복원하였습니다.
- 토너먼트 브라켓에서 아직 유저가 확정되지 않은 경우 fallback 이미지를 추가하였습니다.

[Fix] 점수 입력 모달 클릭 안 됨 #1190

---

pages/tournament.tsx
styles/tournament/UserTournamentBracket.module.scss

- LIVE 상태인 토너먼트를 모두 표시하도록 수정하였습니다.

[Fix] LIVE 상태인 토너먼트 모두 표시 #1239

---

hooks/party/usePartyCategory.ts
utils/axios.ts

- 현재 axios의 admin url에 대한 환경변수가 'pingpong/admin'으로 되어있어 새로운 'party/admin'과 관련된 api를 사용할 수 없어 새로운 환경변수가 추가되었는데 이거에 대해 이야기를 해되야될 것 같습니다.
- PartyCategory데이터를 서버에서 가져와서 관리하는 hook
- 한번가져오면 react-query를 이용해 캐싱됩니다.
- hook이 가진 함수로 categoryAPI를 사용해야만 데이터가 refresh됩니다.
- 로딩 및 에러에는 빈 리스트([]) 반환
- API오류가 나면 간단히 토스트를 띄움
-

[Feat] party category api사용 hook 구현

---

components/Layout/Header.tsx
components/admin/party/PartyCategory.tsx
components/modal/Party/PartyRoomEditModal.tsx
components/modal/admin/AdminTemplateModal.tsx
components/modal/modalType/AdminModal.tsx
components/modal/modalType/PartyModal.tsx
components/party/PartyMain.tsx
components/party/roomDetail/PartyDetailButton.tsx
components/party/roomDetail/PartyDetailProfile.tsx
hooks/party/usePartyCategory.ts
hooks/party/usePartyPenaltyTimer.ts
hooks/party/usePartyTemplate.ts
pages/party/index.tsx
styles/party/PartyDetailRoom.module.scss
styles/party/PartyMain.module.scss
utils/handleTime.ts

- 파티 패널티 적용
- 패널티 적용시 방 생성 불가
- 태널티 적용시 방 참여 불가
-

Feat/파티 패널티시 방 참여 및 생성 제한 #1341

---

components/modal/recruitment/CancelModal.tsx
components/tournament/TournamentMegaphone.tsx
hooks/recruit/useCheckRecruit.ts
hooks/recruit/useGetRecruitResult.ts
hooks/recruit/useInfiniteRecruitList.ts
hooks/recruit/useRecruitDetail.ts
hooks/recruit/useRecruitDetailUser.ts
hooks/recruit/useUserApplicationForm.ts

- #1326 
- 모집 유저 기능에서 사용하고 있던 mock api를 제거했습니다.
- `useCheckRecruit` 훅 오류 수정
- 모집 유저 기능의 `mockInstance`를 제거했습니다 (관리자는 그대로 놔뒀어요!)
- 저번 기수 작업이었던 `TournamentMegaphone`에 `mockInstance`를 사용하고 있던 부분이 남아있어서 수정했습니다. 바꾸면 안되는 부분인지 확인 필요합니다 @greatSweetMango 
- 모집 중인 공고가 있는지 확인하는 `useCheckRecruit` 훅에서 query string을 빼고 요청해서 발생하던 500 에러를 수정했습니다.
-

[Fix] 모집 유저 기능의 mock api 제거

---

components/admin/recruitments/RecruitmentsHistoryList.tsx
components/admin/recruitments/recruitmentsDetail/RecruitmentDetail.tsx
components/admin/recruitments/recruitmentsEdit/components/ActionSelectorButtons.tsx
components/admin/recruitments/recruitmentsuser/DetailRecruitUserList.tsx
components/admin/recruitments/recruitmentsuser/FilterOptions.tsx
components/admin/recruitments/recruitmentsuser/NotificationResults.tsx
components/admin/recruitments/recruitmentsuser/RecruitSearchBar.tsx
hooks/recruitments/useRecruitmentEditInfo.ts
hooks/recruitments/useRecruitmentUserFilter.ts
types/admin/adminRecruitmentsTypes.ts

- recruit admin api 테스트 중 발견된 에러를 수정했습니다. 
> 임의로 수정한 부분이나 보완해야 할 부분 **_FIXME_** 주석으로 남겨두었으니 확인후 수정 부탁드립니다. @parksangmin1543 @greatSweetMango 
- axios instance 변경
instanceInManage -> instance (url에서 pingpong이 제거됨)
- 데이터 프로퍼티명 변경 => 프로퍼티명 논의할 시간이 없어서 일단 구현된 api 명세에 맞췄습니다.
- recruitments -> recruitmentDtoList
- applications -> applicationResults
- 훅 이름 변경
useRucruitmentUserFilter -> useRecruitmentUserFilter
- recruitId 필수로 변경 (undefined일 경우에는 요청 자체가 불가능함)
- 페이지네이션 기능 주석처리 (api는 없는 쪽으로 구현되어 있으므로 다시 논의 필요합니다)
- recruitId 필수로 변경 (undefined일 경우에는 요청 자체가 불가능함)
- applicationResults undefined에러 처리 추가
-

[Fix] recruit admin api 연결 중 발생한 에러 수정 (조회 api 위주)

---

components/recruit/Application/applicationFormItems/MultiCheckForm.tsx
components/recruit/Application/applicationFormItems/SingleCheckForm.tsx
types/recruit/recruitments.d.ts

- #1371 
- 지원서 보기/수정 페이지에서 인터페이스 속성이 맞지 않아 제출한 지원서 내용이 보이지 않던 문제 수정했습니다.
- 내 응답의 checkedList는 체크박스 id만 들어오던 방식에서 => 체크박스 id + 해당 항목 내용이 같이 들어오는 것으로 수정됐습니다.
- 내가 제출한 지원서 상세보기 api에서
- check박스 응답은 answer를 null로
- text 응답은 checkedList를 [] 빈 배열로 응답
- 따라서 기존의 속성의 옵션 설정 없앴습니다.
-

[Fix] 지원서 보기/수정 페이지 api 응답 형식에 맞게 수정

---

components/Layout.tsx
next.config.js

- 프론트엔트 테스트 시 로그인 토큰이 계속 필요한데요, 로그인하지 않고 테스트할 경우가 있습니다.
- 로그인하지 않고 테스트할 수 있게... 리턴했습니다.
- 
- config : process.env.NODE_ENV를 받아오며, npm run dev로 돌릴 때 'development'로 세팅됩니다.
- Layout.tsx : 이를 이용하여 appLayout이 빌드시와 데브서버 시 각각 다른 컴포넌트를 리턴하게 만들었습니다.. 
현재는 useUser, useSeason등 api 콜 하고 setError하는 부분을 전부 주석처리한 코드를 리턴하는데, 
이후 개발하면서는 useUser는 사용하게 될 것 같습니다.
최종적으로는 takgu 레이아웃을 분리해 이 안에서만 useSeason 등 사용하게 하는 게 좋겠지만, 우선은 테스트 목적으로 작성했습니다.
이게 맞는지는 잘 모르겠기 때문에 혹시라도 보시고 이건아니지 싶으시면 조언 부탁드립니다.

[Feat] 프론트엔드 테스트 시 로그인 조회하지 않도록 변경 #1455

---

components/agenda/modal/AgendaModalProvider.tsx
components/agenda/modal/ModifyModal.tsx
components/agenda/modal/NoticeModal.tsx
components/agenda/modal/ProceedCheckModal.tsx
components/agenda/modal/useModal.tsx
types/agenda/modalTypes.ts

- 수정 modal 추가 및 클릭 이벤트 에러 처리
1. 수정 기본 모달 추가
- 기존 title, description, onCancel, onProceed 가 동작하는 모달에 필요한 form 컴포넌트를 넣어 사용할 수 있도록 변경
- 폼 제출은 onProceed로 전달하는 함수에서 정의되어야 함
```jsx
const ModifyModal = (
props: agendaModal & {
FormComponent: React.ComponentType<{
data: any;
}>;
}
) => {
...
return (
<>
...
<div className={styles.formContainer}>
<FormComponent data={data} />
</div>
...
</>
);
};
```
2. 클릭 이벤트 에러 해결
- 모달 어디든 클릭 이벤트가 발생한 경우 모달이 닫히는 오류
- modalOutside를 지정하고 이벤트가 발생했을 경우, modalOutside일 경우에만 모달 close
- onCancel, onProceed와 modalClose를 모두 포함한 handleCancel, handleProceed을 정의
- 버튼 클릭 -> 지정된 함수를 실행한 후 모달을 닫을 수 있도록 함
- handleCancel, handleProceed 함수 내에서 onCancel, onProceed와 modalClose 호출
- #1481

[Feat] 수정 modal 추가 및 클릭 이벤트 에러 처리 #1481

---

components/LoginChecker.tsx
components/agenda/Form/AgendaForm.tsx
components/agenda/Home/AgendaInfo.tsx
components/agenda/Home/AgendaList.tsx
components/agenda/Home/MyAgendaBtn.tsx
components/agenda/Home/MyTeamInfo.tsx
components/agenda/utils/PageController.tsx
pages/agenda/index.tsx
pages/index.tsx
styles/agenda/Home/AgendaList.module.scss
styles/agenda/utils/PageController.module.scss
styles/index.module.scss
styles/takgu/Layout/Layout.module.scss

- 주요 에러 중 ui 처리, 본인 작업 부분
웹뷰 오른쪽 왼쪽에서 왼쪽 누

[Bug] 뷰/ui 관련 에러 처리#1519

---

components/takgu/modal/event/WelcomeModal.tsx

- 리액트 쿼리의 'user' 키에 대한 정보가 저장되어 있어서 보상을 수령했는지 업데이트가 안되고있는 상황이였습니다.
- 보상받기를 눌렀을 때 'user' 키에 대한 캐시를 초기화시켜서 새롭게 받아올 수 있도록 만들었습니다.
- **테스트를 실제로 해보기 어려운 상황이여서 토이프로젝트를 만들어서 동작을 확인하고 올립니다. 테스트를 해주시면 감사합니다.. 모든 user key 를 가지고있는 데이터가 다시 패칭되기 때문에 문제가 있을 수도 있다고 생각합니다 ...** 
- 캐시를 무효화하는 로직을 버튼을 클릭시 무효화 할 수 있도록 옮겼습니다.
-

[Bug] 로그인 보상을 수령해도 계속 화면이 뜨는 이슈 #1525

---

components/agenda/teamDetail/TeamButtons.tsx
hooks/useAxiosWithToast.ts
pages/agenda/[agendaKey]/[teamUID]/index.tsx
utils/agenda/getAgendaSnackBarInfo.ts

- 팀 상세 페이지 토스트 에러
- 개인이 팀에서 나갈 시,  API 변경 + 토스트 메시지 변경 
- 팀 상세 페이지에서 팀장일 때, 폭파하기를 하면 -> API: team/cancel -> 토스트 메시지: 팀을 폭파했습니다.
- 팀 상세 페이지에서 팀원일 때, 나가기를 하면 -> API: team/drop -> 토스트 메시지: 팀에서 나갔습니다. 
- 링크 복사 alert 메시지 변경 :  alert('링크가 복사되었습니다.');
- 토스트 메시지 살짝 변경 사항
- admin 페이지에서 나오는 토스트 메시지 '성공했습니다'로 변경
- 팀 확정 메시지 변경 :  `message: '팀이 성공적으로 확정되었습니다.`

[Bug] 팀 상세 페이지 토스트 에러 #1522

---

components/LoginChecker.tsx
components/agenda/Form/CreateTeamForm.tsx
components/agenda/Form/SubmitAgendaForm.tsx
components/agenda/Home/AgendaList.tsx
components/agenda/Home/MyTeamInfo.tsx
components/agenda/Layout/MenuBar.tsx
components/agenda/agendaDetail/AgendaInfo.tsx
components/agenda/agendaDetail/tabs/AgendaAnnouncements.tsx
components/agenda/agendaDetail/tabs/ParticipantTeam.tsx
components/agenda/agendaDetail/tabs/ParticipantTeamList.tsx
components/agenda/agendaDetail/tabs/ParticipantsList.tsx
components/agenda/teamDetail/TeamInfo.tsx
components/agenda/utils/AgendaLoading.tsx
components/agenda/utils/PageController.tsx
hooks/agenda/useAgendaInfo.ts
hooks/agenda/useAgendaKey.ts
hooks/agenda/useAgendaTeamKey.ts
hooks/agenda/useFetchGet.ts
hooks/agenda/usePageNation.ts
pages/agenda/detail/host/createAnnouncement.tsx
pages/agenda/detail/host/index.tsx
pages/agenda/detail/host/result.tsx
pages/agenda/detail/index.tsx
pages/agenda/detail/team/create.tsx
pages/agenda/detail/team/index.tsx
pages/agenda/profile/index.tsx
pages/agenda/profile/user.tsx
stories/agenda/Form/CreateTeam.stories.tsx
stories/agenda/Form/SubmitAgendaResult.stories.tsx
styles/agenda/utils/AgendaLoading.module.scss

- 동적 라우팅 버그로 인해 쿼리 사용
- 기존에 동적 라우팅으로 인해 새로고침을 할 시, 에러가 발생하여 index페이지로 이동하는 버그가 생겼습니다. 
- 동적 라우팅을 사용하지 않고, 페이지 라우팅 + 쿼리문을 사용하여 문제를 해결했습니다. 
---
1. 동적 라우팅 페이지를 페이지 라우팅으로 변경
2. router.push / Link href 등의 페이지 이동 안에 쿼리문 넣는 작업
3. 특정 페이지에서 쿼리의 데이터를 참고(router.query.agenda_key)하여 해당 페이지의 데이터 및 UI를 띄우기
4. useAgendaKey() / useAgendaTeamKey() Hooks 만들기 : 렌더링 모두 되었을 시, agenda_key와 team_key를 가져오기
5. 아젠다 로딩 페이지 생성 및 완전히 데이터 나오지 처리 되지 않았을 시 나오게 설정 (후에 UI 개선)
6. 기존의 hooks에 예외 처리 추가 : agenda_key가 undefined로 들어 갈 시 등의 로직 추가
7. 쿼리문 데이터 받아오기 + 기존의 hooks 사용 잘되는지 테스트 및 여러 에러들 수정
---
- **특이 사항 발생**
- 쿼리 데이터 받기(ex: router.query.agend_key) 문제가 발생했습니다.-> error: queryFn
- 가끔씩 완전히 렌더링이 안된 상태에서 데이터를 받는 경우가 있어 쿼리 데이터를 undefined로 가져 오는 오류가 생겼습니다. 
- 따라서 완전히 렌더링 후 router.isReady -> 렌더링 다 되었을 시, 가져오는 방법으로 수정했습니다.
- **쿼리 …

[Bug] router bug #1538

---

components/agenda/Form/AdminTeamForm.tsx
components/agenda/Profile/CurrentList.tsx
components/agenda/agendaDetail/tabs/AgendaDescription.tsx
components/agenda/agendaDetail/tabs/Participant.tsx
components/error/AgendaError.tsx
hooks/agenda/usePageNation.ts
pages/agenda/profile/user.tsx
pages/agenda/ticket/history.tsx
styles/agenda/Home/AgendaInfo.module.scss
styles/agenda/Home/AgendaList.module.scss
styles/agenda/Layout/Layout.module.scss
styles/agenda/Profile/AgendaProfile.module.scss
styles/agenda/Profile/CurrentList.module.scss
styles/agenda/Profile/HistoryList.module.scss
styles/agenda/Profile/ProfileCard.module.scss
styles/agenda/agendaDetail/AgendaDetail.module.scss
styles/agenda/agendaDetail/tabs/AgendaDescription.module.scss
styles/agenda/utils/AgendaTag.module.scss

- 프로필 update 오류, 팀 수정 기능 추가, css 정리 
1. 팀 수정 폼 변경
- 팀 취소는 팀 목록 테이블에서만 가능하도록 변경
- 팀 취소상태에서 OPEN/CONFIRM 상태로 변경시, 팀장이름 자동으로 추가
2. css 정리 
3. 프로필 update 오류
- search를 통해 url이 변경되었지만 페이지 새로고침이 되지 않았을 경우 데이터를 제대로 불러오지 않음
1) 참여중/참여 기록 변경되지 않음
- 문제
- pageNation을 사용하여 불러오는 LIst들이 불러오지 않음
- 해결
- usePageNation에서 url과 isReady에 따른 useEffect 추가
2) agenda에 등록되지 않은 사용자일 경우 content를 불러오지 않음
- 문제 
- agendaProfileData가 초기화되지 않음
- 해결
- axios.get을 통해 받아온 data와 component에 보내는 data를 분리하여 저장 
- isAgendaId가 false일 경우 agendaProfileData 초기화

[Fix] 프로필 update 오류, 팀 수정 폼 변경, css 정리 #1551

---

hooks/agenda/useFetchGet.ts
hooks/useAxiosAgendaError.ts
pages/agenda/profile/user.tsx

[Fix] accessToken api 호출 url 변경 #1551 

---

.github/workflows/main-build-test.yml
.github/workflows/main-deploy.yml
.github/workflows/test-deploy.yml

- github Actions Deprecation 해결 및 버전 업그레이드
- 버전 업그레이드를 하지 않아 github Actions가 작동되지 않는 버그가 발생했습니다.
- .github/workflows/.yml 파일들 안에 `runs-on: macos-12 ` 를 `runs-on: macos-13` 으로 변경했습니다. 
- #1586

[Bug] github Actions Deprecation 버그 해결

---

.github/workflows/main-deploy.yml
.github/workflows/test-deploy.yml

- github Actions Deprecation 해결 및 버전 업그레이드
- main, test-deploy, deploy 브랜치에 대한 github Actions 설정들이 정상 작동하지 않는 문제가 발생했습니다.  
- Error ❌
- `The macOS-12 environment is deprecated, consider switching to macOS-13, macOS-14 (macos-latest) or macOS-15.`
- Warning ⚠️ 
- `The set-***put command is deprecated and will be disabled soon. Please upgrade to using Environment Files.`
- github Actions 설정 파일 안의 설정된 코드들을 업그레이드 해주었습니다. 위치 -> `.github/workflows/.yml` 
- Error ❌
- `runs-on: macos-12 ` -> `runs-on: macos-13`
- Warning ⚠️
- `actions/checkout@v2` ->  `actions/checkout@v3`
- `actions/setup-node@v1` -> `actions/setup-node@v3`
- `aws-actions/configure-aws-credentials@v1` -> `aws-actions/configure-aws-credentials@v3`
- #1586

Fix: github Ations 설정 업그레이드

---

utils/axios.ts

- Axios 공용 인터셉터 추출
- Axios 공용 인터셉터를 추출했습니다.
- axios의 인터셉터들의 콜백 함수들 선언해서 분리했습니다. 
**변경전**
```ts
instance.interceptors.request.use(
function setConfig(config) {
config.headers = {
'Content-Type': 'application/json',
Authorization: `Bearer ${localStorage.getItem('42gg-token')}`,
};
config.withCredentials = true;
return config;
},
function getError(error) {
return Promise.reject(error);
}
)
```
**변경후**
```ts
instance.interceptors.request.use(setConfig, getError);
instanceInManage.interceptors.request.use(setConfig, getError);
instanceInPartyManage.interceptors.request.use(setConfig, getError);
// 추출된 callback함수들
function setConfig<T>(config: AxiosRequestConfig<T>) {
return {
...config,
headers: {
...config.headers,
'Content-Type': 'application/json',
Authorization: `Bearer …
```

[Refactor] Axios 공용 인터셉터 추출

---

components/takgu/Layout/MegaPhone.tsx
styles/takgu/Layout/MegaPhone.module.scss

- 확성기 스크롤 위치 오류 수정
- 확성기 스크롤 위치가 맞지 않고 빈 메시지가 들어가는 문제를 수정했습니다.
- 문제 원인으로 추정되는 것은 유저가 임의로 스크롤하지 못하도록 추가했던 `overflow-y: hidden !important`
- 스크롤은 정상적으로 동작하도록 하기 위해서 라이브러리 설정 그대로 `overflow-y: auto` 가 적용되도록 하고
- 유저가 스크롤을 시도할 때 발생하는 wheel, touchmove 이벤트에서 스크롤 동작이 발생하지 않도록 설정했습니다.
- https://virtuoso.dev/custom-scroll-container
- https://virtuoso.dev/customize-structure
- https://developer.mozilla.org/ko/docs/Web/API/EventTarget/addEventListener#passive
- close #1582

[Fix] 확성기 스크롤 오류 수정

---

components/agenda/Form/SubmitAgendaForm.tsx
components/takgu/modal/admin/AdminEditItem.tsx
components/takgu/modal/admin/AdminProfileModal.tsx
components/takgu/modal/store/inventory/ProfileImageModal.tsx
constants/common/mimeType.ts
hooks/useUploadImg.ts

- #1583 에서 이미지 로드가 실패하는 원인을 파악해본 결과 이미지들이 과거에 썼던 버킷주소에서 이미지를 받아오고 있어서 그런것으로 확인했습니다.
- 이를 해결하기 위해서 이미지를 다시 업로드를 시도해보았고, 업로드 과정에서 에러가 발생하고 있는 것을 확인했습니다.
- 에러 원인은 https://github.com/42organization/42gg.client/commit/792a0bb4db1995ff00f28dcea556e99507ba2247 에서 image 경로를 `image/takgu`로 고치는 과정에서 mime 타입까지 수정된 것으로 보입니다.
- 잘못된 mime type을 수정했습니다
- 'application/json' 과 'image/jpg', 'image/jpeg'를 인라인스트링으로 관리하던 부분을 상수로 추출했습니다.
- inline에선 mime타입을 기재하던 부분들을 드러내고, MIME_TYPE을 공용상수로 뺴냈습니다.
```ts
// 변경전
{type: 'image/jepg'}
{type: 'application/json'}
// 변경후
{type: MIME_TYPE.JPEG}
{type: MIME_TYPE.JSON}
```
- fix #1583

[Fix] MIME type 상수화

---

components/calendar/CalendarLayout.tsx
components/calendar/CustomCalendar.tsx
components/calendar/sidebar/CalendarSidebar.tsx
pages/calendar/index.tsx
styles/calendar/Calendar.module.scss
styles/calendar/modal/AddSelect.module.scss

- snackbar 오류 수정
- 캘린더 스크롤 문제 수정
- 개인일정 모달 및 그룹 관련해서, 성공 시에도 error snackbar(ex. 그룹 수정에 실패했습니다)가 뜨던 오류 수정
- 캘린더 스크롤 시 ui 이상해진 것 수정
-
close #1606

Fix: 성공 시에도 snackbar 뜨는 것 수정 및 캘린더 스크롤 수정
