- components/RankList.tsx
- 랭크 리스트 만들기
- 랭크 컴포넌트를 활용하여 리스트 작성해보기!
> [Feat] 랭크 리스트 만들기 #3

- components/Header.tsx
- components/NotiItem.tsx
- components/Notibar.tsx
- pages/api/pingpong/notifications/index.ts
- pages/api/pingpong/users/index.ts
- pages/index.tsx
- styles/NotiItem.module.scss
- styles/Notibar.module.scss
- styles/globals.css
- types/mainType.ts
- types/notiTypes.ts
- utils/atom.ts
- Notibar Nextjs API 연결 및 알림타입 수정
- 헤더 알림카운트, 유저 이미지 적용
- 알림바
- api 알림 생성: pingpong/notification
- Notibar Nextjs API 연결
- 백엔드와 상의 후 알림 타입 수정
- 읽은 알림(isChecked)이면 배경색 어둡게 보임
- 메인페이지 및 헤더
- api 메인 유저 생성: pingpong/users
- 메인페이지와 Nextjs API 연결
- 헤더 컴포넌트에 recoil로 알림 카운트, 유저 이미지 적용
> [Feat] 알림바 Nextjs API 연결 및 헤더 알림아이콘 이미지 적용 #15

- components/MenuBar.tsx
- components/NotiBar.tsx
- 대소문자 오류로 MenuBar, NotiBar 파일을 삭제 후 재생성
- 파일이름 대소문자 문제로 관련 파일을 삭제하고, 다시 올립니다.
- `git config core.ignorecase false` : 대소문자를 무시하지 말라는 설정
- 이후 캐시된 파일을 지워주어야 하는데 그 과정이 없어 강제로 관련 파일을 삭제하고 다시 올립니다.
> [Refactor] 대소문자 오류 파일 재생성 #21

- components/rank/MyRank.tsx
- components/rank/RankItem.tsx
- components/rank/RankList.tsx
- pages/api/pingpong/ranks/[type].ts
- pages/rank.tsx
- styles/RankList.module.css
- types/rankTypes.ts
- API 적용 위치 수정
- myRank 및 rankList 분할
- myRank는 메인페이지에서 정보 받아오기
- 랭크페이지에서 받아오던 정보는 랭크리스트에서 받아오기!
> [Feat] 랭크 API 위치 변경 #3

- components/score/InputScoreModal.tsx
- pages/api/pingpong/games/[gameId]/result.ts
- pages/score.tsx
- styles/InputScoreModal.module.scss
- types/scoreTypes.ts
> [Feat] 스코어 입력 페이지 구현

- components/score/InputScoreModal.tsx
- styles/InputScoreModal.module.scss
> [Feat] 점수 입력란 숫자만 받도록 구현 Close #34

- components/user/Chart.tsx
- components/user/EditProfile.tsx
- components/user/Profile.tsx
- pages/api/pingpong/users/[userId]/detail.ts
- pages/match.tsx
- pages/users/[userId].tsx
- types/userTypes.ts
- utils/recoil/user.ts
- user page 생성
- Profile component
- EditProfile component (모달로 띄울 예정)
- user page 생성 (/users/[userId]), Profile 컴포넌트와 EditProfile 컴포넌트 생성 및 구성
- Next API 로 profile API Get, Post(edit) 모두 작성 
- Next API 에 연결하여 프로필 보기, 프로필 수정 기능 구현
> [Feat] 유저페이지의 프로필 컴포넌트 구성

- components/score/InputScoreModal.tsx
- pages/api/pingpong/games/[gameId]/result.ts
- styles/InputScoreModal.module.scss
- types/scoreTypes.ts
- utils/axios.ts
- post axios 응답 status로 판별하도록 수정
- 결과 확인창 추가 및 api 응답별 조건 추가
> [Feat] 결과 확인창 추가 및 api 응답별 조건 추가

- utils/axios.ts
- 서버 api 연결
- nextjs api 사용시 주석 해제하시고 하면 됩니다
> [Feat] 서버 api 연결

- components/Layout/NotiBar.tsx
- components/Layout/NotiItem.tsx
> [Feat] 알림에서 상대 클릭시 상대 유저 페이지로 이동 #1

- components/main/SearchBar.tsx
- 검색결과클릭시 유저페이지로 이동 및 검색어 전체 초기화 버튼 추가 
- 검색결과클릭시 Link로 해당 유저페이지 이동 구현
- useRef를 사용해 검색컴포넌트 바깥 클릭시 검색결과모달 닫기 구현
- X 클릭시 검색어 초기화 기능 추가
> [Feat] 검색결과클릭시 유저페이지로 이동 및 검색어 전체 초기화 버튼 추가 #21

- components/main/Section.tsx
- pages/index.tsx
- 메인에서 경기결과 랭크 컴포넌트 부르기
- 메인에서 랭크 -> 경기결과 순으로 section 순서 수정
- Section에서 path에 따라  GameResultPath, RankList 불러오는 함수 추가
> [Feat] 메인에서 경기결과 랭크 컴포넌트 부르기 #21

- components/Pagination.tsx
- components/rank/RankItem.tsx
- components/rank/RankList.tsx
- 랭크페이지에서 클릭 시 프로필로 이동
- RankList에서 !제거
> [Feat] 랭크-프로필이동 #3

- components/score/InputScoreModal.tsx
- pages/api/pingpong/games/result.ts
- types/scoreTypes.ts
-스코어 입력 후 응답에 따른 메시지 추가 및 api 수정
- alert 추가
- 스코어 입력값 제한
- api 폴더 변경
> [Feat] 스코어 입력 후 응답에 따른 메시지 추가 및 api 수정 Close #43

- components/Layout/Layout.tsx
- pages/login.tsx
- utils/axios.ts
- 레이아웃 페이지 리팩토링
- useEffect 합치기
- useEffect 내부 함수화 
- env 파일 변경 (슬랙에 올렸습니다)
> [Refactor] 레이아웃 리팩토링

- components/Layout/Layout.tsx
- components/main/SearchBar.tsx
- components/score/InputScoreModal.tsx
- pages/api/pingpong/users/live.ts
- pages/api/pingpong/users/searches.ts
- types/mainType.ts
- utils/recoil/main.ts
- 레이아웃, 서치 서버 api 수정사항 반영
- 라이브 데이터, 검색 데이터 api 수정
- 라이브 데이터 gameId 삭제 -> event 값으로 대체
> [Fix] 레이아웃, 서치 서버 api 수정사항 반영 #52

- components/user/EditProfile.tsx
- pages/api/pingpong/users/detail.ts
- EditProfile API 수정사항 반영
- api url 변경
- axios body 에서 imageurl 삭제
> [Fix] EditProfile API 수정사항 반영

- components/match/CurrentMatchInfo.tsx
- components/match/MatchBoardList.tsx
- components/match/MatchEnrollModal.tsx
- components/user/EditProfile.tsx
- pages/api/pingpong/match/tables/[tableId]/[type].ts
- pages/api/pingpong/match/tables/[tableId]/slots/[slotId].ts
- pages/api/pingpong/users/[userId]/detail.ts
- pages/api/pingpong/users/detail.ts
- Match API 변경사항 반영
- Match
- EditProfile
- 이전 pr 에서 유저 정보 업데이트 API (PUT /pingpong/users/detail) 수정하면서 아예 파일을 옮겨버림
- 유저 정보 API (GET /pingpong/users/{userId}/detail) 작동하지 않는 문제 발생
- 페이지 복구하고 분리해서 해결
> [Fix] Match API 변경사항 반영

- components/Layout/Footer.tsx
- components/Layout/Header.tsx
- components/Layout/Layout.tsx
- styles/Footer.module.scss
- styles/Header.module.scss
- styles/Layout.module.scss
- styles/SearchBar.module.scss
- styles/common.scss
- styles/globals.css
> [Feat] 헤더 및 푸터 scss 추가 #63

- components/Layout/Layout.tsx
- styles/Layout.module.scss
> [Fix] 배경 밀림 문제 해결 #63

- components/game/GameResult.tsx
- 메인페이지 토큰 에러 처리
- GameResult 컴포넌트에 토큰이 들어오는 문제 발생
- 토큰 컨트롤로 분기 처리
-
> [Fix] 메인페이지 토큰 에러 처리

- components/rank/RankItem.tsx
- pages/api/pingpong/ranks/count/3.ts
- styles/RankList.module.scss
> [Feat] main ranking 디자인 수정 #63

- styles/main/SearchBar.module.scss
- styles/main/Section.module.scss
> [Style] 검색창 position 수정 #63

- components/Pagination.tsx
- components/rank/RankList.tsx
- styles/Pagination.module.scss
- styles/common.scss
- styles/globals.css
- 페이지네이션 디자인 적용
- 디자인 수정 중 현재페이지 관련 이슈 발생
- 현재 페이지 디자인 적용 문제 관련 추가 작업 필요
> [Style] 페이지네이션 디자인 수정 #63

- components/modal/InputScore.tsx
- components/modal/MatchEnrollModal.tsx
- components/modal/Modal.tsx
- tsconfig.json
- baseUrl 추가 및 상대경로를 절대경로로 변경
- 앞으로 작업하시는 파일들 절대경로로 모두 수정해주세요~!
> [Feat] baseUrl 추가 및 상대경로를 절대경로로 변경 Close#88

- components/Layout/Header.tsx
- components/Layout/Layout.tsx
- components/Layout/MenuBar.tsx
- components/Layout/NotiBar.tsx
- components/Layout/NotiItem.tsx
- styles/Layout/Header.module.scss
- styles/Layout/Layout.module.scss
- styles/Layout/Menubar.module.scss
- styles/Layout/NotiItem.module.scss
- styles/Layout/Notibar.module.scss
- styles/Menubar.module.scss
- styles/NotiItem.module.scss
- styles/Notibar.module.scss
- 메뉴바 알림바 스타일 수정 및 닫기 버튼 추가
- 메뉴바 알림바 닫기 버튼 추가
- 메뉴바 알림바 스타일 수정
- 레이아웃 관련 scss 파일 위치 styles/Layout으로 이동
> [Fix] 메뉴바 알림바 스타일 수정 및 닫기 버튼 추가 #63

- components/Layout/Layout.tsx
- pages/login.tsx
- 새로고침 시 로그인페이지 깜빡임 수정
- isLoading 추가하여 로그인페이지 깜빡임 제거
- Layout 파일 절대경로 수정
> [Feat] 새로고침 시 로그인 페이지 깜빡임 수정 #80

- components/Layout/Layout.tsx
- pages/login.tsx
- merge 이전으로 코드 복구 : 잘못된 setIsLoading위치로 인한 에러 발생으로 코드 복구
> Revert "[Feat] 새로고침 시 로그인 페이지 깜빡임 수정 #80"

- components/Layout/Footer.tsx
- components/Layout/Header.tsx
- components/Layout/Layout.tsx
- components/Layout/MenuBar.tsx
- components/Layout/NotiBar.tsx
- components/Layout/NotiItem.tsx
- components/main/SearchBar.tsx
- components/main/Section.tsx
- pages/_app.tsx
- pages/index.tsx
- 레이아웃, 메인 관련 파일 import 절대 경로로 수정
- components/ Layout, Main 관련 파일 절대경로로 수정
- pages/ index/ _app 파일 절대경로로 수정
> [Style] 레이아웃, 메인 관련 파일 import 절대 경로로 수정 #88

- components/Layout/Layout.tsx
- components/modal/CancelModal.tsx
- utils/recoil/match.ts
-매칭 취소시 CurrentMatchInfo 닫기 기능 구현
> [feat] 매칭 취소시 CurrentMatchInfo 닫기 기능

- components/Layout/MenuBar.tsx
- components/modal/CancelModal.tsx
- components/modal/LogoutModal.tsx
- styles/Layout/Header.module.scss
- styles/Layout/Layout.module.scss
- styles/Layout/Menubar.module.scss
- styles/Layout/Notibar.module.scss
- styles/common.scss
- styles/modal/LogoutModal.module.scss
- styles/modal/MatchEnroll.module.scss
- styles/modal/Modal.module.scss
- utils/recoil/login.ts
> [Feat] 로그아웃 모달 구현 #102

- components/Pagination.tsx
- components/rank/MyRank.tsx
- components/rank/RankList.tsx
- pages/login.tsx
- pages/rank.tsx
- styles/RankList.module.scss
- 랭크페이지 스타일 수정
- rankTitle, myRank 위치 변경 및  myRank 스타일 변경
- import 절대경로 변경
> [Style] 랭크페이지 스타일 수정 #63

- components/game/GameResult.tsx
- components/game/GameResultItem.tsx
- components/game/GameResultList.tsx
- components/game/big/GameResultBigScore.tsx
- components/game/big/GameResultBigTeam.tsx
- components/game/small/GameResultSmallScore.tsx
- components/game/small/GameResultSmallTeam.tsx
- components/load/Loading.tsx
- pages/game.tsx
- pages/load.tsx
- styles/GameResultItem.module.scss
- styles/load/Loading.module.scss
- 로딩 애니메이션 페이지, 컴포넌트 구현
- 상대경로 절대경로 수정
- 로딩 애니메이션 code pen 의 코드를 가져와서 적용 code by :  https://codepen.io/bratzie/pen/dOgXBq#anon-signup
- 상대경로 절대경로로 수정
> [Feat] 로딩 애니메이션 구현 및 상대경로 절대경로 변경

- components/game/GameResultItem.tsx
- components/game/GameResultList.tsx
- components/game/big/GameResultBigTeam.tsx
- components/game/small/GameResultSmallTeam.tsx
- components/rank/RankItem.tsx
- components/rank/RankList.tsx
- styles/GameResultItem.module.scss
- styles/RankList.module.scss
- styles/common.scss
> [Style] scss 정리 #63

- components/Layout/CurrentMatchInfo.tsx
- components/Layout/Header.tsx
- styles/Layout/CurrentMatchInfo.module.scss
- styles/Layout/Header.module.scss
- styles/Layout/Menubar.module.scss
- styles/Layout/Notibar.module.scss
- styles/RankList.module.scss
- styles/common.scss
- 헤더 유저 이미지 클릭시 유저 페이지 이동 기능 추가
- 헤더 유저 이미지 클릭시 유저 페이지 이동 기능 추가
- 그 외
- 현재 매치 정보 클릭 가능한 상대팀 css 수정
- 레이아웃, 메인 관련 컴포넌트에 클릭 가능한 태그에 커서 추가
> [Feat] 헤더 유저 이미지 클릭시 유저 페이지 이동 기능 추가 #111

- components/modal/EditProfileModal.tsx
- components/user/Chart.tsx
- pages/api/pingpong/match/tables/[tableId]/[type].ts
- pages/match.tsx
- pages/users/[userId].tsx
- styles/game/GameResultItem.module.scss
- styles/match/match.module.scss
- styles/user/Chart.module.scss
- styles/user/Profile.module.scss
> [feat] user page styling

- styles/RankList.module.scss
- styles/common.scss
- styles/game/GameResultItem.module.scss
- 모든 페이지 pageTitle 통일시키기
- 각 페이지에서 margin-bottom을 따로 처리 하는 걸 합쳤습니다
> [Style] 모든 페이지 pageTitle 통일시키기

- components/rank/RankItem.tsx
- components/rank/RankList.tsx
- styles/RankList.module.scss
- types/rankTypes.ts
- api 변경사항 확인 후 랭크페이지 내 관련 코드 수정
- userId => intraId 수정
- path 수정하여 브라우저에서도 정상적으로 동작
- ☄️ 승률이 0인 경우 순위 -1 입력되어 정렬 문제 확인 => 백엔드 전달
> [Feat] 랭크페이지 api 수정 #3

- pages/login.tsx
- styles/Login.module.scss
- styles/RankList.module.scss
- 로그인페이지 및 랭크페이지 마우스 포인터 수정
- 랭크 페이지 인트라 아이디만 클릭 가능하게 수정
> [Style] 클릭 액션 시 포인터 수정 #113

- components/game/GameResult.tsx
- components/game/big/GameResultBigScore.tsx
- components/game/big/GameResultBigTeam.tsx
- styles/game/GameResultItem.module.scss
- types/gameTypes.ts
- 게임 컴포넌트 Status 에 따른 애니메이션 구현
- Status에 따른 애니메이션 및 이벤트 구현
- Live는 위아래로 움직이는 애니메이션
- Wait는 움직이는 .  . . 애니메이션
- End는 끝난 시간으로 부터 얼마나 지났는지 확인
- API call 변수 변경
> [Feat] 게임 컴포넌트 Status 에 따른 애니메이션 구현

- components/modal/CancelModal.tsx
- styles/modal/CancelModal.module.scss
- 매칭 취소 버튼 눌렀을 때 변경된 api 수정, 안내 문구 수정
- 매칭 취소 버튼 눌렀을 때 변경된 api 수정
- 안내 문구 수정: 1분간 새로운 예액 불가 안내 추가
> [Fix] 매칭 취소 버튼 눌렀을 때 변경된 api 수정, 안내 문구 수정 #131

- components/Layout/CurrentMatchInfo.tsx
- components/modal/CancelModal.tsx
- components/modal/EditProfileModal.tsx
- components/modal/InputScoreModal.tsx
- components/modal/LogoutModal.tsx
- components/modal/MatchEnrollModal.tsx
- styles/Layout/CurrentMatchInfo.module.scss
- styles/common.scss
- styles/match/MatchBoard.module.scss
- styles/match/MatchBoardList.module.scss
- styles/match/MatchItem.module.scss
- styles/modal/CancelModal.module.scss
- styles/modal/InputScoreModal.module.scss
- styles/modal/LogoutModal.module.scss
- styles/modal/MatchEnroll.module.scss
- styles/user/Profile.module.scss
-
- 버튼 css 수정
-  input score 202 status 메시지 수정
> [Style] 버튼 스타일 및 input score 202 status 메시지 수정 #63

- components/Layout/Layout.tsx
- components/match/MatchItem.tsx
- components/modal/CancelModal.tsx
- styles/match/MatchItem.module.scss
- utils/recoil/match.ts
- slot 정보에서 받은 status 가 mytable 인 경우 버튼 색 다르게하기
> [feat] 내 매칭 버튼 색 다르게하기

- components/modal/MatchEnrollModal.tsx
> [feat] 매치 등록 시 새로고침

- components/rank/MyRank.tsx
- components/rank/RankItem.tsx
- components/rank/RankList.tsx
> [Fix] 경기 이력이 없는 유저 랭크 처리 #136

- components/game/big/GameResultBigScore.tsx
- styles/game/GameResultItem.module.scss
GameResultBigScore 컴포넌트 애니메이션 이벤트 분기처리 리팩토링
live 박스 witdh 추가
- [Fix] Game페이지및컴포넌트리펙토링 및 scss 추가
- GameResultBigScore 컴포넌트 애니메이션 이벤트 분기처리 리팩토링
- live 박스 witdh 추가
> [Fix] Game페이지및컴포넌트리펙토링 및 scss 추가

- pages/login.tsx
- styles/Pagination.module.scss
- styles/globals.css
> [Fix] 로그인페이지 디자인 처리 #63

- components/Layout/CurrentMatchInfo.tsx
- styles/Layout/CurrentMatchInfo.module.scss
- styles/common.scss
- styles/game/GameResultItem.module.scss
- currentMatchInfo 기다리는 중 애니메이션 구현
- common.scss 에 애니메이션 이벤트 추가 가져와서 쓸 수 있게 변수 추가
- currentMatchInfo span 태그 추가
> [Feat] currentMatchInfo 기다리는 중 애니메이션 구현

- components/game/GameResultEmptyArray.tsx
- components/game/GameResultList.tsx
- styles/game/GameResultEmpty.module.scss
- [Feat] 게임 데이터가 없을 때(빈 배열) 빈 결과 컴포넌트 리턴
- 게임 데이터가 없다는 기준을 GameResultList 페이지에서 캐치해서 리턴 보내준다
> [Feat] 게임 데이터가 없을 때(빈 배열) 빈 결과 컴포넌트 리턴

- components/game/small/GameResultSmallTeam.tsx
> [Fix] 작은 게임 결과에 프로필로 이동하는 링크 삭제 Close #147

- components/Layout/Header.tsx
- components/user/Profile.tsx
- 내 프로필에서만 프로필 수정하는 버튼 띄울 수 있게함
-  Profile 컴포넌트에서 userData 받아와서 intraId 같은 경우만 edit 버튼 띄우도록 수정
> [Fix] mypage profile edit button

- components/ErrorPage.tsx
- components/Layout/CurrentMatchInfo.tsx
- components/Layout/Layout.tsx
- components/Layout/NotiBar.tsx
- components/main/SearchBar.tsx
- components/match/MatchBoardList.tsx
- components/modal/CancelModal.tsx
- components/modal/EditProfileModal.tsx
- components/modal/InputScoreModal.tsx
- components/modal/MatchEnrollModal.tsx
- components/rank/RankList.tsx
- components/user/Chart.tsx
- components/user/Profile.tsx
- pages/_error.tsx
- styles/Error.module.scss
- utils/axios.ts
- utils/infinityScroll.ts
- utils/recoil/error.ts
- 에러페이지 구현
- axios 요청 시 에러가 발생하는 경우 catch에서 errorMessage를 처리하여 Layout에서 에러페이지로 이동
- 비정상적인 uri요청 시 에러페이지 처리 => 지속적인 요청 방지를 위해 router.replace로 uri초기화
- 에러페이지 내 홈버튼 추가로 메인페이지 이동
> [Feat] 에러페이지 구현 #152

- components/main/SearchBar.tsx
- 검색시 이전 검색 기록 남아있는 문제 해결
- 키워드 체크 통과 못할 시 검색결과 데이터를 초기화 시킴
> [Fix] 검색시 이전 검색 기록 남아있는 문제 해결 #154

- styles/match/match.module.scss
- 매치페이지 버튼 최근 매치 배너 생겼을 때 위치 밀리는 문제
- scss 수정
> [Style] 매치페이지 버튼 최근 매치 배너 생겼을 때 위치 밀리는 문제

- components/Layout/CurrentMatchInfo.tsx
- components/match/MatchBoard.tsx
- components/match/MatchItem.tsx
- components/modal/cancel/CancelBeforeFiveMinModal.tsx
- components/modal/cancel/CancelControll.tsx
- pages/match.tsx
- 내 매치 클릭시 매치 취소 모달 띄우기 구현
- 매치 취소 조건 추가
- 매치 취소 시점에 경기 시작 5분 전이여도 상대방이 없다면 취소할 수 있게 구현
- 내 매치 클릭시 매치 취소 모달 띄우기
> [Feat] 내 매치 클릭시 매치 취소 모달 띄우기 구현

- components/match/MatchBoardList.tsx
- pages/match.tsx
- styles/match/MatchBoardList.module.scss
- styles/match/match.module.scss
- 매칭페이지 새로고침 버튼 클릭시 깜박임 고치기
- window.location.reload() 삭제, 상태 변화로 핸들링
- getMatchDataHandler로 데이터 받는 함수 빼기
> [Fix] 매칭페이지 새로고침 버튼 클릭시 깜박임 고치기 #164

- components/Layout/Layout.tsx
- pages/login.tsx
- styles/Layout/Layout.module.scss
- styles/Login.module.scss
- styles/common.scss
- styles/modal/CancelModal.module.scss
- styles/modal/InputScoreModal.module.scss
- styles/modal/LogoutModal.module.scss
- styles/modal/MatchEnroll.module.scss
- styles/modal/MatchRejectModal.module.scss
- styles/modal/Modal.module.scss
- 배경 이미지 끊김 해결
- 레이아웃에 appContainer를 추가했습니다.
- 배경 이미지가 들어있는 컴포넌트의 최소 길이를 100vh로 설정하여 이미지가 끊기지 않도록 수정했습니다.
- 모달에 위아래 패딩을 주어 height를 따로 주지 않아도 되도록 수정했습니다.
> [Fix] 배경 이미지 끊김 해결 #124

- components/match/MatchItem.tsx
- MatchItem 에서 시간 지나면 +, 인원표시 사라지게 하기
- MatchItem 에 isAfterSlot : boolean 추가하여, 현재시간이 MatchItem의 현재시간을 지났는지 계산
- isAfterSlot이 true 인 경우에만 +, 인원표시 보이게함
> [Feat] MatchItem 에서 시간 지나면 +, 인원표시 사라지게 하기

- components/modal/InputScoreModal.tsx
- components/modal/MatchEnrollModal.tsx
- components/modal/cancel/CancelModal.tsx
- 에러 페이지에서 일부 상황에 새로고침되어 돌아가는 현상 수정
- 에러 페이지 이후 모달창 처리가 안된 경우 수정
- catch에서 return 하여 새로고침 해결
- catch에서 setter를 통해 모달창 처리
> [Fix] 에러페이지 이동 시 새로고침 수정 # 152

- components/game/big/GameResultBigScore.tsx
- components/game/small/GameResultSmallTeam.tsx
- 게임 컴포넌트 수정
- 작은 게임 컴포넌트에 intraId에 마우스 커서를 올리면 누를 수 있는 텍스트 처럼 보여지는 부분 수정
- 게임이 끝났을 때 1분전이 아니라 11분 전 정도로 처리가되는 부분 1분 전 으로 수정
> [Feat] 게임 컴포넌트 수정

- components/Layout/Header.tsx
- styles/Layout/Header.module.scss
- 헤더 알람 애니메이션 추가
- 헤더 알람 에니매이션 css 코드를 추가하였습니다
> [Feat] 헤더 알람 애니메이션 추가

- components/modal/MatchEnrollModal.tsx
- components/modal/cancel/CancelModal.tsx
- 매치 관련 모달창 동작 에러 처리
- 매치 등록, 취소 시 시간지남, 점수차, 매칭여부 등 다양한 경우에 대해 에러 처리 
- 각각의 상황에 맞는 에러 문구 alert창으로 띄워준 후 페이지 새로고침하여 사용자가 이상하게 느끼지 않도록 수정
> [Fix] 매치 관련 모달창 동작 에러 처리 #173

- components/rank/RankItem.tsx
- components/rank/RankList.tsx
- types/rankTypes.ts
- 경기력이 없는 경우 순위처리가 안되어 있어 발생하는 문제 처리
- 내 순위파악이 불가하여, api정보에 유저 intraId 추가하여 처리
> [Fix] 내 랭크 리스트 처리 #3

- components/game/big/GameResultBigTeam.tsx
- components/modal/EditProfileModal.tsx
- components/user/Profile.tsx
- styles/game/GameResultItem.module.scss
- styles/modal/CancelModal.module.scss
- styles/user/Chart.module.scss
- styles/user/Profile.module.scss
> [Style] 프로필 페이지 css 수정 #63

- components/match/MatchBoardList.tsx
- components/match/MatchManual.tsx
- pages/match.tsx
- styles/match/MatchManual.module.scss
- styles/modal/Modal.module.scss
- utils/recoil/match.ts
- 매치 메뉴얼 모달 구현
- match.ts 에 새로운 메뉴얼 리코일 추가 클릭 시 매치 페이지 에서 모달을 볼 수 있도록 구현
- 불필요한 로그 지우기
> [Feat] 매치 메뉴얼페이지 모달 구현

- components/match/MatchBoard.tsx
- components/match/MatchBoardList.tsx
- components/match/MatchItem.tsx
- styles/match/MatchBoardList.module.scss
- styles/match/MatchItem.module.scss
- styles/match/match.module.scss
- utils/axios.ts
- 매치 페이지 현재 시간에 맞춰 자동 스크롤 기능
- useRef 사용하여 렌더링 될때마다 현재 시간 MathBoard 로 스크롤 히도록 수정
> [Feat] Match 페이지에 스크롤 기능

- components/ErrorPage.tsx
- components/Layout/CurrentMatchInfo.tsx
- components/Layout/Layout.tsx
- components/Layout/NotiBar.tsx
- components/main/SearchBar.tsx
- components/match/MatchBoardList.tsx
- components/modal/EditProfileModal.tsx
- components/modal/InputScoreModal.tsx
- components/modal/MatchEnrollModal.tsx
- components/modal/cancel/CancelModal.tsx
- components/rank/RankList.tsx
- components/user/Chart.tsx
- components/user/Profile.tsx
- pages/404.tsx
- styles/Error.module.scss
- utils/infinityScroll.ts
- 에러 문구 처리 및 에러 코드 추가
- 모든 catch(e)문에 에러 코드 수정
- _error.tsx 를 404.tsx로 변경. warning 방지
> [Feat] 에러 문구 처리 #188

- components/match/MatchBoardList.tsx
- styles/match/MatchBoardList.module.scss
- 새로고침 애니메이션 구현
- 새로고침을 누를 때 마다 setTimeOut을 걸어서 1초 동안 커서를 비활성화 하게 구현
- 새로고침 애니메이션 추가
> [Feat] 새로고침 애니메이션 구현

- components/ErrorPage.tsx
- components/Layout/Layout.tsx
- components/main/SearchBar.tsx
- styles/Error.module.scss
- styles/Layout/Layout.module.scss
- styles/main/SearchBar.module.scss
> [Fix] 검색창 드롭다운 width 수정 #168

- styles/Layout/Layout.module.scss
- 화면이 커지는 경우 매치버튼이 배경 바깥으로 나가는 문제 해결
- scss파일에 position 속성을 부모컴포넌트에서는 relative, 자식컴포넌트에서는 absolute를 적용시켜 준다.
> [Style] 매치 버튼 배경 속으로 이동 #63

- components/game/GameResultList.tsx
- 게임 컴포넌트 더보기 버튼 숨기기
- 게임 컴포넌트에서 api 호출 할 때 새로운 데이터인 totalPage값을 이용해서 남은 토탈 페이지가 1이라면 더보기 버튼을 사라지게 구현
> [Feat] 게임 컴포넌트 더보기 버튼 숨기기

- components/Layout/Header.tsx
- components/game/big/GameResultBigTeam.tsx
- components/game/small/GameResultSmallTeam.tsx
- components/modal/InputScoreModal.tsx
- components/user/Profile.tsx
- next.config.js
- styles/Layout/Header.module.scss
- styles/common.scss
- styles/game/GameResultItem.module.scss
- styles/modal/InputScoreModal.module.scss
- styles/user/Profile.module.scss
- 유저 이미지 삽입
- next.config.js 파일: 허용 도메인 등록
- next/image 임포트해 이미지 삽입
- 헤더
- 프로필 페이지
- 게임결과 페이지 및 컴포넌트
-  스코어 입력 모달
- common.scss userImage 생성
> [Feat] 유저 이미지 삽입 #181

- components/modal/EditProfileModal.tsx
- components/user/Profile.tsx
- styles/user/Profile.module.scss
- winRate border-radius 수정
- 상태메세지가 비어있는 경우 문구 추가
- 상태메세지 편집시 placeholder 추가
- 순위 없는 경우 (순위 : -1) '-'로 보이도록 수정
> [fix] user 페이지 profile 수정

- components/ErrorPage.tsx
- styles/user/Profile.module.scss
> [Fix] 에러 페이지 홈 버튼 클릭시 새로고침 되도록 수정

- styles/Layout/Header.module.scss
- styles/common.scss
- 모든 이미지에 커서 뜨는 문제 해결
- common.scss userImage에 커서 빼고 헤더이미지에만 적용
> [Fix] 모든 이미지에 커서 뜨는 문제 해결

- components/game/GameResultEmptyArray.tsx
- styles/game/GameResultEmpty.module.scss
> [Style] 게임 결과 없을 때 창 css 수정 #63

- components/rank/RankItem.tsx
- components/rank/RankList.tsx
- 랭크리스트 상태메시지 길이 20자 제한 -> 작은 화면 기준 적정선
> [Fix] 랭크 리스트 상태메시지 길이 제한 #3

- components/Layout/Layout.tsx
- styles/Layout/Layout.module.scss
- 화면이 커져서 스크롤이 생기는 경우 매치버튼이 화면 아래로 내려가는 현상 수정
- 상위클래스를 추가하여 부모클래스에 sticky를, 자식 클래스에 absolute를 적용하여 해결
> [Fix] 매치 버튼 위치 수정 #209

- components/main/SearchBar.tsx
- styles/main/SearchBar.module.scss
- 검색 결과 드롭다운 위치, 내용 오류 고치기
- 검색 결과 드롭다운 위치, 내용 오류 고치기
- 검색어 바뀔 때마다 useEffexct에서 검색결과 초기화
> [Fix] 검색 결과 드롭다운 위치, 내용 오류 고치기 #204

- components/rank/RankItem.tsx
- styles/RankList.module.scss
> [Fix] 메인 랭크 리스트 상태 메시지 추가

- components/game/GameResultItem.tsx
- components/game/big/GameResultBigScore.tsx
- components/game/small/GameResultSmallScore.tsx
- GameResultBigScore 렌더링시 흔들리는 현상 수정 
- 상태로 관리되던 scoreStatuse 부분을 컴포넌트로 분리함
- 함수명, 변수명 리팩토링
> [Fix] GameResultBigScore 렌더링시 흔들리는 현상 수정 #212

- components/Layout/NotiBar.tsx
- styles/Layout/Notibar.module.scss
- 알람바 새로고침 애니메이션 추가
- css 에 애니메이션 적용
- useState로 이벤트 처리
> [Feat] 알람바 새로고침 애니메이션 추가

- components/main/SearchBar.tsx
- 검색 디바운스 문제 해결
- 타이머 전역변수로 수정했습니다.
> [Fix] 검색 디바운스 문제 해결 Close #204

- components/Layout/CurrentMatchInfo.tsx
- components/Layout/Header.tsx
- components/Layout/Layout.tsx
- components/Layout/MenuBar.tsx
- components/match/MatchItem.tsx
- components/modal/cancel/CancelControll.tsx
- components/user/Profile.tsx
- utils/recoil/layout.ts
- Cancel modal, Logout modal, MenuBar, Notibar 뒤로가기시 닫히도록 수정 
- presentPath 바뀌면 닫히도록 수정
- MenuBar와 NotiBar show 상태 리코일로 바꿈
- recoil/main 삭제, recoil/layout 으로 통합
> [Fix]Cancel modal, Logout modal, MenuBar, Notibar 뒤로가기시 닫히도록 수정 #180

- components/Layout/NotiItem.tsx
- styles/RankList.module.scss
- 알림 내용 수정
- 상대에 의해 성사되었습니다 -> 성사되었습니다 로 수정
> [Fix] 알림 내용 수정 #205

- components/game/GameResult.tsx
- components/game/GameResultList.tsx
- 게임 컴포넌트 각 프로필별 게임 전적 랜더링
- 프로필 페이지를 이동할 때마다 infResult를 remove refetch 받는 useEffect 추가
> [fix] 게임 컴포넌트 각 프로필별 게임 전적 랜더링

- next.config.js
- package.json
- utils/axios.ts
> [Feat] 배포 스크립트 추가 Close #226

- components/rank/RankItem.tsx
> [Style] 메인 랭크 리스트 점수 제거 #230

- next.config.js
- 이미지 안보이는 문제 fix
- 이미지 path 를 '/' 로 하면 이미지 url 에 hostname 이 추가됨
- 이미지 path 를 '' 로 수정하여 이미지 경로 올바르게 함
> [fix] 이미지 경로 수정

- components/Layout/Footer.tsx
- components/Layout/Layout.tsx
- components/Layout/MenuBar.tsx
- pages/manual.tsx
- styles/Manual.module.scss
- 메뉴얼 페이지 구현
- 메뉴얼 페이지 구현
- 메뉴바의 메뉴얼 버튼 과 푸터의 메뉴얼 버튼 연결
> [Feat] 메뉴얼 페이지 구현

- pages/manual.tsx
- styles/Manual.module.scss
- 매뉴얼 페이지 가운데정렬 안됨 수정
- 매뉴얼 페이지 가운데정렬 안됨 수정
> [Fix] 매뉴얼 페이지 가운데정렬 안됨 수정 #230

- components/Layout/Layout.tsx
- styles/Layout/Layout.module.scss
- 매칭 후 로그아웃시 jb03 에러 해결
- liveHandler 조건에 로그인 상태 추가
- 매치버튼 커서 추가
> [Fix] 매칭 후 로그아웃시 jb03 에러 해결 #237

- components/main/SearchBar.tsx
- 검색 한글자 칠 때마다 결과 사라지는 현상 수정
- 검색 키워드가 빈 문자열일 때만 검색 결과 사라지도록 수정
- 디바운스 속도 0.8 -> 0.5초로 수정
> [fix] 검색 한글자 칠 때마다 결과 사라지는 현상 수정

- components/match/MatchManualModal.tsx
- pages/manual.tsx
- styles/match/MatchManual.module.scss
- 메뉴얼 모달 스크롤 추가 글자 및 색 변경
- 메뉴얼 모달 스크롤 추가
- 메뉴얼 모달 글자 색 변경 흰색 -> 검정색
> [Fix] 메뉴얼 모달 스크롤 추가 글자 및 색 변경

- package-lock.json
- package.json
- utils/axios.ts
- deploy 브랜치 추가 및 배포 자동화 구현 하기
> [Feat] 배포자동화 구현 #238

- package-lock.json
- package.json
- utils/axios.ts
> [Feat] 배포 자동화 구현 중 #238

- package-lock.json
- package.json
> [Feat] webpack 버전 확인 #238

- README.md
> [Docs] README.md

- .github/workflows/main-deploy.yml
- utils/axios.ts
- 베포자동화코드구현
-  aws s3 buckey policy 수정
- github action 파일 수정
- axios 파일 수정
> Feat/ 배포 자동화 코드 구현#238

- .gitignore
- pages/login.tsx
- env 파일 분리
- env 파일 development 와 production으로 분리
- 코드 수정
- .gitignore 수정
> [fix] env 파일 분리

- lib/gtag.ts
- pages/_app.tsx
- GA4 적용하기
- GA4 적용해서 .env.production에 ga ID 넣어주세요~~:)
> [Feat] GA4 심기 #206

- .github/workflows/main-deploy.yml
- lib/gtag.ts
- pages/_app.tsx
- 깃 워크플로우 정리
- 깃 워크플로우에 구글 애널리틱스 적용  
- 깃 워크플로우 정리
> [Fix] 깃 워크플로우 정리 및 구글애널리틱스 적용#258

- components/ErrorChecker.tsx
- components/Layout/Layout.tsx
- pages/404.tsx
- pages/_app.tsx
- Error Check 로직 ErrorChecker 컴포넌트로 분리
- Layout에서 Error 검사하던 로직 ErrorChecker Component 로 분리
- _app.tsx 에서 Layout을 ErrorChecker 로 감쌈
- 404.tsx 에서 `router.replace('/')` 코드가 ErrorPage 컴포넌트에서 중복되기 때문에 지움
> [feat] Error Check 로직 ErrorChecker 컴포넌트로 분리

- styles/user/Profile.module.scss
> [Style] 프로필 편집 페이지 버튼 수정

- components/ErrorChecker.tsx
- components/Layout/Footer.tsx
- components/Layout/Layout.tsx
- components/LoginChecker.tsx
- next.config.js
- pages/404.tsx
- pages/_app.tsx
- pages/error.tsx
- pages/login.tsx
- 로그인 페이지 로직 분리
- LoginChecker컴포넌트를 추가하여 로그인 관련 code를 Layout에서 분리
> [Feat] Login Checker 추가하여 Layout과 분리

- components/user/Profile.tsx
- styles/user/Profile.module.scss
- 바꿨던 edit 버튼이 컴퓨터에서는 잘 보이지만 모바일에서는 이상하게 보이는 문제가 있어서 원래대로 복구했습니다
> [style] edit 버튼 복구

- components/rank/RankItem.tsx
- styles/RankList.module.scss
> [style] main page rank 컴포넌트 간격 수정#265

- components/match/MatchBoardList.tsx
- pages/match.tsx
- styles/match/MatchBoardList.module.scss
- styles/match/match.module.scss
> [Fix] 매치페이지 푸터 위치 조정 #230

- components/rank/MyRank.tsx
- components/rank/RankItem.tsx
- components/rank/RankList.tsx
> [Refactor] rank 관련 컴포넌트 리팩토링

- components/match/MatchBoardList.tsx
- styles/match/MatchBoardList.module.scss
- 마지막 게임 시간일 때 스크롤 문제 수정 및 게임시간 지난 경우 안내 문구 보이기
- 현재 시간이 마지막 시간일 때는 현재 시간에 ref 걸어 스크롤 안되는 문제 해결
- 현재 시간이 마지막 게임 시간 + 1보다 크거나 같을 때 "오늘의 매치가 모두 끝났습니다!" 보이게 하기
> [Fix] 마지막 게임 시간일 때 스크롤 문제 수정 및 게임시간 지난 경우 안내 문구 보이기 #230

- components/Layout/MenuBar.tsx
- types/mainType.ts
- utils/axios.ts
- utils/recoil/layout.ts
- 어드민 연결
- 유저 데이터에 isAdmin추가
- 메뉴바에 어드민일 경우 어드민 페이지 연결
- axios 필요 없는 주석 삭제
> [Feat] 어드민 연결 #275

- components/Layout/MenuBar.tsx
> [Fix] 어드민 이동 함수 수정 #275

- components/modal/WelcomeModal.tsx
> [fix] 페이지 가이드 링크 변경 #278

- components/Layout/CurrentMatchInfo.tsx
- components/Layout/Footer.tsx
- components/Layout/Header.tsx
- components/Layout/MenuBar.tsx
- components/Layout/NotiItem.tsx
- components/game/GameResult.tsx
- components/game/big/GameResultBigTeam.tsx
- components/main/SearchBar.tsx
- components/rank/RankItem.tsx
- pages/users/detail.tsx
- user 페이지 동적 라우팅 쿼리로 바꾸기
- user 페이지 동적 라우팅 쿼리로 바꾸기
- user 페이지로 가는 Link href 수정
- GameResult userpage 인 경우 path 수정
-  +) 메뉴와 푸터의 페이지 가이드 링크 변경
> [fix] user 페이지 동적 라우팅 쿼리로 바꾸기

- components/Layout/Header.tsx
- components/Layout/MenuBar.tsx
- components/modal/ReportModal.tsx
- styles/Layout/Header.module.scss
- styles/Layout/Menubar.module.scss
- styles/modal/ReportModal.module.scss
- utils/recoil/layout.ts
- 신고 모달 구현
- 신고 모달 만들었습니다.
- 메뉴바에 신고하기 버튼 추가했습니다.
- 관리자일 때는 관리자 버튼이, 관리자가 아닐 때는 신고하기 버튼이 보입니다.
- 레이아웃 recoil 파일에 reportModalState가 추가됐습니다.
- JH06 에러코드가 추가됐습니다.
> [Feat] 신고 모달 구현 #282

- components/modal/ReportModal.tsx
> [Feat] 신고 버튼 클릭 시 메뉴바 닫히도록 구현 #282

- components/modal/ReportModal.tsx
> [Refactor] radio목록을 map으로 뿌리도록 수정 #282

- components/rank/RankList.tsx
- 마이랭크 클릭 시 이동 안되는 현상 수정
- useEffect시 제거된 isScroll조건을 추가하여 해결
> [Fix] 마이랭크 클릭 시 이동 안되는 현상

- components/rank/MyRank.tsx
> [Fix] 마이랭크 이동 해결

- components/Layout/Header.tsx
- components/Layout/Layout.tsx
- components/Layout/MenuBar.tsx
- components/main/SearchBar.tsx
- components/modal/MatchManualModal.tsx
- components/modal/ReportModal.tsx
- styles/Manual.module.scss
- utils/recoil/layout.ts
- 검색창 글자 수 제한 및 x 버튼 작동하도록 수정
- show 라는 이름을 가진 변수들을 open으로 수정했습니다.
> [Fix] 검색창 글자 수 제한 및 x 버튼 작동하도록 수정 #230

- components/rank/RankList.tsx
> [Fix] rank페이지 asPath수정

- components/game/big/GameResultBigTeam.tsx
- styles/game/GameResultItem.module.scss
- BigComponent Image 클릭 이벤트 추가
- BigComponent 의 이미지를 클릭하면 프로필 페이지로 이동하게 구현
> [Feat] BigComponent Image 링크 이동 추가

- components/Layout/Header.tsx
- components/Layout/MenuBar.tsx
- components/Layout/NotiBar.tsx
- components/Layout/NotiItem.tsx
- styles/Layout/Notibar.module.scss
- styles/common.scss
- 알림 애니 처음 막기 및 알림오픈 상태 리코일로 수정
- 알림 애니 처음 막기
- 알림오픈 상태 리코일로 수정
- 이미지 빈 회면 그라데이션으로 수정
> [Fix] 알림 애니 처음 막기 및 알림오픈 상태 리코일로 수정 #301

- components/modal/ReportModal.tsx
- 건의사항 입력 시 공백과 개행만 입력된 경우 처리
- replace를 통해 공백과 개행을 제거하여 입력값이 있는지 판단하여 요청처리
> [Fix] 건의사항 입력 처리 #307

- components/Layout/Header.tsx
- components/Layout/Layout.tsx
- components/Layout/MenuBar.tsx
- components/Layout/NotiBar.tsx
- 메뉴바 Link로 수정 및 건의하기로 수정
- 메뉴바 Link로 수정
- 신고하기 -> 건의하기로 수정
- 메뉴바, 알림바 useResetRecoilState로 수정
> [Fix] 메뉴바 Link로 수정 및 건의하기로 수정 #304

- components/Layout/CurrentMatchInfo.tsx
- components/Layout/NotiBar.tsx
- styles/match/MatchBoardList.module.scss
- 5분 임박 & 상대 있을 때, 취소불가로 표시하기
- 5분 임박 & 상대 있을 때, 취소불가로 표시하기
> [Fix] 5분 임박 & 상대 있을 때, 취소불가로 표시하기 #310

- README.md
- components/modal/EditProfileModal.tsx
- components/user/Profile.tsx
> [Fix] 오타 수정

- components/LoginChecker.tsx
- 🎉🎉🎉 Beta Version 
- Coming soon Load 해제
- Login 연결
> [Release] Beta Version

- components/LoginChecker.tsx
- intra서버 문제로 인한 릴리즈 연기
- 로그인, 로드 둘 다 임포트
- 로그인은 주석 처리함
- intra 서버 문제가 복구되면 주석 해제할 예정
> [Release] Beta Version intra서버 문제로 인한 릴리즈 연기

- components/LoginChecker.tsx
- Beta Version 진짜 릴리즈
- 로그인 주석 해제
> [Release] Beta Version intra서버 복구됨, 진짜 릴리즈

- components/Layout/CurrentMatchInfo.tsx
- styles/Layout/CurrentMatchInfo.module.scss
- 현재 매치 정보 배너: 상대가 있는 상태로 경기 5분 임박시 회색처리
- 릴리즈 후 건의사항 반영
> [Fix] 건의사항 반영 / 현재 매치 정보 배너: 상대가 있는 상태로 경기 5분 임박시 회색처리 #310

- components/error/Error.tsx
- components/modal/EditProfileModal.tsx
- styles/user/Profile.module.scss
> [Feat] 라켓 타입 듀얼 추가 Close #320

- components/modal/MatchManualModal.tsx
- 매뉴얼 페이지 수정
- 매뉴얼에 경기 취소, 노쇼에 해당하는 내용 보강
> [Fix] 매뉴얼내용추가

- components/modal/EditProfileModal.tsx
- components/user/Profile.tsx
- 다른 사용자 프로필 페이지에서 상태메시지가 없는 경우 상태메시지 비워두기
- 프로필 수정 시 모달창 닫히고 알럿창 뜨는 문제 해결
- intraId 확인하여 상태메시지 입력메시지 출력
- setModalInfo 코드 위치 수정
> [Fix] 상태메시지 및 모달창 수정 #327

- styles/Layout/CurrentMatchInfo.module.scss
> [Fix] 취소 불가 버튼 color 수정

- components/Layout/MenuBar.tsx
- components/Layout/NotiItem.tsx
- styles/Layout/NotiItem.module.scss
- 알림 공지 링크 기능 추가
- 공지에서 https가 있을 경우,
- (내용) => (링크걸 문자열) https://~ 이렇게 받아온 내용을
- '=>'기준으로 이후에 나오는 문자열에 해당 링크를 걸어줍니다.
> [Feat] 알림 공지 링크 기능 추가

- lib/gtm.ts
- pages/_app.tsx
- pages/_document.tsx
- 구글 태그 매니저 삽입하기
- lib/gtm.ts 추가
- _app.tsx 수정
- _document.tsx 수정
- .env.production 수정
> [Feat] 구글 태그 매니저 삽입하기 #334

- .github/workflows/main-deploy.yml
- 깃 워크플로우에 태그매니저 추가
- 깃 워크플로우에 태그매니저 추가
> [Feat] 깃 워크플로우에 태그매니저 추가 #334

- components/rank/MyRank.tsx
- components/rank/RankItem.tsx
- components/rank/RankList.tsx
- styles/RankList.module.scss
- 랭크페이지 수정
- 승률 제거
- intraId 옆 점수 제거 -> 승률위치로 이동
- 경기를 하지 않은 경우 (랭크 -1) 점수 '-'로 표기
- onClick  함수 이름 변경
> [Fix] 랭크페이지 수정사항 #336

- components/user/Profile.tsx
- styles/user/Profile.module.scss
- types/userTypes.ts
- utils/recoil/user.ts
- 프로필 페이지에 승패 추가 및 디자인 수정 
- 승패 추가했습니다.
- 유저 이름 삭제했습니다.
> [Feat] 프로필 페이지에 승패 추가 및 디자인 수정 #336

- components/Layout/Layout.tsx
- components/game/GameResult.tsx
- components/mode/ModeRadiobox.tsx
- components/mode/ModeSeasonMineProvider.tsx
- components/mode/ModeSeasonProvider_origin.tsx
- components/mode/SeasonProvider.tsx
- components/rank/RankList.tsx
- components/user/Chart.tsx
- components/user/Profile.tsx
- pages/game.tsx
- pages/users/detail.tsx
- styles/mode/ModeRadiobox.module.scss
- styles/mode/ModeSelect.module.scss
- types/mainType.ts
- utils/recoil/layout.ts
- 페이지별 Mode Season Provider 분리
- rank : ModeSeasonProvider 유지 (mode, season 정보 제공
- game : ModeSeasonMineProvider 생성 (mode, season, isMine 정보 제공)
- users/detail : SeasonProvider 생성 (season 정보만 제공)
> [Feat] 페이지별 Mode Season Provider 분리

- components/user/Profile.tsx
- components/user/RankProfile.tsx
- pages/users/detail.tsx
- styles/user/Chart.module.scss
- styles/user/Profile.module.scss
- types/userTypes.ts
- utils/recoil/user.ts
- 기본 프로필 / 랭크 프로필 분리
- 랭크 프로필 추가했습니다.
- 타입 및 리코일 수정했습니다.
- 주석처리한 부분은 api 연결 되면 사용할 부분입니다.
> [Feat] 기본 프로필 / 랭크 프로필 분리 및 랭크 시즌 드롭다운 추가

- components/rank/RankList.tsx
- components/rank/RankListFrame.tsx
- 랭크페이지 리팩토링 페이지네이션 위치 수정
- RankList와 RankListFrame에서 둘 다 메인인지 확인하는 게 불필요하다고 생각되어 RankListFrame으로 페이지네이션 컴포넌트 위치를 수정함
> [Fix] 랭크페이지 리팩토링 페이지네이션 위치 수정 #353

- components/statistics/StatisticsCharts.tsx
- components/statistics/StatisticsSelect.tsx
- pages/api/pingpong/stat/visit.ts
- styles/chart/Statistics.module.scss
- types/chartTypes.ts
- 차트페이지 목업 데이터 추가 및 get요청 받기
- 차트페이지 목업 데이터로 값 받기
- axios get 요청으로 값 받아서 그래프에 넣기
- key error 처리
> [Feat] 차트페이지 목업 데이터 추가 #344

- components/modal/afterGame/AfterGameModal.tsx
- components/mode/ModeSeasonMineProvider.tsx
- pages/api/pingpong/seasonlist.ts
- 게임결과 페이지 전체 및 일반전 시즌 제거, 목 api 추가
> [Fix] 일반전 시즌 제거, 목api 추가

- components/game/GameResult.tsx
- components/game/GameResultEmptyItem.tsx
- components/game/GameResultItem.tsx
- components/game/GameResultList.tsx
- components/game/big/GameResultBigScore.tsx
- components/game/big/GameResultBigTeam.tsx
- components/game/small/GameResultSmallScore.tsx
- components/game/small/GameResultSmallTeam.tsx
- types/gameTypes.ts
- utils/handleTime.ts
- utils/infinityScroll.ts
- 게임결과 페이지 일반전 추가 및 리팩토링
- 일반전 추가 및 내꺼만 보기 추가로 api 수정됨
- 유저 페이지에서 게임결과 페이지로 가는 링크 필요함 @tamagoyakii 
- > 유저페이지에서 몇 개로 보여줄 지 논의 필요
- big, small에서 mode === 'normal'일 경우, 
- 게임 스코어 대신 'VS'로 표시
- 승패 대신 레벨로 표시
- GameResultList 리팩토링 추가 예정 > 완료
- CSS 수정 예정
> [Feat] 게임결과 페이지 일반전 추가 및 리팩토링 #357

- utils/handleTime.ts
- utils/handleTime 함수들 JSDoc 적용
- utils/handleTime 파일에 시간 관련된 함수들이 많아진 것 같아 JSDoc을 사용해보았습니다! (제가 헷갈려서요🤣)
- 이제 vscode에서 함수에 마우스를 대면 설명을 보실 수 있어요!
참고 : https://www.youtube.com/watch?v=ORmnc-hLrYs&t=119s
> [Feat] utils/handleTime 함수들 JSDoc 사용해서 정리 #365

- components/mode/ModeSeasonProvider.tsx
- pages/api/pingpong/vip.ts
- pages/rank.tsx
- utils/infinityScroll.ts
- 모드에 따라 랭크페이지 이름 바꾸기
- rank 페이지에 상태로 모드를 ModeSeasonProvider에서 받아오게 만들었습니다!
- 그리고 모드에 따라 페이지 이름을 바꿔주는 함수를 추가해 줌
> [Fix] 모드에 따라 랭크페이지 이름 바꾸기 #353

- components/match/MatchBoard.tsx
- components/modal/MatchManualModal.tsx
- pages/match.tsx
- 일반 게임에 대한 매뉴얼 조금 추가했습니다. 아직 완성되지 않은 매뉴얼이니 더 추가하고 싶은 내용이 있다면 언제든 알려주세요!
> [Fix] 매치 매뉴얼 수정 #347

- components/user/Profile.tsx
- components/user/RankProfile.tsx
- pages/users/detail.tsx
- styles/user/Profile.module.scss
- types/userTypes.ts
- utils/recoil/user.ts
- 기본 프로필 api 연결했습니다.
- 랭크 프로필은 변경 사항이 있어 이후에 수정하도록 하겠습니다!
> [Feat] 프로필 api 연결 #350

- components/Layout/Layout.tsx
- components/mode/ModeSeasonMineProvider.tsx
- components/mode/ModeSeasonProvider.tsx
- components/mode/SeasonDropDown.tsx
- components/mode/SeasonProvider.tsx
- utils/recoil/seasons.ts
> [Fix] 시즌 드롭다운 리코일 관리 #375

- components/game/GameResult.tsx
- components/rank/RankList.tsx
- components/rank/RankListItem.tsx
- 게임 랭크 페이지 api 수정
- 임시로 넣었던 v1 뺐어요
- exp 0일때 터지는 것 수정 했어요
> [Fix] 게임 랭크 페이지 api 수정

- components/game/GameResultItem.tsx
- components/game/small/GameResultSmallScore.tsx
- styles/game/GameResultItem.module.scss
- 게임페이지 일반전 스타일링 추가
- 게임페이지 일반전 스타일링 추가
> [Feat] 게임페이지 일반전 스타일링 추가 #357

- components/modal/afterGame/AfterGameModal.tsx
> [Fix] 매치 팀 데이터 변경 #379

- components/game/GameResultItem.tsx
- components/game/big/GameResultBigTeam.tsx
- styles/game/GameResultItem.module.scss
- 게임페이지 일반전 레벨 수정
- 게임페이지 일반전 레벨 수정
- 레벨 앞에 `Lv` 추가
- 승패&레벨 박스 디폴트 크기를 정해줌
> [Fix] 게임페이지 일반전 레벨 수정 #357

- components/rank/MyRank.tsx
- components/rank/RankList.tsx
- components/rank/RankListFrame.tsx
- components/rank/RankListItem.tsx
- types/rankTypes.ts
- utils/recoil/myRank.ts
- 랭크페이지 코드 정리
- 이미 받아오는 데이터 백 삭제 요청 후 삭제함(types => intraId)
- 굳이 내려주지 않아도 되는 프롭스 삭제(isMain => 현재 라우터 위치로 파악 가능)
- 타입 이름 수정
> [Fix] 랭크페이지 코드 정리 #353

- components/Layout/Header.tsx
- components/Layout/Layout.tsx
- components/Layout/MenuBar.tsx
- components/match/MatchSlot.tsx
- components/modal/EditProfileModal.tsx
- components/modal/MatchEnrollModal.tsx
- components/mode/ModeSeasonProvider.tsx
- components/user/BasicProfile.tsx
- components/user/RankProfile.tsx
- pages/users/detail.tsx
- types/mainType.ts
- types/userTypes.ts
- utils/recoil/layout.ts
- utils/recoil/user.ts
- 게임 등록 body 추가 및 user, userLive 데이터 타입 추가 
- 매치 post에 body 추가했습니다. mode 기본값은 normal이며, 랭크인 경우만 rank로 요청됩니다.
- user, userLive 데이터 타입 추가했습니다. (currentMatchMode, seasonMode)
> [Feat] 게임 등록 body 추가 및 user, userLive 데이터 타입 추가 #379

- components/rank/RankList.tsx
- 메인페이지에서 현재시즌모드로 데이터 못 받아오는 문제 해결
- 메인페이지에서 데이터 요청시 현재 시즌모드 확인해서 데이터 요청함
> [Fix] 메인페이지에서 현재시즌모드로 데이터 못 받아오는 문제 해결 #353

- components/Layout/Layout.tsx
- components/modal/ModalProvider.tsx
- components/modal/afterGame/AfterGameModal.tsx
- components/modal/afterGame/ExpGameModal.tsx
- types/expTypes.ts
- types/modalTypes.ts
- types/scoreTypes.ts
- utils/recoil/expInfo.ts
- 경기 종료 이후 경험치 모달창 구현
- 현재 모달창에 애니메이션 추가예정
- FIXED-EXP 모달 추가
> [Feat] 경험치 모달창 구현 #364

- components/Layout/Layout.tsx
- components/match/MatchSlot.tsx
- components/modal/afterGame/AfterGameModal.tsx
> [Fix] 에러 코드 정리 #387

- components/modal/MatchEnrollModal.tsx
- components/mode/ModeSeasonMineProvider.tsx
- components/mode/ModeSeasonProvider.tsx
- components/mode/modeItems/IsMineCheckBox.tsx
- components/mode/modeItems/ModeRadiobox.tsx
- components/user/Chart.tsx
- styles/Error.module.scss
- styles/Layout/CurrentMatchInfo.module.scss
- styles/Layout/Menubar.module.scss
- styles/Layout/NotiItem.module.scss
- styles/Layout/Notibar.module.scss
- styles/common.scss
- styles/game/GameResultItem.module.scss
- styles/main/SearchBar.module.scss
- styles/modal/AfterGameModal.module.scss
- styles/modal/MatchRejectModal.module.scss
- styles/modal/Modal.module.scss
- styles/mode/IsMineCheckBox.module.scss
- styles/rank/RankList.module.scss
- styles/user/Profile.module.scss
- types/mainType.ts
- IsMine 체크박스 컴포넌트 추가했습니다.
- midium -> medium 오타 수정했습니다.
- mode 타입 변수명 정리했습니다.
rank/normal/both -> `recordMode`
rank/normal -> `matchMode`
> [Fix] IsMine 토글에서 체크박스로 변결 #389

- components/modal/afterGame/Celebration.tsx
- components/modal/afterGame/ExpGameData.tsx
- components/modal/afterGame/ExpGameModal.tsx
- styles/modal/ExpGameModal.module.scss
- utils/sleep.ts
- 경험치 상승 모달, 애니메이션 구현
- 경험치 상승 모달 구현
- 경험치 상승률을 상태로 만든다
- `
style={{
width: `${getPercent(maxExp, beforeExp)}%`,
}}
` 를 만들어 상태 값을 순차적으로 증가 시켜서 게이지가 올라가는 것 처럼 구현
- getPercent 함수가 100이 넘어가면 컴포넌트를 다시 호출하여 레벨 상승 후 이어서 경험치 증가하게 구현
> [Feat] 경험치 상승 모달, 애니메이션 구현 

- components/modal/ModalProvider.tsx
- 모달 닫는 함수명 수정
- modalCloseHandler -> closeModalHandler 로 수정했습니다.
> [Refactor] 모달 닫는 함수명 수정 Close #398

- components/Layout/CurrentMatchInfo.tsx
- components/Layout/Header.tsx
- components/Layout/Layout.tsx
- components/Layout/NotiBar.tsx
- components/error/Error.tsx
- components/error/ErrorChecker.tsx
- components/game/GameResult.tsx
- components/game/GameResultList.tsx
- components/game/big/GameResultBigTeam.tsx
- components/main/SearchBar.tsx
- components/match/MatchBoard.tsx
- components/match/MatchSlot.tsx
- components/modal/MatchEnrollModal.tsx
- components/modal/afterGame/AfterGameModal.tsx
- components/modal/afterGame/ExpChangeModal.tsx
- components/modal/afterGame/ExpGuage.tsx
- components/modal/afterGame/NormalGameModal.tsx
- components/modal/matchCancel/CancelModal.tsx
- components/mode/ModeSeasonMineProvider.tsx
- components/statistics/StatisticsChartData.tsx
- components/statistics/StatisticsSelect.tsx
- components/user/RankProfile.tsx
- pages/404.tsx
- pages/_app.tsx
- pages/login.tsx
- utils/infinityScroll.ts
- import 순서 정리
- 정리 기준은 다음을 따라 정렬하였습니다.
```
next             - from 'next/*'
react            - from 'react/*'
recoil           - from 'recoil'
types            - from 'type/*'
utils            - from 'utils/*'
components       - from 'components/*'
[icon]           - from 'react-icons/*'
styles           - from 'styles/*'
```
> [Refactor] import 순서 정리 및 안쓰는 import 삭제 #400

- components/user/RankProfile.tsx
- styles/common.scss
- styles/game/GameResultItem.module.scss
- styles/match/MatchSlot.module.scss
- styles/modal/ExpGameModal.module.scss
- styles/rank/RankList.module.scss
- styles/rank/RankListMain.module.scss
- styles/user/Profile.module.scss
- types/userTypes.ts
- utils/recoil/user.ts
- 일반 게임용 색상 추가
- 일반 게임 색상 추가했습니다.
- pp / rank 색상 분리했습니다.
- RankProfile 타입을 ProfileRank로 수정했습니다.
> [Feat]  일반 게임용 색상 추가 #408

- components/Layout/CurrentMatch.tsx
- components/Layout/Layout.tsx
- components/Layout/MenuBar.tsx
- components/Layout/NotiBar.tsx
- components/Layout/NotiItem.tsx
- components/LoginChecker.tsx
- components/rank/RankList.tsx
- components/rank/RankListItem.tsx
- components/rank/topRank/RankListItemMain.tsx
- components/rank/topRank/RankListMain.tsx
- components/user/BasicProfile.tsx
- components/user/ProfileChart.tsx
- components/user/RankProfile.tsx
- styles/Layout/CurrentMatchInfo.module.scss
- 변수명 및 함수명 일부 변경했습니다!
- 레이아웃, 메인, 랭크, 유저 페이지 변수명 및 함수명 변경!
- 노티아이템 컴포넌트 스테이트도 함께 변경했습니다!
> [Refactor] 변수명 수정 #405

- components/Layout/Header.tsx
- components/Layout/Layout.tsx
- components/Layout/MenuBar.tsx
- components/Layout/NotiBar.tsx
- components/Layout/NotiItem.tsx
- components/game/GameResult.tsx
- components/match/MatchBoard.tsx
- components/modal/menu/ReportModal.tsx
- components/mode/GameMode.tsx
- components/mode/MatchMode.tsx
- components/mode/ProfileMode.tsx
- components/mode/RankMode.tsx
- components/mode/modeItems/ModeRadiobox.tsx
- components/mode/modeItems/SeasonDropDown.tsx
- components/rank/RankList.tsx
- components/rank/topRank/RankListMain.tsx
- types/mainType.ts
- types/seasonTypes.ts
- utils/recoil/layout.ts
- utils/recoil/seasons.ts
- seasonMode 관련 데이터 업데이트 및 season 초기값 수정했습니다. 이에 따른 오류들은 이후에 새로운 이슈를 생성하여 처리할 예정입니다.
- seasonListState에 seasonMode 추가
- userState, liveState에 seasonMode 제거
- season 초기값 수정
- menubarState -> openMenubarState로 변경
- notibarState -> openNotibarState로 변경
> [Fix] seasonMode 관련 데이터 업데이트 및 season 초기값 수정 #419

- styles/mode/ModeRadiobox.module.scss
- styles/mode/ModeSelect.module.scss
- styles/mode/ModeToggle.module.scss
- styles/mode/SeasonDropDown.module.scss
> [Style] 시즌 드롭다운 스타일 추가 및 css 살짝 수정 #418

- components/mode/RankMode.tsx
- components/rank/RankList.tsx
- 페이지네이션 처리
- 일반전 일 때 페이지 숫자가 1 부족한 상태로 들어오는 현상 해결
- 모드가 바뀔 시 페이지 1페이지로 초기화
> [Fix] 일반전 페이지네이션 처리 #397

- components/user/BasicProfile.tsx
- 프로필 페이지 대체이미지 처리
- 이미지가 없는 유저 프로필 이후 이미지가 있는 유저 프로필에서도 대체이미치 뜨는 현상 처리
> [Fix] 프로필페이지 데체이미지 초기화 확인  #425

- components/Layout/CurrentMatch.tsx
- components/Layout/Layout.tsx
- components/error/Error.tsx
- components/error/ErrorChecker.tsx
- components/main/SearchBar.tsx
- components/modal/afterGame/exp/ExpChangeModal.tsx
- components/modal/afterGame/score/AfterGameModal.tsx
- components/modal/matchCancel/CancelModal.tsx
- components/modal/profile/EditProfileModal.tsx
- components/mode/modeItems/UserGameSearchBar.tsx
- components/rank/RankList.tsx
- components/rank/RankListItem.tsx
- components/statistics/StatisticsCharts.tsx
- components/user/BasicProfile.tsx
- components/user/ProfileChart.tsx
- components/user/RankProfile.tsx
- pages/404.tsx
- styles/Error.module.scss
- styles/rank/RankList.module.scss
- utils/infinityScroll.ts
- 에러 변수명 수정 및 내 순위 색상 변경
- errorMessage => error 변수명 수정
- 일반전에서 내 순위 분홍색 -> 민트색 변경
> [Refactor] 에러변수명 변경 및 내 순위 색상변경 #405

- components/game/GameResult.tsx
- components/game/GameResultList.tsx
- styles/game/GameResultItem.module.scss
- 게임페이지 데이터 page 내용 삭제, isLast 적용
- infinityScroll 데이터 요청 방식 변경: 기존 page 확인에서 isLast를 확인하여 데이터를 요청하는 것으로 변경함
- 그에 따라 GameResultList 컴포넌트 수정
- 그 외 새로고침 여러번 하면 시즌이 들어가기 전에 데이터를 요청해서 에러페이지로 넘어나는 것을 막기 위해 path 만들 때, season 조건을 추가해주었습니다!!
> [Fix] 게임페이지 변경된 데이터 적용 #427

- components/match/MatchBoard.tsx
- components/match/MatchSlot.tsx
- components/match/MatchSlotList.tsx
- components/modal/match/MatchEnrollModal.tsx
- types/modalTypes.ts
> [Fix] 매치등록시 새로고침 안되도록 수정 Close #435

- components/modal/afterGame/exp/ExpChangeModal.tsx
- components/modal/afterGame/score/AfterGameModal.tsx
- components/modal/afterGame/score/MatchTeams.tsx
- components/modal/afterGame/score/NormalGame.tsx
- components/modal/afterGame/score/RankGame.tsx
- types/mainType.ts
- types/scoreTypes.ts
> [Fix]  afterGameModal 맵 함수 에러 긴급패치

- components/mode/modeWraps/RankMode.tsx
- components/rank/RankList.tsx
- pages/rank.tsx
- styles/mode/ModeToggle.module.scss
- styles/mode/ModeWrap.module.scss
- styles/user/Profile.module.scss
- 토글 색상 수정
- 일반전 토글 색상 회색에서 norm-lightblue2로 수정했습니다.
- toggleMode 타입을 <string> => <MatchMode>로 수정했습니다.
- 유저 정보 수정 모달에서 라켓타입 테두리 되찾았습니다.
> [Style] 토글 색상 수정 #418

- components/rank/RankList.tsx
- 랭크페이지에서 1페이지인 경우 데이터 변경 안되는 문제 처리
> [Fix] 랭크 페이지에서 1페이지인 경우 데이터 문제 처리#441

- components/Layout/CurrentMatch.tsx
- components/Layout/Layout.tsx
- components/match/MatchBoard.tsx
- components/match/MatchSlot.tsx
- components/match/MatchSlotList.tsx
- components/modal/match/MatchEnrollModal.tsx
- components/modal/matchCancel/CancelModal.tsx
- styles/mode/ModeRadiobox.module.scss
- types/modalTypes.ts
- utils/recoil/match.ts
> [Fix] 매치 페이지 live 업데이트 #443

- components/Layout/NotiBar.tsx
- components/Layout/NotiItem.tsx
- 알림 제목,내용 한꺼번에 관리할 수 있도록 리팩토링
- NotiItem: `if else`에서 `객체`로 알림타입으로 제목, 내용 관리할 수 있도록 리팩토링
- NotiBar: 버튼 컴포넌트화
> [Refactor] 알림 제목,내용 한꺼번에 관리할 수 있도록 리팩토링#451

- components/modal/match/MatchEnrollModal.tsx
- components/mode/modeWraps/ProfileModeWrap.tsx
- enrollResponse 객체 추가 및 그에 따른 리팩토링
> [Refactor] enrollResponse 객체 추가 및 그에 따른 리팩토링 #453

- components/Layout/CurrentMatch.tsx
- components/match/MatchBoard.tsx
- styles/Layout/Notibar.module.scss
- styles/common.scss
- styles/match/MatchBoard.module.scss
-  refresh -> reload 변수명 통일
-  refresh, reload 제각각으로 쓰던 변수명 통일
> [Style] refresh -> reload 변수명 통일

- components/game/GameResult.tsx
- 게임 메인에서 라이브 경기 안뜸 수정
- 메인일 때 경로 `status=live` 추가
> [Fix]  메인에서 게임중 경기 뜨지 않는 문제 수정

- components/modal/afterGame/score/AfterGameModal.tsx
- components/modal/afterGame/score/DefaultGame.tsx
- components/modal/afterGame/score/RankGame.tsx
- styles/modal/AfterGameModal.module.scss
- types/scoreTypes.ts
- 게임 결과 모달 스코어 표시
- 랭크게임 결과 모달에서 상대방이 이미 스코어를 입력 하였으면 input박스가 사라지고 게임종료 버튼 띄워주기
- intraID 왼쪽정렬 -> 가운데 정렬로 수정
> [Feat] 게임 결과 모달 스코어 표시

- components/match/MatchSlot.tsx
- matchSlot 리팩토링
- if / else if / else 문 객체처리하여 리팩토링!
> [Refactor] matchSlot 리팩토링#460

- components/modal/afterGame/exp/ExpChangeModal.tsx
- components/modal/afterGame/exp/ExpGuage.tsx
- components/modal/afterGame/ppp/PppChange.tsx
- styles/modal/ExpGameModal.module.scss
- expModal 디자인 적용 및 랭크 게임일 때 ppp 추가
- expModal 디자인 적용
- 랭크 게임일 때 ppp 추가
> [feat] expModal 디자인 적용 및 랭크 게임일 때 ppp 추가

- components/modal/matchCancel/CancelController.tsx
- components/modal/matchCancel/CancelModal.tsx
- components/modal/matchCancel/CancelRejectModal.tsx
- CancelBeforeFiveMinModal 컴포넌트 이름 변경 및 리팩토링
- 컴포넌트 이름 변경했습니다. (CancelBeforeFiveMinModa -> CancelRejectModal)
- 해당 컴포넌트에서 시간을 변수로 바꿀 수 있도록 리팩토링했습니다.
- 모달에 뜨는 메시지를 추가했습니다.
> [Refactor] CancelBeforeFiveMinModal 컴포넌트 이름 변경 및 리팩토링 Close #463

- components/mode/modeWraps/GameModeWrap.tsx
- components/mode/modeWraps/MatchModeWrap.tsx
- components/rank/MyRank.tsx
- pages/game.tsx
- pages/match.tsx
- pages/rank.tsx
- styles/game/GameResultItem.module.scss
- styles/match/match.module.scss
- 타이틀 그림자 및 내 순위 수정
- 랭크 페이지, 매치 페이지, 게임 페이지 타이틀에서 일반전인 경우 타이틀 그림자를 파란색으로 변경
- 랭크 페이지에서 내 '순위'가 일반전인 경우 에는 내 '열정'으로 변경
- 랭크 페이지에서 RankList 컴포넌트에 props 추가 (warning 해결)
> [Fix] 타이틀 그림자 및 내 순위 수정 #465

- components/user/BasicProfile.tsx
- components/user/ProfileChart.tsx
- components/user/RankProfile.tsx
- pages/users/detail.tsx
- utils/infinityScroll.ts
- 프로필페이지 인트라 아이디를 key로, 유저 바뀔때 리렌더링 시키기
- detail에서 인트라 아이디를 key로, 유저 바뀔때 리렌더링 시키기
- 수정이가 가기 전에 말해주었던 거예욥! 🍒 @su1715 
- 참고 자료: https://beta.reactjs.org/learn/preserving-and-resetting-state#the-ui-tree
> [Fix] 프로필페이지 인트라 아이디를 key로, 유저 바뀔때 리렌더링 시키기

- components/modal/ModalProvider.tsx
- components/modal/match/CancelModal.tsx
- CancelModal 폴더 및 소소한 부분 리팩토링
> [Refactor] CancelModal 폴더 및 소소한 부분 리팩토링 #471

- components/match/MatchSlot.tsx
- 토글이 스위치될 때 상대가 등록한 매치 슬롯이 깜빡이는 문제 해결
- useMemo를 사용해 버튼 스타일 객체와 함수를 기억하고 있게 만들었습니다. 
- 따라서 토글 모드를 확인하고 색을 바꿔주는 시간을 단축시켰습니다. 해결:)
> [fix] 토글이 스위치될 때 상대가 등록한 매치 슬롯이 깜빡이는 문제 해결 close #450

- components/game/GameResultEmptyItem.tsx
- components/game/GameResultList.tsx
- 게임페이지 로딩중 추가
- 게임페이지 데이터를 받아오는 시간이 오래 걸려서 이것 저것 해보다가...
- 로딩중을 추가하였습니다.
> [Feat] 게임페이지 로딩중 추가 close #478

- components/modal/menu/ReportModal.tsx
- components/rank/MyRank.tsx
- styles/rank/RankList.module.scss
> [Refactor] myRank리팩토링#480

- components/modal/match/MatchManualModal.tsx
- styles/modal/MatchManualModal.module.scss
- 매치 메뉴얼 객체화
- 하드코딩 된 메뉴얼을 객체화 하였습니다.
> [Refactor] 매치 메뉴얼 객체화#347

- components/match/MatchSlot.tsx
- components/modal/event/WelcomeModal.tsx
- components/modal/match/CancelModal.tsx
- components/modal/match/MatchEnrollModal.tsx
- components/modal/match/MatchManualModal.tsx
- components/modal/match/MatchRejectModal.tsx
- components/rank/MyRank.tsx
- components/rank/topRank/RankListMain.tsx
- components/user/BasicProfile.tsx
- pages/game.tsx
- pages/match.tsx
- pages/rank.tsx
- styles/game/GameResultItem.module.scss
- styles/match/MatchSlot.module.scss
- styles/match/match.module.scss
- styles/rank/RankList.module.scss
- styles/rank/RankListMain.module.scss
- 코드 객체화 및 스타일 중첩
- content 라는 객체를 만들어 return 할 내용을 따로 저장했습니다.
> [Refactor] 코드 객체화 및 스타일 중첩 #483

- components/modal/afterGame/exp/ExpChangeModal.tsx
- components/modal/afterGame/exp/ExpGuage.tsx
- components/modal/afterGame/ppp/PppChange.tsx
- styles/modal/ExpGameModal.module.scss
-   expModal 디자인 수정
-  expModal 디자인 변경 
- 모달의 특정 부분을 클릭하면 종료를 못 하는 버그 수정
> [fix] expModal 디자인 변경

- components/modal/event/WelcomeModal.tsx
- components/modal/match/CancelModal.tsx
- components/modal/match/MatchRejectModal.tsx
- styles/modal/CancelModal.module.scss
- styles/modal/MatchManualModal.module.scss
- styles/modal/MatchRejectModal.module.scss
- styles/modal/WelcomeModal.module.scss
- content 속 배열을 문자열로 수정 및 개행 출력을 위한 스타일 추가
> [Refactor] content 속 배열을 문자열로 수정 및 개행 출력을 위한 스타일 추가 #483

- styles/modal/MatchManualModal.module.scss
- 메뉴얼 스타일 수정
-  `>li` 를 상위로 합쳤었지만 스타일이 뭉개지는걸 확인하여 원복
- `>li` 분리
> [Refactor]매뉴얼 css적용 안되는 부분 수정#347

- components/modal/afterGame/exp/ExpChangeModal.tsx
- components/modal/afterGame/exp/ExpGuage.tsx
- components/modal/afterGame/ppp/PppChange.tsx
- pages/_document.tsx
- 사파리 아이콘 메타태그 추가
- 사파리 아이콘 메타태그 추가
> [Feat] 사파리 아이콘 메타태그 추가 #488

- components/modal/match/CancelModal.tsx
- components/rank/MyRank.tsx
- cancelModal에 currentMatch 데이터 요청 추가
> [Fix] cancelModal에 currentMatch 데이터 요청 추가 #491

- components/modal/afterGame/score/AfterGameModal.tsx
- components/modal/afterGame/score/Guide.tsx
- components/modal/afterGame/score/NormalGame.tsx
- styles/modal/AfterGameModal.module.scss
- 일반전 경기 시작시 경기종료 모달에서 파랗게 활성화된 종료버튼 깜박 보이는 문제 발견
- 일반전 경기종료 버튼 10분 전 회색으로 보이게 하기
- 10분 전에 누를 수 없게 회색 비활성화된 버튼 보이게 하기
- 비활성화 버튼 누를 때, 모달 리렌더링 시키기
- 경기시작시간에서 10분이 지날 경우 버튼 활성화되어 보이게 함
> [Fix] 일반전 경기종료 버튼 10분 전 회색으로 보이게 하기 #477

- components/Layout/Header.tsx
- 메뉴 및 알림 백드롭 스크롤 해결
- openMenuBar 및 openNotiBar 통하여  overflow hidden 하였음.
-
> [Fix]메뉴 및 알림 열었을 때 백드롭 스크롤 되는 문제 해결#492

- components/LoginChecker.tsx
- pages/index.tsx
- utils/recoil/modal.ts
- welcomeModal 안나오는 버그 수정
- 토큰을 받을 때 바로 setModal 함수를 쓰는게 아니라 상태를 추가해서 처음 들어 왔다고 판단 이후 index.tsx 에서 모달 띄워주기
> [fix]welcomeModal 안나오는 버그 수정

- components/main/Section.tsx
- components/rank/RankList.tsx
- components/user/RankProfile.tsx
- pages/index.tsx
- isMain, RankProfile수정 및 Section 리팩토링
- RankList 컴포넌트에 isMain props 전달하는 것으로 수정
- RankProfile에서 경기력이 없을 때 기본값 수정
- Section 컴포넌트 리팩토링
> [Fix] isMain, RankProfile수정 및 Section 리팩토링 #521

- components/modal/ModalProvider.tsx
- styles/user/Profile.module.scss
> [Refactor] ModalProvider 객체화 #523

- components/game/GameResultList.tsx
- 게임페이지에서 유저검색시 더보기 안뜨는 문제
- `asPath`를 `pathname`으로 수정했습니다!
> [Fix] 게임페이지에서 유저검색시 더보기 안뜨는 문제 close #525

- components/rank/RankList.tsx
- rankList 중복 데이터 처리
- 중복 데이터가 들어오는 경우 index값으로 key를 변경하여 처리
> [Fix] rankList 중복데이터 처리 #526

- components/Layout/CurrentMatch.tsx
- components/match/MatchBoard.tsx
- components/modal/match/MatchManualModal.tsx
- components/rank/MyRank.tsx
- map 인자 수정
- i -> index 로 수정했습니다.
> [Refactor] map 인자 수정

- components/game/GameResultList.tsx
- 게임페이지 더보기 눌렀을 때 빅아이템 초기화되는 문제
- 빅아이템 초기값 셋팅 조건을 첫번째 데이터를 받아올 때로 바꿔주었습니다!
> [Fix] 게임페이지 더보기 눌렀을 때 빅아이템 초기화되는 문제 close #531

- components/rank/MyRank.tsx
- components/rank/RankList.tsx
- components/rank/RankListFrame.tsx
- pages/rank.tsx
- types/rankTypes.ts
- utils/recoil/myRank.ts
- myRank 랜더링 문제 수정
- myRank에 rank/normal 값을 모두 저장합니다.
> [Fix] myRank 랜더링 문제 수정 #534

- components/modal/menu/ReportModal.tsx
- 건의모달 점수 정정 항목 삭제
- 건의모달 점수 정정 항목 삭제
- 백엔드에서 불가하다 하여서 점수 정정 요청 항목을 삭제했습니다.
> [Fix] 건의모달 점수 정정 항목 삭제

- components/main/Section.tsx
- components/rank/RankList.tsx
- components/rank/RankListFrame.tsx
- components/rank/RankListItem.tsx
> [Fix] rank 페이지에서 props명 변경

- components/modal/match/MatchManualModal.tsx
- components/rank/RankListItem.tsx
- 일반전, 랭크전 매뉴얼 확정
- 매뉴얼 내용 확정해 수정 및 사소한 오타 수정
> [Feat] 일반전, 랭크전 매뉴얼 확정 #542

- components/LoginChecker.tsx
- components/modal/event/WelcomeModal.tsx
- pages/index.tsx
- welcomeModal 최초 로그인에 수정
- modalProvider 에서 분리하여 loginCheker에 직접적으로 선언 하는 방식으로 변경 하였습니다
> [Fix] welcomeModal 최초 로그인에 수정

- components/modal/menu/ReportModal.tsx
- 건의모달 항목 순서 변경
- 건의 모달 항목의 순서를 긍정적인 순서로 바꾸었습니다.
> [Fix] 건의모달 항목 순서 변경

- components/modal/match/MatchRejectModal.tsx
- components/user/ProfileChart.tsx
- components/user/RankProfile.tsx
- season, MatchRejectModal 예외 상황 처리
- season !== undefined 추가
- MatchRejectModal 에서 setReloadMatch 추가
> [Fix] season, rejectModal 예외 상황 처리 #548

- components/LoginChecker.tsx
- components/load/CommingSoon.tsx
- 일반전 업데이트
- 일반전 업데이트 + 서버 배포 전 로그인 막기
> [Update] 일반전 업데이트 + 서버 배포 전 로그인 막기

- package.json
- pages/_document.tsx
- 배포시 기존 로그인되어 있던 유저들이 이전의 페이지에 머물러 있는 문제 발생
- 브라우저 캐시 문제로 이전 버전의 html 문서를 읽어서 발생한 문제라고 판단해 캐시를 지우는 html 코드를 추가함
> [Bug] 업데이트 배포시 SyntaxError 해결하기

- package.json
- pages/_document.tsx
- 업데이트 배포시 SyntaxError 해결 및 배포
- html 코드 수정
> [Bug] 업데이트 SyntaxError 해결 및 배포

- components/rank/RankList.tsx
- components/rank/RankListItem.tsx
- styles/rank/RankList.module.scss
- 나의 RankListItem 깜빡임 해결
- Item 스타일을 객체로 만들고, 나의 Item 색을 지정하는 조건을 추가했습니다.
> [Fix] 나의 RankListItem 깜빡임 해결 #538

- components/LoginChecker.tsx
- 어드민만 로그인 가능하게 임의로 변경
- 로그인 체커에 유저를 요청하는 api보내서 isAdmin 인지 체크후 어드민이면 / 페이지로 이동
> [Fix] 어드민만 루트 페이지로 이동 가능하게 임의로 변경

- components/LoginChecker.tsx
- 어드민만 로그인 되었던 코드 롤백
- 어드민만 로그인 되었던 코드 롤백 하였습니다!
> [Fix] 어드민만 로그인 되었던 코드 롤백

- components/LoginChecker.tsx
- 새 시즌 시작! 및 일반전 업데이트
- 새 시즌 시작! 및 일반전 업데이트 가즈아
> [Release] 새 시즌 시작! 및 일반전 업데이트

- components/rank/RankListItem.tsx
> [Fix] 깜빡임 해결을 위해 level 표시 조건 수정 Close #562

- components/modal/statChange/ExpStat.tsx
- 최고치 경험치 표시방식 추가
- 42레벨일 경우 경험치 표기방식 추가 Max로 추가
-
> [Feat] 최고 레벨 시 경험치 표시방식 추가 #565

- components/mode/modeWraps/RankModeWrap.tsx
- components/rank/MyRank.tsx
- components/rank/RankListFrame.tsx
- 랭크페이지 경험치 순위 표시 수정
- 경험치 순위 표시 페이지 토글 일부 수정 : [랭크-일반] => [랭크-열정] 으로 변경
- 순위 목록 표제목 일부 수정 : [열정] => [순위] 로 변경
> [Fix] 랭크페이지 경험치 순위 표시 수정

- components/match/MatchSlot.tsx
- 슬롯 렌더링 줄이기
- `React.memo`를 이용해 매치슬롯 렌더링을 줄였습니당
> [Fix] 슬롯 렌더링 줄이기 #569

- styles/PlayerImage.module.scss
- 이미지 중앙정렬 안되는 문제 해결
- div 태그가 더 생기면서 속성 적용이 안되었음
- 이미지 속성 추가
> [Style] 이미지 중앙정렬 안되는 문제 해결

- components/modal/afterGame/RankGame.tsx
- components/modal/afterGame/Score.tsx
- 점수 입력 자판이 숫자 자판으로 뜨고 엔터로 제출 되도록 변경
- 점수 입력 타입 숫자로 바꾸고 0 ~ 2 밖 범위 입력 못하도록 변경
- 엔터키로 점수 입력 되도록 추가
> [Feat] 점수 입력 자판이 숫자 자판으로 뜨고 엔터로 제출 되도록 변경 #587

- package.json
- 버전 수정
- 버전 수정 0.1.0 -> 1.0.0
> [Update]package.json 파일 version 수정 #595

- components/game/GameResultList.tsx
- tsconfig.json
- utils/infinityScroll.ts
- tsconfig 설정 변경
- React component naming rule을 인식하기 위해 `typeRoot` 속성을 적용
- naming rule에 맞게 InfScroll 컴포넌트 이름 수정
- #613
> [Fix] update tsconfig 

- components/admin/notifications/CreateNotiButton.tsx
- components/admin/notifications/NotificationTable.tsx
- package-lock.json
- package.json
- pages/api/admin/notifications/index.ts
- notification page에서 사용할 no 
```
npm install & npm run dev
```
- notification table 단독 컴포넌트만 만들어져 있는 상황이라 위 사진처럼 _app.tsx에서 notification table만 출력되도록 변경해주면 mock api를 통해 테이블을 볼 수 있습니다.
- #627 에 남겼듯이 추후 MUI를 걷어내고 자체 테이블을 구축할 예정
> Feat/make notification table #627

- package-lock.json
- #637 참고
-
- 아래 두 군데가 추가됨
```
"node_modules/is-arrayish": {
"version": "0.2.1",
"resolved": "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz",
"integrity": "sha512-zz06S8t0ozoDXMG+ube26zeCTNXcKIPJZJi8hBrF4idCLms4CG9QtK7qBl1boi5ODzFpjswb5JPmHCbMpjaYzg=="
},
```
```
"is-arrayish": {
"version": "0.2.1",
"resolved": "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz",
"integrity": "sha512-zz06S8t0ozoDXMG+ube26zeCTNXcKIPJZJi8hBrF4idCLms4CG9QtK7qBl1boi5ODzFpjswb5JPmHCbMpjaYzg=="
},
```
> [Chore] update package-lock.json

- components/admin/users/UserManagementTable.tsx
- constants/admin/table.ts
- 관리자 페이지 하위 메뉴 중 유저 관리 페이지 랜더링 오류 해결
- 테이블 컬럼명이 있는 객체 경로 및 코드 수정 ([참고](https://github.com/42organization/42gg.client/commit/98e0597275e2e2f686d8fa42f30c994d2a7fa80b))
- 전달 받는 데이터 타입과 컬럼 원형 수정 ([참고](https://github.com/42organization/42gg.client/commit/159cbd3acfbe4ff67dba0ceac6c3388e74be1b31))
- #672
> Fix/cannot read table column object #672

- pages/_app.tsx
- _app.tsx 파일의 <Script/> id 오류 개선
> [Fix] <Script/> id 추가 #674

- pages/api/admin/games/index.ts
- types/admin/gameLogTypes.ts
- 게임 관리 페이지에 사용할 mock 구성
- API spec에 맞춰서 URL, method, data format 설계
- data format 타입 지정
- #680
> Feat/setup mock api in game management #680

- components/modal/admin/AdminFeedbackCheckModal.tsx
- 알림 메일 전송 관련 API 설정 변경
- isMail에 들어가는 값을 정상적으로 수정
> [Fix] modify property in sendNotification API #694

- components/modal/admin/AdminNotiAllModal.tsx
- styles/admin/modal/AdminNotiAll.module.scss
- 피그마 디자인 시안을 기준으로 CSS 대공사
1. `npm i && npm run dev`
2. 관리자 페이지의 "알림 관리"로 이동
3. 우측 상단에 있는 [All] 버튼 클릭
4. 디자인이 바뀐 전체 알림 모달 확인
- #676
> [Feat] 관리자 전체 알림 모달 디자인 수정 #693

- components/modal/admin/AdminPenaltyModal.tsx
- styles/admin/modal/AdminPenalty.module.scss
> Feat/관리자 유저 관리 패널티 모달 css 수정 #703

- components/modal/profile/EditProfileModal.tsx
- styles/user/Profile.module.scss
- types/userTypes.ts
- utils/recoil/user.ts
- 프로필 수정란에 슬랙, 이메일 받기 여부 선택지 추가
> [Feat] sns버튼 추가 #616

- components/Layout/Layout.tsx
- components/toastmsg/toastmsg.tsx
- hooks/useAxiosWithToast.ts
- axios interceptor로 공통되는 http res status에 따라 toast 띄어주기
> Feat/update axios interceptor #656

- components/Layout/MenuBar.tsx
- 관리자 페이지 연결 link 수정
- 기존 백엔드에 연결되있던 link를 프론트가 제작한 url로 이동하도록 수정
> [Chore] modify link to admin page in main #723

- components/modal/admin/AdminNotiUserModal.tsx
- types/admin/adminNotiUserTypes.ts
- 관리자 특정 유저 모달 중복 부분 개선
- setModal({modalName: null}) 중복 부분을 삭제하였습니다.
> Feat/관리자 특정 유저 모달 api 붙이기 #709

- components/modal/admin/AdminNotiAllModal.tsx
- types/admin/adminNotiAllTypes.ts
> Feat/관리자 전체 알림 모달 api 붙이기 #713

- components/admin/announcement/AnnounceList.tsx
- components/admin/feedback/FeedbackTable.tsx
- components/admin/notification/NotificationTable.tsx
- components/admin/users/UserManagementTable.tsx
- styles/admin/feedback/FeedbackTable.module.scss
- styles/admin/notification/NotificationTable.module.scss
- styles/admin/users/UserManagementTable.module.scss
- 각 테이블별 디자인을 수정했습니다.
- 테이블 내부에 있는 버튼 hover 효과  
- 페이지 폰트 규격을 rem으로 변경(반응형 작업을 위해)
- 테이블 홀짝 행별 배경색 구분
- 테이블 헤더를 한글로 표기
> Style/update style in content area #717

- components/admin/games/GamesTable.tsx
- components/admin/slot/SlotMain.tsx
- styles/admin/games/GamesTable.module.scss
> Feat/ 게임 관리 스타일 변경 #738

- components/Layout/CurrentMatch.tsx
- components/modal/match/MatchCancelModal.tsx
> [Fix] isImminent 수정

- components/admin/slot/SlotMain.tsx
- components/modal/admin/AdminFeedbackCheckModal.tsx
> [Fix] 콘솔에러 수정

- components/admin/slot/SlotMain.tsx
- components/modal/admin/AdminFeedbackCheckModal.tsx
- pages/api/pingpong/admin/games/index.ts
> [Fix] 콘솔 에러 수정

- components/LoginChecker.tsx
-  comming soon 페이지 반영
- 작업 연장으로 인해 comming soon 페이지 반영
> [Chore] redirect to comming soon page

- components/admin/feedback/FeedbackTable.tsx
> [Fix] modify api url

- components/match/MatchSlotList.tsx
- components/modal/profile/EditProfileModal.tsx
> [Feat] Hot Fix 날짜 월 표기, 슬랙 알림 준비중 문구

- components/admin/games/GamesTable.tsx
- 날짜 표기오류 수정, 슬랙 알림 임시 alert문구 표기
-
-
> [Fix] 날짜 표기오류 수정, 슬랙 알림 임시 alert문구 표기

- .github/CODEOWNERS
- .gitignore
- .husky/pre-commit
- .husky/prepare-commit-msg
- git / github 컨벤션 자동화
- deploy 브랜치에 직접 커밋 못남기도록 설정
- 브랜치 명에 있는 이슈 넘버를 커밋 타이틀 마지막에 부착
- codeonwer 해제
> Feat/update development setup #758

- README.md
- components/Layout/Footer.tsx
- package-lock.json
- package.json
- 리드미 갱신
- 2기 멤버 이름과 깃주소 추가
- mui badge 추가
- 저작권 표시 갱신
> Chore/update project guide #757

- styles/common.scss
> [Fix] modify font option #762

- components/rank/MyRank.tsx
- components/rank/RankList.tsx
- package-lock.json
- rank api 변경
- **Rank 페이지 조회**
- pingpong/ranks/{gameType}page=${page}&count=${count}&season={seasonId}
- /pingpong/ranks/{gameType}?page=${page}&size=${count}&season={seasonId}
- **경험치 랭킹 페이지 조회**
- /pingpong/vip?page=${pageNum}&count=${pageSize}
- /pingpong/exp?page=${pageNum}&size=${pageSize}
---
- 경험치 랭킹 페이지 조회에서`vip` -> `exp`, `count`->`size`로 변경
- Rank 페이지 조회에서 `count` -> `size`로 변경
rank 리스트 다른 시즌 요청시 에러를 입력받음
-
> [GGFE-11] Rank api 변경

- components/admin/users/UserManagementTable.tsx
- components/modal/ModalProvider.tsx
- components/modal/admin/AdminPenaltyModal.tsx
- components/modal/admin/AdminProfileModal.tsx
- package-lock.json
- types/admin/adminUserTypes.ts
- **관리자 유저** 페이지 api 수정
- 🛠 **유저 전체 조회** 🛠 : 변경사항 없음
- 🛠 **유저 검색 조회** 🛠
수정 전: pingpong/admin/users?q=${keyword}&page=${pageNumber}&size=${recordSize}
수정 후: pingpong/admin/users?intraId=${intraId}&page=${pageNumber}&size=${recordSize}
- 🛠 **유저 상세정보 조회(자세히)** 🛠
수정 전: pingpong/admin/users/{userId}/detail
수정 후: pingpong/admin/users/{intraId}
- 🛠 **유저 상세정보 수정** 🛠
수정 전: pingpong/admin/users/{userId}/detail
수정 후: pingpong/admin/users/{intraId}
+키 변수명 수정
- 상세정보 수정 api 확인 필요 -> 지금 요청안됨
> [GGFE-12] Admin - User

- components/admin/announcement/AnnounceEdit.tsx
- components/admin/announcement/AnnounceList.tsx
- **관리자 공지** api 수정
- 🛠 **공지사항 저장** 🛠
수정 전: pingpong/admin/announcement
수정 후: pingpong/admin/announcement
- 🛠 **공지사항 조회** 🛠
수정 전: pingpong/admin/announcement?page=${currentpage}&size=${recordSize}
수정 후: pingpong/admin/announcement?page=${page}&size=${size}
- 🛠 **공지사항 삭제** 🛠
수정 전: pingpong/admin/announcement
수정 후: pingpong/admin/announcement/{deleterIntraId}
- pingpong/announcement 수정 후 다시 확인필요
> [GGFE-27] Admin - Announcement

- components/admin/common/AdminSearchBar.tsx
- components/main/SearchBar.tsx
- components/mode/modeItems/UserGameSearchBar.tsx
- hooks/useSearchBar.ts
- searchbar에서 enter 동작 추가
- searchbar에서 seasondropdown에 첫번째값과 일치하다면 해당 동작 수행
- debounce 값을 300으로 수정하였습니다. 빠르게 타이핑했을때 바로 엔터를 쳤을 때 딜레이가 발생해 사용성이 떨어진다고 판단했습니다. 
-
> [GGFE-40] search enter 기능 추가

- components/match/MatchBoard.tsx
- components/modal/match/MatchEnrollModal.tsx
- components/modal/match/MatchRejectModal.tsx
- components/mode/modeWraps/MatchModeWrap.tsx
- hooks/modal/match/useMatchCancelModal.ts
- hooks/modal/match/useMatchEnrollModal.ts
- pages/_app.tsx
- utils/handleTime.ts
- match time 다루는 부분에서 닌자코드 수정
- stringToHourMin 함수 추가
- string의 hour과 min이 string으로 쓰일 때도 있고 number로 쓰일 때도 있어서 반환값은 string, number 둘 다 반환(따로 분리하는 게 나을까요? string만 반환, number만 반환하는 식으로)
-
> [GGFE-54] match time slice 닌자코드 수정

- pages/login.tsx
- styles/Login.module.scss
- kakao oauth 로그인 버튼 만들었습니다!
-
-
> [GGFE-71] Add kakao login button

- components/admin/season/SeasonCreate.tsx
- components/admin/season/SeasonList.tsx
- components/modal/ModalProvider.tsx
- components/modal/admin/SeasonEdit.tsx
- types/modalTypes.ts
- types/seasonTypes.ts
- utils/recoil/seasons.ts
- 관리자 시즌 페이지 api 명세 수정
- get, post, put, delete 요청 수정
- ~seasonMode가 빠지면서 타입을 바꿔주었는데 table의 타입이 꼬인건지 에러가 나네요.. 이부분은 다시 고쳐보겠습니다~
> [GGFE-29] 관리자 시즌 페이지

- components/error/Error.tsx
- styles/Error.module.scss
- Error page 작업
- 빈 노티 이모지 추가 및 색상 변경
- 배경색이나 배치는 임의로 한거라 이상한 부분 있으면 코멘트 남겨주세요
-
> [GGFE-77] Style Error page

- components/modal/event/WelcomeModal.tsx
- styles/modal/Modal.module.scss
- Modal z index 수정 + welcome  modal 스타일 수정
- Modal z-index 수정
- welcome modal div 하나더 감싸져있던 부분 수정
-
> [GGFE-69] Modal z index 수정 + welcome  modal 스타일 수정

- components/rank/topRank/RankListItemMain.tsx
- styles/common.scss
- styles/rank/RankListMain.module.scss
- styles/user/Profile.module.scss
- types/seasonTypes.ts
- utils/recoil/seasons.ts
- main에서 intraId 클릭해도 profile로 넘어가지 않는 문제
- season type 맞지않은 부분 수정했습니다.
- intraId를 link tag 안에 넣었습니다. 
- profilemodal 배경색, button디자인 수정했습니다.
- 빵빠레 디자인 변경했습니다.
-
> [GGFE-78] Style-intraID-profile

- components/modal/match/MatchManualModal.tsx
- styles/mode/ModeRadiobox.module.scss
- match 페이지 수정
- 토글 버튼 색상 수정
- 메뉴얼 BOTH (빠른매칭)에 대한 설명 수정
-
> [GGFE-80] match 페이지 토글버튼 & 메뉴얼 수정

- components/Layout/MenuBar/MenuBarElement.tsx
- components/modal/menu/LogoutModal.tsx
- styles/Layout/Layout.module.scss
- styles/Layout/MenuBar.module.scss
- styles/common.scss
- StyledButton 위치가 화면비율이 세로가 길 때 버튼 오른쪽이 흰색이 나오면서 배경 깨짐 현상 수정
- 버튼 자체에 오류가 있다고 생각했는데 더 근본적인 배경 min-width를 지정해줬습니다
- layout min-width 지정
- 메뉴바 & 일부 모달 버튼 cursor: pointer 옵션 적용
-
> [GGFE-73] StyledButton 위치 수정

- components/modal/event/AnnouncementModal.tsx
- 공지사항 모달을 헤더에 있는 아이콘으로 불러올시 체크박스가 업데이트 안되는 현상 수정
- 체크 안된 상태로 모달 종료시 로컬저장소에 있는 변수 삭제
- 모달을 불러올 때 체크가 되어있는지 확인하는 로직 추가
-
> [GGFE-79] 공지사항 모달 체크박스

- components/Layout/MenuBar/MenuBar.tsx
- styles/Layout/MenuBar.module.scss
- ~~MenuBar 항목들 cursor스타일 추가~~
- 73 branch에서 이미 적용됨
- MenuBar Profile 탁구왕과 intraId 사이 개행 추가
- ~~메뉴 항목들 중 cursor:point가 부분적으로 적용되어 있어서 메뉴 항목들 전체에 다 추가~~
- kakao 로그인 시 게스트 id가 너무 길어서 탁구왕 intraId가 이상하게 줄바꿈돼서 나옴 -> 탁구왕(개행)intraId 형식으로 변경
-
> [GGFE-85] Style Menubar profile 개행 추가

- styles/Layout/NotiBar.module.scss
- NotiBar delete + reload 버튼 cursor 스타일 추가
- delete 버튼 curosr: pointer 추가
- reload 버튼 spin상태일 때 cursor: wait로 변경
-
> [GGFE-86] Style NotiBar delete + reload 버튼 cursor 스타일 추가

- next.config.js
- styles/admin/AdminReject.module.scss
- 권한없음 페이지 스타일 변경
- 카카오로 로그인해서 관리자 페이지 접근하면 확인 가능합니다!
- 배경 이미지 -> 로그인 이미지로 변경
- 컨테이너 색상 임의로 변경
- 메인과 같은 폰트로 42gg 폰트 변경
-
> [GGFE-82] 권한없음 페이지 스타일

- components/admin/slot/SlotCurrent.tsx
- components/admin/slot/SlotMain.tsx
- styles/admin/slot/SlotMain.module.scss
- types/admin/adminSlotTypes.ts
- 관리자 api 명세 수정. 반응형 화면은 슬롯이 실제로 변경되는걸 보고 다시 수정하겠습니다. 
- 스케쥴 startTime 추가
- 최근 스케쥴 삭제 버튼 추가
-
> [GGFE-26] 관리자 슬롯

- components/Layout/CurrentMatch.tsx
- components/Layout/Layout.tsx
- pages/index.tsx
- styles/Layout/CurrentMatchInfo.module.scss
- styles/main/Home.module.scss
- mainPageProfile 위치 수정 + currentMatch 문구 수정
- mainPageProfile home에서 Layout으로 이동(항상 보이게)
- currentMatch의 (경기 예약 취소, 경기 취소 불가) 문구를 (예약 취소, 취소 불가)로 변경
- 전체에서 font-size 조정할 것이기 때문에 미디어쿼리 삭제
-
> [GGFE-81] Style mainPageProfile 위치 수정 및 currentMatch 문구 수정

- styles/Layout/NotiBar.module.scss
- Noti reload 버튼 수정
- noti 하단 deco 위치 수정
- Noti reload 버튼 matchboard에서 쓰는 스타일 그대로 사용(색만 변경)
- noti 하단 deco 위치 수정
-
> [GGFE-87] style Noti reload deco

- styles/globals.css
- media query fontsize 조정
- 임의로 폰트사이즈는 적용해놓은거라 이상하면 코멘트 달아주세요
- global.css에서 fontsize 화면 크기별로 조정
-
> [GGFE-91] Style media query fontsize 조정

- components/Layout/CurrentMatch.tsx
- components/Layout/Layout.tsx
- components/Layout/MainPageProfile.tsx
- pages/index.tsx
- styles/Layout/CurrentMatchInfo.module.scss
- styles/Layout/Layout.module.scss
- styles/Layout/MainPageProfile.module.scss
- mainPageProfile currentMatch 분리
- 홈 제외하고는 mainPageProfile 보이지 않음
- currentMatch는 항상 보이게
-
> [GGFE-92] mainPageProfile currentMatch 분리

- components/Layout/MenuBar/MenuBar.tsx
- 상대방 프로필 들어간 이후 menubar 열면 본인 사진으로 바뀌는 버그 수정
- profileState recoil상태가 공유되면서 생겼던 문제라 menubar에서는 recoil을 사용하지 않고 useState로 profile 상태를 관리하게 바꿨습니다.
-
> [GGFE-96] bug profile menu profile

- hooks/useSearchBar.ts
- styles/user/Profile.module.scss
- 서치할때 일치하지 않았을 경우에도 넘어가는 오류
- 제가 if문으로 안감싸놓았었네요 다음부터는 확실히 테스트후 올리겠습니다.
- profile페이지에 expbar 색상 변경했습니다. 확실히 정해지지는 않아서 이쁜색상있으면 알려주시면 감사하겠습니다.
- editbutton에 커서포인터추가했습니다.
-
> [GGFE-105] bug searchbar enter error

- components/rank/topRank/RankListMain.tsx
- ranklist 조건문 수정
- 1등과 2등 순서를 변경하는 과정에서 빈배열에서 1등과 2등에 undefined를 생성하게 되어 조건문을 수정했습니다.
- intraId가 중복되는 문제가있어 rank로 변경했습니다.
-
> [GGFE-110] rank bug 수정

- styles/Layout/NotiBar.module.scss
- Noti delete button css 수정
- 다른 브라우저 환경에서 전체삭제 문구가 줄바꿈이 되는 경우가 있어서 패딩을 변경하고 버튼 width, height를 삭제하여 button 속 font-size에 알아서 맞춰지게 변경했습니다.
-
> [GGFE-108] Noti delete button 수정

- styles/Layout/NotiItem.module.scss
- Noti enemy font-color 변경
- 기존 색상이 눈 아프고 잘 보이지 않는 색상이라 변경했습니다.
-
> [GGFE-109] Noti enemy font-color 변경

- components/modal/admin/AdminNotiUserModal.tsx
- admin noti api 수정
- admin에서 특정 유저에게 알림 보내는 api 수정했습니다.
-
> [GGFE-116] admin noti api 수정

- styles/Layout/CurrentMatchInfo.module.scss
- Current match 배경색상 수정
- Current match 레이아웃 배경색상에 어울리게 수정
-
> [GGFE-118] Current match 배경색상 수정

- components/admin/games/GamesTable.tsx
- hooks/modal/aftergame/useSubmitModal.ts
- api 관련해서 불필요해진 내용이 있어서 삭제했습니다.
- 일반 게임 결과 등록 api에서 teamId가 필요없어져서 수정했습니다.
- 게임 관리 api에서 season은 불필요해서 삭제했습니다.
-
> [GGFE-112] api 변경사항 적용

- cypress/e2e/profile.cy.ts
- profile cypress 수정
- 전첵적으로 classname 변경되것 부분 수정했습니다.
- api변경된 gameapi, profileApi 변경했습니다.
- gameapi의 경우 pingpong/games?intraId={username}&count=5&size=1로 변경되어 맞게 수정했습니다.
-
> [GGFE-114] profile 현재에 맞게 수정

- components/admin/games/GamesTable.tsx
- admin game 시작시간 추가
- admin game 시작시간 추가
-
> [GGFE-119] admin game 시작시간 추가

- components/modal/admin/AdminProfileModal.tsx
- pages/api/pingpong/admin/users/index.ts
- types/admin/adminUserTypes.ts
- Admin 페이지에서 유저 정보 수정 안되던 문제 수정했습니다.
백에서 처리하는 UserType과 프론트에서 처리하는 UserType이 달라서 발생하는 문제여서 통일시켜줬습니다 (`ROLE_ `prefix 제거)
-
> [GGFE-122] admin 유저 정보 수정 버그 수정

- components/modal/admin/AdminProfileModal.tsx
- pages/api/pingpong/admin/users/index.ts
- types/admin/adminUserTypes.ts
Reverts 42organization/42gg.client#876
다시 ROLE_ prefix 붙입니다.ㅎㅎ
> Revert "[GGFE-122] admin 유저 정보 수정 버그 수정"

- components/mode/modeItems/SeasonDropDown.tsx
- utils/recoil/seasons.ts
- 시즌을 백에서 최신정보를  배열0으로 보내줌에따른 변경
-  출력을 반대로 해주던 것을 삭제
- 배열 끝부분을 보내주던것을 삭제
-
> [GGFE-121] season dropdown

- types/admin/adminUserTypes.ts
- `ROLE_GUEST` 타입 추가
- 사용하지 않는 `ROLE_MANAGER` 타입 삭제하고 `ROLE_GUEST` 타입 추가했습니다.
-
> [GGFE-122] ROLE_GUEST 타입 추가

- utils/infinityScroll.ts
- 간혹 InfScroll 에서 undefined error가 나던 문제 수정
위와 같은 에러가 나서 data 존재 여부 조건 추가해줬습니다.
-
> [GGFE-124] InfScroll에서 error data 가 없는 경우 발생하는 에러 수정

- components/Layout/CurrentMatch.tsx
- 게임을 하고 결과가 다 끝난후 starttime type error 발생
- CurrentMatchContent에 currentMatchList가 없는 경우에도 접근을 하게 되어 생기는 문제라고 생각해 수정했습니다.
- 테스트는 dev에서 에러가 발생했는데 localhost에서는 오류가 발생하지 않아 pr올립니다
-
> [Bug] starttime typeerror

- components/game/GameScore.ts
- components/game/big/GameResultBigScore.tsx
- components/game/small/GameResultSmallItem.tsx
- components/game/small/GameResultSmallScore.tsx
RANK 게임에서도 END일 경우에만 점수 보이게 변경
게임 상태가 WAIT, LIVE일 경우에는 NORMAL, RANK 상관없이 VS가 뜨도록 수정했습니다
-
> [GGFE-115] RANK 게임에서도 END일 경우에만 점수 보이게 변경

- components/user/BasicProfile.tsx
- styles/user/Profile.module.scss
> [Fix] fix kakao img

- styles/Layout/MenuBar.module.scss
- styles/common.scss
- 일부 기종에서 menu bar logout 안보이던 문제 수정
- ~~menu bar logout 에  padding-bottom 입력~~
- 100vh에서 webkit-fill-available로 변경
-
> [GGFE-127] Style menu bar logout

- styles/user/Profile.module.scss
- 4자리 exp일 경우 expbox가 두줄이 되는 경우 발생
- 둘의 크기를 더 늘려주었습니다.
- nheo님으로 테스트했습니다.
-
> [GGFE-131] Style-profilepage-expbox

- components/admin/announcement/AnnounceEdit.tsx
- styles/admin/announcement/AnnounceEdit.module.scss
- 관리자 announcement 모달 스타일 수정 및 에러문구 수정
- 모달 스타일 수정 (배경색, title 색상)
- 에러문구 수정 (code값이 리팩토링되면서 바뀌어서 code값 수정)
-
> [GGFE-84] Admin announcement 수정

- hooks/Login/useLoginCheck.ts
- hooks/useAxiosResponse.ts
-  배포하면서 생긴 에러 수정
- ` const refreshToken = Cookies.get('refresh_token')` null일때 에러현상 수정
-
> [Fix] [GGFE-126] cookie error

- components/Layout/MenuBar/MenuBarElement.tsx
- styles/Layout/MenuBar.module.scss
- styles/common.scss
- 메뉴바 로그아웃 admin, normal인 경우 padding bottom 다르게 적용
- 
-
> [GGFE-134] 메뉴바 로그아웃 admin, normal인 경우 padding bottom 다르게 적용

- components/rank/topRank/RankListItemMain.tsx
- components/rank/topRank/RankListMain.tsx
- ranknumber 트로피에 숫자안보이는 문제 수정
- rank에 따라 숫자가 표시되게 변경했습니다.
-
> [Bug] [GGFE-135] ranknumber bug 수정

- components/Layout/Layout.tsx
- components/Layout/MegaPhone.tsx
- pages/api/pingpong/megaphones/index.ts
- pages/login.tsx
- styles/Layout/MegaPhone.module.scss
- 메인페이지 확성기 레이아웃
- 관리자페이지 제외 모든 페이지에서 보이게 적용해놨습니다.
- 클릭하면 5초간 멈췄다가 다시 진행합니다.
- 확성기 문구 수, 길이에 따라 애니메이션 시간 및 속도 조절하는 스타일 추가 필요
-
> [GGFE-161] 메인페이지 확성기 레이아웃

- components/modal/ModalProvider.tsx
- components/modal/store/purchase/BuyModal.tsx
- components/modal/store/purchase/GiftModal.tsx
- components/modal/store/purchase/NoCoinModal.tsx
- components/shop/GiftSearchBar.tsx
- components/shop/ItemCard.tsx
- hooks/modal/store/purchase/useNoCoinModal.ts
- styles/main/SearchBar.module.scss
- styles/modal/store/BuyModal.module.scss
- styles/modal/store/GiftModal.module.scss
- styles/modal/store/NoCoinModal.module.scss
- types/modalTypes.ts
- 구매, 선물 모달
- 아이템 가격이 보유코인보다 비쌀 때에는 게임참여 권유 모달을 띄웁니다.
- 구매, 선물 모달에서는 아이템 이름과 가격, 환불 불가 경고문을 보여줍니다.
- 선물 모달에서는 선물할 유저를 검색하면 확인 문구가 보이도록 했습니다.
- mock api 적용과 선물한 유저를 선택하지 않았을 때 예외처리를 추가할 예정입니다.
> [GGFE-164] 구매 선물 모달

- components/modal/ModalProvider.tsx
- components/modal/store/CoinHistoryContainer.tsx
- components/modal/store/CoinHistoryDetails.tsx
- components/modal/store/UserCoinHistoryModal.tsx
- components/modal/store/purchase/BuyModal.tsx
- components/modal/store/purchase/GiftModal.tsx
- components/mode/modeWraps/StoreModeWrap.tsx
- components/shop/ItemCard.tsx
- hooks/modal/store/purchase/useBuyModal.ts
- hooks/modal/store/purchase/useGiftModal.ts
- pages/api/pingpong/items/store.ts
- pages/api/pingpong/users/coin.ts
- styles/modal/store/CoinHistoryContainer.module.scss
- styles/modal/store/CoinHistoryDetails.module.scss
- styles/modal/store/UserCoinHistoryModal.module.scss
- styles/mode/StoreModeWrap.module.scss
- types/itemTypes.ts
- types/modalTypes.ts
- types/userTypes.ts
- 상점페이지 - 코인 내역 모달
- 상점페이지에서 매뉴얼 버튼 옆 코인을 누르면 코인내역 모달을 띄웁니다.
-  거래 내역엔 거래 날짜와 시간, 내용, 코인 변동액이 표시됩니다
-  /pingpong/users/coin에서 mock data를 볼 수 있습니다
- 무한 스크롤 적용되도록 수정할 예정입니다.
- 현재는 스타일 위주로 봐주시면 될 것 같습니다
- Item 타입에 ItemType추가, 이름 변경 사항 반영하여 구매페이지 아이템 컴포넌트 수정하였습니다
- 기존 구매, 선물 모달 버튼을 ModalButton 컴포넌트로 대체하였습니다
> [GGFE-171] 코인내역 모달

- components/modal/event/WelcomeModal.tsx
- 출석하기시 post요청보내는 것으로 변경
- 웰컴모달이 실행되면 post요청하는 것에서 출석하기를 눌렀을때 요청하는 것으로 변경했습니다.
-
> [GGFE-140] Attendance-modal

- components/Layout/MenuBar/MenuBar.tsx
- components/user/BasicProfile.tsx
- pages/api/pingpong/users/intraId.ts
- styles/Layout/MenuBar.module.scss
- styles/common.scss
- styles/user/Profile.module.scss
- utils/recoil/tierColor.ts
- 티어 이름별 색상변화
- 티어별로 티어이름에 색상이 변경됩니다.
- 전체적으로 색상업데이트 되었습니다.
-
> [GGFE-176] tier-colorchange

- components/modal/store/CoinHistoryDetails.tsx
- 코인 내역 모달 변동액 부호 추가
- 수정하면서 코인 변동액 양수일 때 +부호가 빠져서 다시 수정했습니다
> [GGFE-171] 코인 내역 모달 - 변동액 +부호 추가

- components/admin/announcement/AnnounceList.tsx
- components/admin/season/SeasonCreate.tsx
- components/admin/users/UserManagementTable.tsx
- styles/admin/Layout.module.scss
- styles/admin/SideNav.module.scss
- styles/admin/SideNavContent.module.scss
- styles/admin/announcement/AnnounceEdit.module.scss
- styles/admin/announcement/AnnounceList.module.scss
- styles/admin/announcement/Announcement.module.scss
- styles/admin/coin/CoinMain.module.scss
- styles/admin/common/AdminSearchBar.module.scss
- styles/admin/common/Pagination.module.scss
- styles/admin/feedback/FeedbackTable.module.scss
- styles/admin/games/GamesTable.module.scss
- styles/admin/modal/FeedbackDetail.module.scss
- styles/admin/notification/NotificationTable.module.scss
- styles/admin/penalty/PenaltyTable.module.scss
- styles/admin/receipt/MenuTab.module.scss
- styles/admin/season/SeasonCreate.module.scss
- styles/admin/season/SeasonList.module.scss
- styles/admin/slot/SlotCurrent.module.scss
- styles/admin/slot/SlotMain.module.scss
- styles/admin/store/ItemHistory.module.scss
- styles/admin/store/ItemList.module.scss
- styles/admin/store/StoreMain.module.scss
- styles/admin/users/UserManagementTable.module.scss
- 관리자 페이지 크기 및 비율 수정
- 관리자 페이지 폰트 크기와 화면 내에서 아이템이 차지하는 비율 등을 수정했습니다!
-
> [GGFE-167] 관리자 페이지 크기 및 비율 수정

- components/admin/feedback/FeedbackTable.tsx
- components/modal/ModalProvider.tsx
- components/modal/admin/AdminFeedbackCheckModal.tsx
- components/modal/modalType/AdminModal.tsx
- components/modal/modalType/NormalModal.tsx
- components/modal/modalType/StoreModal.tsx
- components/modal/store/StoreManualModal.tsx
- utils/recoil/modal.ts
- modalProvider 리팩토링
- modalProvider 내의 모달이 너무 많아서 분리했습니다.
- normal, admin, store 종류로 나눴습니다.
-
> [GGFE-178] modalProvider 리팩토링

- hooks/modal/store/purchase/useBuyModal.ts
- hooks/modal/store/purchase/useGiftModal.ts
- types/itemTypes.ts
- 구매, 선물 모달 api 변경사항 적용
- 구매, 선물 모달 api request body에 itemId가 삭제되어 해당 사항 반영했습니다
> [GGFE-164] 구매, 선물 모달 api 변경사항 적용

- components/Layout/MegaPhone.tsx
- hooks/useInterval.ts
- pages/api/pingpong/megaphones/index.ts
- styles/Layout/MegaPhone.module.scss
- 확성기 글자 크기 수정 + 아이템 넘어가는 로직 수정
- 확성기 글자 크기 - 화면이 작아졌을 때 확성기 내용이 다른 확성기 내용을 침범하여 이상하게 보여지는 문제 수정
- 확성기 마지막 아이템에서 첫번째로 돌아갔을 때 설정한 시간이 두 번 흐르던 문제 수정
-
> [GGFE-187] 확성기 글자 크기 수정 + 아이템 넘어가는 로직 수정

- .stylelintrc.json
- styles/Layout/MegaPhone.module.scss
- styles/Layout/MenuBar.module.scss
- styles/Layout/NotiBar.module.scss
- styles/ProfileColor.scss
- styles/admin/announcement/AnnounceEdit.module.scss
- styles/admin/modal/AdminNoti.module.scss
- styles/admin/season/SeasonCreate.module.scss
- styles/admin/season/SeasonList.module.scss
- styles/common.scss
- styles/main/SearchBar.module.scss
- styles/match/MatchBoard.module.scss
- styles/modal/store/GachaBall.module.scss
- styles/modal/store/InventoryModal.module.scss
- styles/rank/RankList.module.scss
-  stylelint all 속성 순서 설정에 추가
-  stylelint all 순서 설정에 추가
-
> [GGFE-192] stylelint all 속성 순서 설정에 추가

- components/Layout/CurrentMatch.tsx
- components/match/MatchBoard.tsx
- currentMatch 빈 배열인 경우 에러 수정
- currentMatch 빈 배열인 경우 조건 추가하여 에러 수정
-
> [GGFE-196] currentMatch 빈 배열인 경우 에러 수정

- components/admin/coin/CoinPolicyHistory.tsx
- components/modal/admin/AdminEditCoinPolicy.tsx
- constants/admin/table.ts
- types/admin/adminCoinTypes.ts
- 관리자 재화정책 등록 조회 api 연결
- 관리자 재화정책 등록 조회 api 연결하고 타입만 데이터에 맞춰서 수정했습니다!
-
> [GGFE-201] 관리자 재화정책 등록 조회 api 연결

- components/Layout/MegaPhone.tsx
- styles/Layout/CurrentMatchInfo.module.scss
- styles/Layout/MainPageProfile.module.scss
- styles/Layout/MegaPhone.module.scss
- 확성기 api 연결 + 디자인 수정
- 확성기 api 연결
- 디자인은 currentMatch에 맞춰서 크기 조정했습니다.
- currentMatch도 확성기 때문에 눈에 잘 안들어오는거 같아서 배경색 투명도를 조절했습니다.
- mainPageProfile 위에 간격 추가했습니다.
-
> [GGFE-203] 확성기 api 연결 + 디자인 수정

- components/Layout/NotiBar/NotiItem.tsx
- components/modal/modalType/StoreModal.tsx
- components/modal/store/UserCoinHistoryModal.tsx
- hooks/modal/store/purchase/useBuyModal.ts
- hooks/modal/store/purchase/useGiftModal.ts
- pages/api/pingpong/items/index.ts
- pages/api/pingpong/items/store.ts
- styles/Layout/NotiItem.module.scss
- types/inventoryTypes.ts
- 상점 - 구매, 선물 모달 api 연결
- 구매, 선물 모달 api 연결했습니다
- 노티 타입에 GIFT 추가했습니다
- ItemType 변경 사항 반영했습니다
-
> [GGFE-195] 상점 - 구매, 선물 모달 api 연결

- stories/layout/CurrentMatch.stories.tsx
- stories/layout/Megaphone.stories.tsx
- Megaphone-storybook 추가
- Megaphone-storybook 추가했습니다.
-
> [GGFE-227] Megaphone-storybook 추가

- components/modal/store/inventory/ChangeProfileBackgroundModal.tsx
- components/modal/store/inventory/ChangeProfileEdgeModal.tsx
- 뽑기 모달 응답 처리 수정
- 뽑기 모달 응답 수정으로 컴파일 에러 나는 부분 수정했습니다
- 에러코드는 확인 후 다시 pr 올릴 예정입니다
-
> [GGFE-234] 뽑기 모달 응답 처리 수정

- styles/game/GameResultItem.module.scss
- 베이직 프로필 테마에서 게임아이템 스타일 적용안되던 부분 수정
- 베이직 프로필 테마에서 게임아이템 스타일 적용안되던 부분 수정
-
> [GGFE-244] 베이직 프로필 테마에서 게임아이템 스타일 적용안되던 부분 수정

- components/admin/announcement/AnnounceEdit.tsx
- 관리자 - 공지사항 에러 수정
- resetHandler 정의된 위치가 ```  if (!user) return null;``` 뒤에 있어서 초기화 전 접근 문제가 있었습니다.
- resetHandler 위치를 앞으로 옮겨 해결했습니다.
-
> [GGFE-252] 관리자 - 공지사항 에러 수정

- styles/Layout/Header.module.scss
- styles/admin/modal/AdminNoti.module.scss
- 모바일 알림 숫자 크기 + 관리자 알림보내기 모달 스타일 수정
- 모바일에서 알림 숫자가 너무 작게 나와서 크기 수정했습니다
- 관리자 알림 보내기 모달에서 아이디 검색바 크기와 폰트 사이즈 수정했습니다!
-
> [GGFE-253] 모바일 알림 숫자 크기 + 관리자 알림보내기 모달 스타일 수정

- components/modal/store/purchase/BuyModal.tsx
- components/modal/store/purchase/GiftModal.tsx
- components/mode/modeWraps/StoreModeWrap.tsx
- pages/store.tsx
- utils/recoil/updateCoin.ts
- 상점페이지 코인 react-query 적용
- 기존에 리코일로 관리하던 코인 업데이트를 react-query를 사용하는 방식으로 수정했습니다.
- 구매, 선물 성공 시 invalidateQueries를 호출합니다.
- 이상 없을 시 주석처리해둔 updateCoin은 삭제하겠습니다
-
> [GGFE-248] 상점 코인 react-query 적용

- styles/modal/store/ColorPicker.module.scss
- input, colorpicker width 지정
- 모바일 id 색깔변경 모달에서 input, colorpicker 가 모달 벗어나는 문제가 있어 width 지정했습니다
-
> [GGFE-268] id 색깔변경 모달 - input, colorpicker width 지정

- components/modal/ModalProvider.tsx
- components/modal/event/AnnouncementModal.tsx
- components/modal/event/WelcomeModal.tsx
- components/rank/topRank/RankListMain.tsx
- hooks/Layout/useAnnouncementCheck.ts
- 출석모달 버그 수정
- 리액트쿼리로 변경되면서 기본값이 없어서 false일때 들어오도록 수정했습니다. 
- 에러코드가 400->409로 변경했습니다.
- /pingpong/users/images->/pingpong/users/top3로 직관성이 없다고 해서 변경되었습니다.
-
> [GGFE-261] 출석모달 버그 수정, top3 api url 변경

- components/admin/users/UserManagementTable.tsx
- components/modal/admin/AdminUserCoinModal.tsx
- components/modal/modalType/AdminModal.tsx
- constants/admin/table.ts
- pages/api/pingpong/admin/users/coin.ts
- styles/admin/modal/AdminUserCoin.module.scss
- styles/admin/users/UserManagementTable.module.scss
- types/admin/adminUserTypes.ts
- types/modalTypes.ts
- 관리자 코인 수정 기능 추가
- 유저 관리 페이지에서 코인 수정 버튼을 추가해 코인 수정 모달을 띄우도록 했습니다.
- 코인 지급(차감)액은 0이 아닌 숫자만 입력가능하도록 했습니다.
-
> [GGFE-269] 관리자 코인 수정 기능 추가

- components/modal/admin/AdminFeedbackCheckModal.tsx
- 관리자 피드백 완료 유저 알림 토스트 설정
- 기존에 토스트가 설정되어 있지않아 default at 토스트 뜨던 부분 토스트메세지 설정
-
> [GGFE-274] 관리자 피드백 완료 유저 알림 토스트 설정

- components/Layout/Footer.tsx
- components/modal/event/WelcomeModal.tsx
- 페이지 가이드 노션 링크로 교체
- 푸터 Page Guide 와 웰컴모달 페이지 소개 링크를 노션 페이지가이드 링크로 교체했습니다.
- 배포 직전 권한 수정만 하면 될 것 같습니다
-
> [GGFE-277] 페이지 가이드 노션 링크로 교체

- README.md
- github readme 업데이트
- github readme 업데이트
-
> [GGFE-276] github readme 업데이트

- components/modal/event/WelcomeModal.tsx
- 출석 api 호출 로직을 변경했습니다.
- 중첩된 try catch 블록을 제거함
-
> [GGFE-261] 출석 api 호출 로직 변경

- components/modal/admin/AdminProfileModal.tsx
- 관리자 유저상세정보에서 코인 수정 막음
- 코인 수정 api가 따로 생김에 따라 관리자 유저 상세정보에서 직접 coin을 삭제하는 부분은 막아놨습니다
- 직접 coin을 수정하면 해당 유저의 코인 내역에는 표시되지 않아서 막았습니다
-
> [GGFE-279] 관리자 유저상세정보에서 코인 수정 막음

- components/modal/afterGame/InputScore.tsx
- 점수 입력 모달에 모바일 숫자 키패드 하나 더 추가
- 상대방 점수 입력 부분에 inputMode와 pattern 추가했습니다
-
> [GGFE-280] 점수 입력 키패드 하나 더 추가

- components/Layout/Layout.tsx
- components/modal/ModalProvider.tsx
- components/modal/event/AnnouncementModal.tsx
- components/modal/modalType/NormalModal.tsx
- hooks/Layout/useAnnouncementCheck.ts
- isAttended 데이터를 수정했습니다.
- 리코일에서 user 데이터로 수정했습니다.
-
> [GGFE-261] useUser로 수정

- components/modal/ModalProvider.tsx
- components/modal/event/AnnouncementModal.tsx
- components/modal/event/WelcomeModal.tsx
- components/modal/statChange/CoinChangeModal.tsx
- hooks/Layout/useAnnouncementCheck.ts
> [GGFE-261] 출석모달버그

- components/modal/event/WelcomeModal.tsx
- components/modal/statChange/CoinChangeModal.tsx
> [GGFE-261] 409에러시 리로드

- components/modal/store/inventory/ChangeIdColorModal.tsx
- components/modal/store/inventory/EditMegaphoneModal.tsx
- components/modal/store/inventory/NewMegaphoneModal.tsx
- components/modal/store/inventory/ProfileImageModal.tsx
- 보관함 아이템 데이터를 만료시키는 로직을 추가했습니다.
- 뽑기 제외한 모달에서 사용한 아이템 업데이트가 잘 안되는 문제가 있어 만료시키는 로직을 추가했습니다.
-
> [GGFE-282] 쿼리 만료 로직 추가

- components/modal/statChange/CoinChangeModal.tsx
- components/modal/store/inventory/ChangeIdColorModal.tsx
- components/modal/store/inventory/ColorPicker.tsx
- ID 색깔 변경 모달 내 다른 곳 클릭 시 팔레트 꺼짐 추가
- ID 색깔 변경 모달 내 다른 곳 클릭 시 팔레트 꺼짐 추가
-
> [GGFE-283] ID 색깔 변경 모달 내 다른 곳 클릭 시 팔레트 꺼짐 추가

- README.md
- Github readme - 기술스택 react query 추가
- Github readme - 기술스택 react query 추가
-
> [GGFE-281] Github readme - 기술스택 react query 추가

- styles/Layout/CurrentMatchInfo.module.scss
- styles/game/GameResultItem.module.scss
- styles/modal/event/AnnouncementModal.module.scss
- styles/mode/SeasonDropDown.module.scss
- styles/store/ItemCard.module.scss
- 클릭 가능한 부분 curosr:pointer 추가
- currentMatch의 예약취소 버튼
- announcementModal의 하루동안 열지 않기
- 상점 - itemcard의 선물하기, 구매하기 버튼
- 랭크, 프로필, 게임 - 시즌 드롭다운
- 게임 - gameResultSmallItem
-
> [GGFE-285] 클릭 가능한 부분 curosr:pointer 추가

- components/modal/match/MatchManualModal.tsx
- 매치 매뉴얼 노쇼 패널티 문구 추가
- 매치 매뉴얼 전체, 일반 탭에 노쇼 시 24시간 패널티 적용 문구 추가했습니다
-
> [GGFE-286] 매치 매뉴얼 노쇼 패널티 문구 추가

- components/admin/SideNav.tsx
- components/admin/tournament/TournamentEdit.tsx
- components/admin/tournament/TournamentList.tsx
- constants/admin/table.ts
- pages/admin/tournament.tsx
- types/admin/adminTournamentTypes.ts
- types/admin/tableTypes.ts
- 관리자 토너먼트 페이지의 레이아웃을 작성했습니다.
- 기존 관리자 시즌페이지와 공지사항페이지를 가져와서 레이아웃을 작성했습니다. 추후 새로운 이슈열어서 디테일한 사항 수정할 예정입니다.
-
> Feat/관리자 토너먼트 페이지 레이아웃#1075

- components/admin/tournament/TournamentList.tsx
- components/modal/tournament/TournamentRegistryModal.tsx
- components/tournament/TournamentCard.tsx
- pages/tournament.tsx
- types/admin/adminTournamentTypes.ts
- types/modalTypes.ts
- types/tournamentTypes.ts
- 토너먼트에 필요한 인터페이스들을 통합하고 이동했습니다
- 
- 기존에 modalType에 있던 Info 인터페이스를 tournamentType을 새로만들어서 이동시켰습니다
- 인터페이스의 내부에 필요한 내용을 통합하고 알맞게 수정했습니다.
-
> [Feat]토너먼트 type 통일 #1084

- utils/infinityScroll.ts
- 레거시를 참고(거의 복사)하여 무한스크롤 제네릭 함수를 추가하였습니다.
> [Feat] 무한스크롤 제네릭 함수 #1092

- types/tournamentTypes.ts
- 토너먼트 전체조회 API를 위한 TournamentData 인터페이스를 `tournamentTypes.ts`에 정의하였습니다.
`export interface TournamentData {
tournaments: TournamentInfo[];
totalPage: number;
}`
> [Feat] TournamentData 타입 추가 #1094

- pages/api/pingpong/tournaments/index.ts
- Mock API 페이지네이션 로직을 수정하였습니다.
- 쿼리 매개변수로 필터링된 토너먼트들을 slice() 할 때 두 번째 매개변수를 잘못 입력하여 수정하였습니다.
- 추가로, 매개변수의 페이지 번호가 전체 페이지를 초과할 경우 404로 응답하도록 하였습니다.
> [Fix] 토너먼트전체조회 Mock API 페이지네이션 로직 수정 #1096

- components/Layout/MenuBar/MenuBarElement.tsx
- public/image/menu_halloffame.svg
- 명예의전당 링크를 메뉴바에 추가하였습니다.
- svg 파일 추가
- 명예의전당 링크 컴포넌트 추가
> Feat/메뉴바에 tournament record(명예의전당) 바로가기 추가 #1108

- .github/workflows/test-deploy.yml
- test-deploy 브랜치에 머지 시 dev.42gg.kr 버킷에 배포하도록 액션을 수정하였습니다.
> [Chore] edit test-deploy action #1114

- components/modal/admin/AdminTournamentParticipantEditModal.tsx
- components/modal/modalType/AdminModal.tsx
- styles/admin/modal/AdminTournamentParticipantEditModal.module.scss
- types/modalTypes.ts
> [Feat] 관리자 토너먼트 참가자 수정 모달 컴포넌트 추가 및 UI #1113

- components/admin/tournament/TournamentSearchBarGroup.tsx
- components/modal/admin/AdminTournamentParticipantEditModal.tsx
- package-lock.json
- package.json
- 참가자 수정 모달에 유저 검색 기능을 추가했습니다.
- 타이핑을 500ms 이상 멈추면 입력된 값으로 요청을 보내 유저 아이디 리스트를 받습니다.
- 유저 리스트를 받으면 드롭다운 메뉴로 보여줍니다. 방향키로 이동하여 엔터로 선택할 수 있습니다(MUI Menu 컴포넌트 내장 기능).
- 존재하지 않는 유저 아이디와 존재하는 유저 아이디를 시각적으로 구분할 수 있도록 하였습니다.
> Feat/관리자 토너먼트 참가자 수정 모달 유저 검색 기능 #1120

- hooks/tournament/useTournamentMatchEditor.ts
- 점수 수정 Request시에 teamId가 제대로 요청되지 않는 부분 수정
-
-
> [Fix] 점수 수정 request 수정 #1131

- pages/index.tsx
- 토너먼트가 없으면 빈 배열이 응답으로 오므로 배열 길이를 체크하도록 수정하였습니다.
> [Fix] 메인 페이지 토너먼트 미리보기 유효성 검사 수정 #1169

- pages/tournament.tsx
> [fix] 오타수정 #1176

- components/tournament/TournamentMatch.tsx
- 브라켓 뷰에서 party name이 TBD 일 경우 공백문자로 출력하도록 만들었습니다.
-
-
> [Fix] TBD를 공백문자로 표시하도록 변환 #1199

- components/admin/tournament/TournamentEditMatch.tsx
- components/modal/tournament/TournamentRegistryModal.tsx
- components/tournament/TournamentCard.tsx
- pages/api/pingpong/tournaments/dummyTournamentData.ts
- types/admin/adminTournamentTypes.ts
- types/tournamentTypes.ts
- player_cnt 변수명을 playerCnt로 변경햇습니다.
-
-
> [Fix] 변수명 수정 #1205

- pages/tournament-record.tsx
> [Chore] 페이지 제목 수정 #1213

- pages/tournament-record.tsx
> [Chore] 페이지 제목 수정 #1213 (#1214)

- components/admin/tournament/TournamentEdit.tsx
- hooks/tournament/useTournamentEditInfo.ts
- 토너먼트 생성, 수정시 분단위로 입력 할 수 있도록 수정했습니다.
-
-
> Others/관리자 토너먼트 생성 수정시 분단위로 설정 할수 있도록 수정 #1225

- components/modal/admin/AdminFeedbackCheckModal.tsx
- 체크되지 않고 있던 `isSend` 값을 확인하여 유저에게 알림을 보낼 지 보내지 않을 지 선택할 수 있도록 수정하였습니다.
> [Fix] 관리자 피드백 처리 상태 변경 시 알림 전송 선택 기능 오작동 수정 #1126

- components/rank/RankList.tsx
<hr>
<hr>
바뀐 백엔드 API에 맞추어 URL 을 변경했습니다.
-
-
> [Others] Rank 페이지 조회, 경험치 랭킹 페이지 조회 API URL 변경 #1223

- components/modal/profile/EditProfileModal.tsx
- 슬랙 봇등록이 완료됨에 따라 슬랙 알림 기능을 활성화 합니다.
-
-
> [Feat] 슬랙 알림 기능 활성화 #1233

- components/tournament-record/UserTournamentBracket.tsx
- components/tournament/UserTournamentBracket.tsx
- pages/tournament.tsx
- styles/tournament-record/UserTournamentBracket.module.scss
- 진행중인 토너먼트에 대해 유저가 경기 현황을 새로고침하여 볼 수 있도록 버튼을 추가하였습니다.
- 아래는 전적 페이지의 토너먼트 브라켓으로 테스트한 예시입니다(크롬, 빠른 3G 환경).
> [Others] 토너먼트 점수 입력 혹은 경기 종료 후 경기 진행 상황 업데이트 #1210

- components/admin/SideNav.tsx
- components/main/Section.tsx
- components/party/PartyCategory.tsx
- components/party/PartyNav.tsx
- components/party/PartyPenalty.tsx
- components/party/PartyPreview.tsx
- components/party/PartyReport.tsx
- components/party/PartyRoom.tsx
- components/party/PartyTemplate.tsx
- pages/admin/party.tsx
- pages/index.tsx
- styles/admin/party/PartyNav.module.scss
> [feat] admin페이지 nav바 생성

- components/Layout/Layout.tsx
- components/party/PartyNav.tsx
- components/party/PartyRoomEdit.tsx
- components/party/PartyRoomList.tsx
- components/party/PartyRoomTable.tsx
- hooks/party/usePartyCategory.ts
- hooks/party/usePartyList.ts
- pages/api/pingpong/party/admin/rooms/index.ts
- pages/parties/index.tsx
- styles/admin/party/PartyRoomEdit.module.scss
- styles/party/PartyMain.module.scss
- styles/party/ParytyRoomList.module.scss
- types/admin/adminParty.ts
- types/partyTypes.ts
- react-query를 이용한 category hook 구현
- 기존의 usePartyRoom을 사용하지않고 usePartyCategory를 사용해 category를 불러주세요
-
> category 관리 훅 구현

- components/party/PartyCreate.tsx
- hooks/party/usePartyCategory.ts
- hooks/party/usePartyTemplate.ts
- pages/api/pingpong/party/templates.ts
- pages/parties/create.tsx
- styles/party/PartyCreate.module.scss
- types/partyTypes.ts
- 파티 룸을 생성하는 PartyCreatePage컴포넌트를 구현했습니다.
- PartyTemplate을 조회, 생성, 수정, 삭제 가능한 훅을 만들었습니다.
- template을 가져오거나 수정할때 usePartyTemplate훅을 이용해 주세요.
훅 내부에 templates가 캐싱되어있으므로 꼭 훅을 이용해야 수정이 가능합니다.  
-
> Feat: PartyCreate페이지 작성 및 usePartyTemplate 훅 구현

- components/modal/ModalProvider.tsx
- components/modal/modalType/AdminModal.tsx
- components/modal/modalType/PartyModal.tsx
- components/modal/party/PartyRoomEditModal.tsx
- components/party/PartyRoomTable.tsx
- pages/parties/index.tsx
- styles/admin/party/PartyRoomEdit.module.scss
- types/modalTypes.ts
- utils/recoil/modal.ts
-  Party에 대한 모달을 생성가능하게 세팅
-  Admin에 PartyRoomEdit  모달 추가
-  Modal컴포넌트 종류에 Party항목을 추가
- `type PartyModal = 'REPORT_COMMENT' | 'REPORT_ROOM' | 'REPORT_NOSHOW'` 은 신고 작성시를 위한 예시 입니다.
-
>  Feat: Party관련 모달 설정 

- hooks/party/usePartyTemplate.ts
- pratyTemplate API를 다루는 hook
- react-query를 이용해 캐싱
- hook내부의 함수를 통해 API를 호출해야 데이터가 refresh됨
- 에러시 토스트를 띄움니다
-
> [Feat] partytemplate api사용 hook 구현

- components/recruit/Main/CollapseListItem.tsx
- components/recruit/Main/MyApplicationInfo.tsx
- components/recruit/Main/MyRecruitStatus.tsx
- components/recruit/Main/MyRecruitment.tsx
- components/recruit/Main/RecruitStepper.tsx
- hooks/recruit/useGetRecruitResult.ts
- hooks/recruit/useRecruitDetail.ts
- pages/api/pingpong/recruitments/[id]/applications/result/index.ts
- pages/recruit/[id]/index.tsx
- styles/recruit/Main/collapseListItem.module.scss
- styles/recruit/Main/myRecruitment.module.scss
- styles/recruit/RecruitList/list.module.scss
- types/recruit/recruitments.d.ts
- utils/handleTime.ts
- 유저의 상황별 페이지를 만들었습니다.
1기 ~ 5기 모집글에서 각 상태를 테스트 해 볼 수 있습니다.
- 지원 여부 확인 => 지원한 경우 지원서 페이지 이동 버튼
- 지원 상태 확인 (지원서 제출, 면접 시간, 결과)
⚠️ 지원 결과 확인 api에 필요한 `applicationId`는 현재 알 수 있는 방법이 없어 없는 쪽으로 구현해뒀습니다!
⚠️ 지원 여부 확인 방법과 상태 확인 방법은 임의로 처리해 둔 것입니다. 역시 나중에 확인해 볼 예정입니다.
| <img width="763" alt="Screen_Shot 2024-03-14 17 10 19" src="https://github.com/42organization/42gg.client/assets/57761286/6634481b-6030-4155-ba8f-0a8bcf17d774"> |  |
|--|--|
| <img width="763" alt="Screen_Shot 2024-03-14 17 10 30" src="https://github.com/42organization/42gg.client/assets/57761286/2b785785-9356-449f-910f-50bc531e472b"> | <img width="763" alt="Screen_Shot 2024-03-14 17 10 37" src="https://github.com/42organization/42gg.client/assets/57761286/28102196-5d79-4a52-b9ef-553f5e3a858d"> |
| <img width="763" alt="Screen_Shot …
> [Feat] 상황별 공고 메인 페이지

- components/admin/recruitments/recruitmentsEdit/RecruitmentEdit.tsx
- components/admin/recruitments/recruitmentsEdit/components/ActionSelectorButtons.tsx
- components/admin/recruitments/recruitmentsEdit/components/QuestionFormBuilder.tsx
- components/admin/recruitments/recruitmentsEdit/components/QuillDescriptionEditor.tsx
- components/admin/recruitments/recruitmentsEdit/components/TitleTimeRangeSelector.tsx
- hooks/recruitments/useRecruitmentEditInfo.ts
- styles/admin/recruitments/recruitmentEdit/components/ActionSelectorButtons.module.scss
- styles/admin/recruitments/recruitmentEdit/components/QuestionFormBuilder.module.scss
- styles/admin/recruitments/recruitmentEdit/components/QuillDescriptionEditor.module.scss
- 자잘한 스타일과 props를 개선했습니다.
- 기존 props를 모듈 패턴으로 정리하였습니다.
- style에 mui를 최대한 활용하여 깔끔하게 정리했습니다
- 폼 빌더에서 각 질문지별로  focus를 잡을 수 있도록 추가하였습니다.
**BEFORE**
**AFTER**
-
> Feat 관리자 공고 등록 수정 템플릿 #1256

- components/recruit/Main/MyRecruitStatus.tsx
- components/recruit/Main/MyRecruitment.tsx
- components/recruit/Main/RecruitStepper.tsx
- hooks/recruit/useGetRecruitResult.ts
- pages/api/pingpong/recruitments/[id].ts
- pages/api/pingpong/recruitments/[id]/applications/[applicationId]/result.ts
- pages/recruit/[id]/index.tsx
- types/recruit/recruitments.d.ts
- 지원 결과와 관련된 api 변경사항을 적용했습니다.
- 공고 상세 조회 api 변경사항 : 지원자가 작성한 지원서의 id가 추가되었습니다. (`applicationId`) 작성한 지원서가 없는 경우에는 null입니다.
- 지원서를 작성한 경우 지원하기 버튼을 disabled 처리했습니다.
- 지원 상태가 추가되었습니다.
- 제출 후 면접 일자 나오기 전 : PROGRESS
- 면접 일자가 나온 경우 : INTERVIEW
- 면접 전 탈락 : APPLICATION_FAIL
- 면접 후 탈락 : INTERVIEW_FAIL
| 면접 전 탈락 | 면접 후 탈락 |
| -- | -- |
|<img width="589" alt="Screen_Shot 2024-03-15 19 05 00" src="https://github.com/42organization/42gg.client/assets/57761286/653209a8-72b6-4ff5-b2de-2c87fc59483f"> | <img width="589" alt="Screen_Shot 2024-03-15 19 05 12" src="https://github.com/42organization/42gg.client/assets/57761286/bdd8cd8b-b354-46c8-a49b-e0081a9d8445"> |
-
> [Feat] 지원 결과 상태 추가

- components/modal/Party/PartyReportModal.tsx
- components/party/roomDetail/PartyDetailButton.tsx
- components/party/roomDetail/PartyDetailContentCommentBox.tsx
- components/party/roomDetail/PartyDetailProfile.tsx
- components/party/roomDetail/PartyDetailTitleBox.tsx
- pages/api/pingpong/party/rooms/[roomId]/index.ts
- pages/api/pingpong/party/rooms/[roomId]/start/index.ts
- pages/party/[roomId]/index.tsx
- styles/party/PartyDetailRoom.module.scss
- types/modalTypes.ts
- types/partyTypes.ts
- utils/handleTime.ts
-  rebase한 커밋 제거
- 원본상태에서 커밋 추가 및 푸쉬
> Feat/make party detail #1283

- hooks/party/usePartyColorMode.ts
- 파티의 배경이미지를 설정할 수 있는 hook입니다.
- 파티의 배경이미지를 설정할 수 있는 hook입니다.
-
> [Feat] party 배경 이미지 설정 hook

- components/party/PartyCreate.tsx
- constants/party/createOptions.ts
- hooks/party/usePartyCategory.ts
- pages/party/create.tsx
- styles/party/PartyCreate.module.scss
- 파티 방 생성 페이지 구현
- 카테고리 선택 페이지 구현
- 세부사항 수정 페이지 구현
- useCategory에 loading, error 상태 체크 추가
- 카테고리 불러오는 데 실패하면 메인화면으로 리다이렉트
- 방 생성에 실패하면 toast 이후 재시도
-
> [Feat] party모집 방 생성 페이지 구현 #1281

- hooks/party/usePartyCategory.ts
- hooks/party/usePartyTemplate.ts
- 백엔드 api변경에 따른 api hook 수정
- 카테고리, 템플릿 가져오는 api 수정
-
> [Hotfix] category, template api 리스트에 키값 추가

- pages/party/index.tsx
- 방리스트에 필터가 적용되지않는 오류 수정
- categoryId 필터를 categoryName 필터로 변경
-
> [Bug] 파티 메인 페이지 전체 필터 적용안되는 오류 수정

- components/party/PartyRoomListItem.tsx
- pages/party/index.tsx
- styles/party/PartyCommon.scss
- styles/party/PartyMain.module.scss
- styles/party/PartyRoomListItem.module.scss
- 메인 페이지 마감시간 표시 및 진행중 표기
- 메인 페이지 마감시간 표시 및 진행중 표기
- css 파일 style 변경
-
> [Feat] 메인 페이지 마감시간 표시 및 진행중 표기

- components/party/PartyCreate.tsx
- styles/Layout/Layout.module.scss
- styles/party/PartyCreate.module.scss
- types/partyTypes.ts
- 파티 생성 페이지 배경 설정 및 글자수 표기
- 파티 생성 페이지 배경 변경
- 기존의 party-detail 배경 삭제
- 생성 페이지에 글자 수 표기
-
> [Feat] 파티 생성 페이지 배경 설정 및 글자수 표기

- components/main/PartyPreview.tsx
> [Feat] 파티프리뷰 활성화방없을시 처리

- components/party/roomDetail/PartyDetailButton.tsx
> [test-deploy] react-icons 버전에 따른 party 공유, 신고 아이콘 종류 변경 후 테스트 재배포

- components/admin/recruitments/recruitmentsuser/tmplateEditor.tsx
- components/modal/admin/AdminRecruitMessageTemplateModal.tsx
- 면접 결과 안내 메시지 템플릿 조회 / 등록 api 연결
- 주석 처리 해둔 부분을 수정했습니다
- 아직 api가 배포 안된 상태라 테스트는 불가합니다
> [Feat] 면접 결과 안내 메시지 템플릿 조회 / 등록 api 연결

- components/admin/recruitments/recruitmentsDetail/components/QuestionForm.tsx
- components/admin/recruitments/recruitmentsEdit/components/ActionSelectorButtons.tsx
- components/admin/recruitments/recruitmentsEdit/components/QuestionFormBuilder.tsx
- hooks/recruitments/useRecruitmentEditInfo.ts
- types/admin/adminRecruitmentsTypes.ts
- 타입 에러로 인해 발생하던 빌드 에러를 수정했습니다.
- `IcheckItem` 의 content / contents
=> content로 수정하겠습니다.
- `Iquestion`
=> 빈 지원서 데이터에서 쓰이는 경우 checkList, 유저가 응답한 데이터에서 쓰이는 checkedList가 섞이면서 타입 에러 발생
=> 유저 응답 데이터에서 쓰이는 타입을 별도로 추가하는 방식으로 수정하겠습니다 (`IuserFormResponse`)
-
> [Fix] 타입 에러로 인한 빌드 에러 수정

- components/admin/recruitments/recruitmentsuser/NotificationResults.tsx
- components/modal/admin/AdminRecruitResultModal.tsx
- components/modal/modalType/AdminModal.tsx
- types/modalTypes.ts
- 테스트를 위한 임시 결과 등록 모달을 추가했습니다.
-
> [Feat] 임시 결과 등록 모달 추가

- components/admin/recruitments/RecruitmentsHistoryList.tsx
- components/admin/recruitments/recruitmentsDetail/RecruitmentDetail.tsx
- components/admin/recruitments/recruitmentsEdit/components/ActionSelectorButtons.tsx
- components/admin/recruitments/recruitmentsuser/NotificationResults.tsx
- hooks/recruitments/useRecruitmentEditInfo.ts
- hooks/recruitments/useRecruitmentUserFilter.ts
- recruit 쪽의 mock api를 제거했습니다.
- 테스트 배포 후 동작 확인 예정이라 오류 여부 확인을 못했습니다.
- 이해가 안되는 부분은 FIXME 코멘트 달아두고 이해한대로 수정했습니다. 담당하신 분은 나중에 확인 부탁드립니다.
-
> [Feat] mockinstance 제거

- components/recruit/RecruitList/RecruitListItem.tsx
- hooks/recruit/useUserApplicationForm.ts
- recruit user api 연결 중 발견된 에러 수정
- user 공고 목록에서 시작, 종료 날짜 모두 시작날짜를 보여주던 문제 수정
- 지원하기 api 요청 body 수정
-
> [Fix] recruit user api 연결 중 발견된 에러 수정

- components/recruit/Main/MyApplicationInfo.tsx
- components/recruit/Main/MyRecruitment.tsx
- 지원 결과 조회 api 버그 수정
- 지원서 조회 시 `applicationId` 같이 안보내던 문제 수정
-
> [Fix] 지원 결과 조회 api 수정

- components/recruit/Main/MyApplicationInfo.tsx
> [Fix] 지원서 확인하기 페이지 url 수정

- components/recruit/Main/MyApplicationInfo.tsx
- components/recruit/Main/MyRecruitment.tsx
> [test-deploy] 지원서 확인하기 페이지 url 수정

- components/party/roomDetail/PartyDetailButton.tsx
> [Fix] share URL

- components/party/roomDetail/PartyDetailButton.tsx
- pages/party/[roomId]/index.tsx
> 1358 feat party detail room의 css 변경

- components/party/roomDetail/PartyDetailProfile.tsx
- styles/party/PartyDetailRoom.module.scss
> [Fix] join, leave 버튼 위치 수정

- components/modal/recruitment/ApplyEditModal.tsx
- components/recruit/Main/MyApplicationInfo.tsx
- components/recruit/Main/MyRecruitment.tsx
- components/recruit/RecruitList/RecruitListItem.tsx
- pages/recruit/apply.tsx
- pages/recruit/detail.tsx
- pages/recruit/my-application.tsx
- 동적 라우팅을 쿼리스트링으로 수정
- #1386
- 페이지를 동적 라우팅으로 이동할 시 정적 배포 환경에서 페이지 id를 찾을 수 없는 문제가 있어 모집 유저 페이지에서 동적 라우팅을 사용하는 부분을 쿼리스트링으로 변경했습니다.
- 공고 상세 페이지 : `recruit/[id]` -> `recruit/detail?recruitId=[id]`
- 공고 지원 페이지: `recruit/[id]/apply` -> `recruit/apply?recruitId=[id]`
- 내 지원서 페이지 : `recruit/[id]/my-application?applicationId=[applicationId]` -> `recruit/my-application?recruitId=[id]&applicationId=[applicationId]`
⭐️ 로컬에서는 해당 에러 재현이 안되어서 빠진 곳 없이 페이지 이동이 잘 되는지 정도만 확인해주시면 좋을 것 같습니다!
-
> [Fix] 동적 라우팅을 쿼리스트링으로 수정

- components/recruit/Application/ApplicationForm.tsx
- components/recruit/Application/applicationFormItems/MultiCheckForm.tsx
- hooks/recruit/useUserApplicationForm.ts
- types/recruit/recruitments.d.ts
- utils/handleApplicationForm.ts
-  build 에러 수정했습니다.
- 수정하기 api 요청 시 form -> forms 
- applicationForm 요청에 사용하는 form 타입 추가했습니다.
-
> [Fix] recruit build 에러 수정

- components/modal/recruitment/CancelModal.tsx
- close #1397
- 지원서 취소 이후 이동하는 페이지 url 변경 (사유: #1386)
-
> [Fix] 지원서 취소 이후 이동 url 변경

- styles/recruit/application.module.scss
- styles/recruit/common.module.scss
- #1401 
- 모집지원서 텍스트폼 기본문구가 헤더 뚫고 나오는 문제 수정
-
> [Fix] 모집지원서 텍스트폼 css 수정

- components/modal/modalType/PartyModal.tsx
- components/modal/party/PartyManualModal.tsx
- components/party/PartyCreate.tsx
- components/party/PartyMain.tsx
- components/party/roomDetail/PartyDetailButton.tsx
- hooks/party/usePartyRoomList.ts
- pages/party/index.tsx
- styles/party/PartyCreate.module.scss
- styles/party/PartyDetailRoom.module.scss
- 파티 메뉴얼 작성 및 아이폰 글자 색상 수정
- 파티 모집에 대한 메뉴얼 추가
- 아이폰에서 글자가 파란색으로 나오는 오류 수정
- 파티 참여시 슬랙알림에 대한 토스트 알림 추가
-
> Feat/파티 메뉴얼 작성 및 아이폰 글자 색상 수정 #1390

- components/modal/modalType/PartyModal.tsx
> [test-build] PartyModal 빌드 오류에따른 import제거후 재배포

- components/party/PartyCreate.tsx
- hooks/party/usePartyForm.ts
> [test-deploy] 파티생성시 마감기한 추가후 최종 테스트

- components/recruit/Application/ApplicationForm.tsx
- components/recruit/Application/applicationLayout/ApplicationFormFooter.tsx
- pages/recruit/detail.tsx
- pages/recruit/my-application.tsx
- #1403 
- 지원 시간 이후 => 지원하기 버튼이 비활성화 + 지원이 마감되었습니다
- 지원서 제출 상태 & 지원 마감 전 =>  수정버튼
- 지원서 제출 상태 => 삭제 버튼
- 지원서 제출 이후 다른 상태인 경우 둘 다 안 보임(ex. 면접, 합불 상태)
-
> [Fix] 공고모집 시간 이후 지원 수정 취소 기능 제한

- components/modal/recruitment/ApplyEditModal.tsx
- hooks/recruit/useUserApplicationForm.ts
- #1404
- 지원서 제출 모달에 로딩 상태일 때 disabled 설정 추가했습니다
> [Feat] 지원하기 로딩 버튼 처리

- components/Layout/Header.tsx
- components/modal/party/PartyRoomEditModal.tsx
- constants/party/createOptions.ts
- hooks/party/usePartyForm.ts
- styles/admin/party/PartyRoomEdit.module.scss
- styles/party/PartyCreate.module.scss
- 파티 배포 후 변경사항 반영
- 모바일에서 봤을때 폰트깨짐 현상 (아이폰에서 방 생시 글자 파란색으로 출력 및 가운데 정렬 안됨)
-  어드민에서 댓글쓰고 나간사람 인트라id 확인 불가(닉네임으로 나옴)
-  상세페이지에서 뒤로가기 버튼 없어짐
-  직접입력 디폴트 값 2-4 -> 2-8로 수정
- 방 생성시 공백문자 제거
-
> [Bug] 파티 모집 배포이후 피드백 반영 #1414

- components/main/PartyPreview.tsx
> [test-deploy] 파티 상세페이지에서 뒤로가기하면 항상 파티 메인으로 이동

- components/admin/recruitments/RecruitmentsHistoryList.tsx
- components/admin/recruitments/recruitmentsuser/DetailRecruitUserList.tsx
- components/admin/recruitments/recruitmentsuser/MenuTab.tsx
- components/admin/recruitments/recruitmentsuser/NotificationResults.tsx
- components/admin/recruitments/recruitmentsuser/RecruitSearchBar.tsx
- components/admin/recruitments/recruitmentsuser/RecruitmentFilterOptions.tsx
- components/admin/recruitments/recruitmentsuser/RecruitmentUser.tsx
- components/modal/admin/AdminRecruitResultModal.tsx
- hooks/recruitments/useRecruitmentUserFilter.ts
- types/modalTypes.ts
- 진행날짜수정 및 필터기능수정
- 수정전 후가 제대로 동작하지않는 부분을 수정했습니다.
- 필터기능이 제대로 동작하지 않는 부분을 수정했습니다.
- 면접일자알림기능 수정했습니다.
-
> [Fix] 진행날짜수정 및 필터기능 수정 #1400

- pages/agenda/[agendaKey]/[teamUID]/index.tsx
- pages/agenda/[agendaKey]/index.tsx
- pages/agenda/admin/index.tsx
- pages/agenda/create.tsx
- pages/agenda/index.tsx
- pages/agenda/profile/index.tsx
- pages/index.tsx
- agenda 하위 폴더 구성
- index/agenda 하위 폴더 구성 
```
|-- /agenda
|   |-- /[agendaKey]
|   |-- /[agendaKey]/[teamUID]
|
|-- /agenda/admin
|
|-- /agenda/profile
```
- 이후 각 페이지 내에서 권한별로 다르게 구성할 예정
> [Feat] agenda 하위 폴더 구성 #1434

- stories/pingpong/profile/profilepage.stories.tsx
- 디렉토리 구조 변경으로 인한 스토리북 경로 문제 해결
- 디렉토리 구조 변경 이후에 스토리북에서도 경로 에러가 나타나는 사소한 에러가 발생했습니다. 
- 스토리북에서 import하는 부분에서 디렉토리 구조 변경으로 영향을 받은 부분을 고쳐주었습니다.
-
> [Refactor] 디렉토리 구조 변경으로 인한 스토리북 경로 문제 해결

- components/agenda/agendaDetail/AgendaInfo.tsx
- styles/agenda/agendaDetail/AgendaInfo.module.scss
- types/agenda/agendaDetail/tabs/agendaInfoTypes.ts
- agenda Info 컴포넌트 조건 추가
- 기존의 agenda Info 컴포넌트를 팀 상세정보 페이지에서 사용할 수 있도록 조건 추가
- isHost와 status가 인자로 들어오지 않았을 경우 height 조정 및 버튼 출력 삭제
- 인자가 들어왔는지 체크하여 div className 추가 및 버튼 출력 하도록 변경
- close #1476
> [Feat] agenda Info 컴포넌트 조건 추가

- components/agenda/utils/PageController.tsx
> fix: index 페이지 비동기로 데이터없는 오류

- components/LoginChecker.tsx
> [test-deploy] fix: 로그인체크 해제

- hooks/takgu/Layout/useUser.ts
> [test-deploy] setError 끄고 로그인되는지 확인

- hooks/Login/useLogoutCheck.ts
> [test-deploy] ENV 추가 후 재시도

- Layout/LayoutProvider.tsx
> [test-deploy] index layout 확인

- components/LoginChecker.tsx
- components/admin/agenda/announcements/AnnouncementTable.tsx
- components/admin/agenda/teamList/TeamTable.tsx
- components/agenda/Form/AdminTicketForm.tsx
- components/agenda/Form/TicketForm.tsx
- components/agenda/Form/userForm.tsx
- components/agenda/Home/MyAgendaBtn.tsx
- components/agenda/Profile/HistoryList.tsx
- components/agenda/Ticket/Ticket.tsx
- components/agenda/agendaDetail/tabs/AgendaAnnouncements.tsx
- components/agenda/agendaDetail/tabs/ParticipantTeamList.tsx
- components/agenda/agendaDetail/tabs/ParticipantsList.tsx
- hooks/agenda/useFetchGet.ts
- hooks/agenda/useIntraId.ts
- hooks/agenda/usePageNation.ts
- pages/admin/agenda/teamModify.tsx
- pages/agenda/detail/host/result.tsx
- pages/agenda/detail/index.tsx
- pages/agenda/detail/team/create.tsx
- pages/agenda/detail/team/index.tsx
- pages/agenda/index.tsx
- pages/agenda/profile/user.tsx
- types/agenda/profile/profileCardTypes.ts
- hooks (useFetchGet, usePageNation) 수정
- 기존에 라우팅 수정으로 agenda 관련 hooks에 params의 agenda_key가 undefined인지 확인 하는 코드를 넣었지만, hooks의 일관성을 위해서 삭제했습니다. 
- API 호출 유무를 분기하기 위해 해당 코드를 넣었지만 props로 isReady 또한 받아와서 체크하도록 수정했습니다.  
1. hooks (useFetchGet, usePageNation) 이전 PR에서 코드 추가된 부분 삭제
2. props를 Object형식으로 가져오도록 변경 -> Object에서 isReady를 추가해서 isReady를 통해서 API호출 유무를 판단하도록 설정
> [Bug] router bug #1538

- components/agenda/Profile/ProfileCard.tsx
- styles/agenda/Home/MyAgendaBtn.module.scss
- styles/agenda/Home/MyTeamInfo.module.scss
- styles/agenda/Layout/Layout.module.scss
> [Style] 반응형 UI 업데이트 #1504

- pages/_app.tsx
- 로그인 보상 수령이슈 관련, 쿼리클라이언트 캐싱이 되지 않는 오류
- 쿼리클라이언트가 유지되지 않고 _app.tsx 속에서 계속 new를 통해 재생성하는 부분 확인
- 해당 쿼리클라이언트 useState를 통해 갱신되지 않도록 변경 
-
> [bug]로그인 보상을 수령해도 계속 화면이 뜨는 이슈/ 쿼리클라이언트 캐싱오류 #1525

- components/agenda/Form/AgendaForm.tsx
- components/agenda/Form/SubmitAgendaForm.tsx
- components/agenda/agendaDetail/TabContent.tsx
- components/agenda/agendaDetail/tabs/AgendaDescription.tsx
- constants/agenda/agendaDetail/agendaTabs.ts
- pages/agenda/detail/host/index.tsx
- pages/agenda/index.tsx
- styles/agenda/agendaDetail/AgendaDetail.module.scss
- styles/agenda/agendaDetail/tabs/AgendaConditions.module.scss
- styles/agenda/agendaDetail/tabs/AgendaDescription.module.scss
- styles/agenda/pages/agendakey/host/host.module.scss
- 아젠다 리스트, 호스트페이지, 상세조회 페이지 버그
- 호스트페이지 구성
- 진행완료 아젠다 있는데 agenda page의 진행완료 페이지에는 나타나지 않는 부분 해결
- 조건 탭 빼서 상세정보에 넣기
- admin agenda 수정 시 현재 날짜와 상관없이 수정 가능
> [Fix] 아젠다 리스트, 호스트페이지, 상세조회 페이지 버그 #1551 

- components/admin/takgu/party/PartyTemplate.tsx
- components/agenda/Form/TicketForm.tsx
- components/agenda/Home/AgendaDeadLine.tsx
- components/agenda/Home/AgendaList.tsx
- components/agenda/Layout/MenuBarContent.tsx
- components/agenda/agendaDetail/AgendaInfo.tsx
- components/agenda/modal/testModal.tsx
- components/error/AgendaError.tsx
- components/takgu/modal/admin/AdminTemplateModal.tsx
- components/takgu/modal/tournament/TournamentRegistryModal.tsx
- hooks/useAxiosGet.ts
- hooks/useAxiosWithToast.ts
- pages/agenda/detail/host/result.tsx
- pages/agenda/index.tsx
- pages/takgu/_api/pingpong/admin/announcement/index.tsx
- pages/takgu/_api/pingpong/admin/coinpolicy/index.ts
- pages/takgu/_api/pingpong/admin/feedback/index.ts
- styles/agenda/Home/Agenda.module.scss
- styles/agenda/Home/AgendaDeadLine.module.scss
- styles/agenda/Layout/Header.module.scss
- styles/agenda/Layout/Layout.module.scss
- styles/agenda/Layout/MenuBar.module.scss
- styles/agenda/common.scss
- styles/color-theme.css
- styles/globals.css
- 사파리 UI 오류 픽스
- 파란글씨..
- 로고 클릭 가능한 부분 사이즈 오류로 아젠다 가려짐
- 콘솔로그 제거
- 아젠다리스트 상태표시 세분화
- 아젠다리스트 web UI 깨짐
- 볼드체 깨짐
> [Bug] 사파리 UI 깨지는 부분 #1554 

- components/agenda/Profile/CurrentList.tsx
- components/agenda/Profile/HistoryList.tsx
- pages/agenda/profile/user.tsx
- styles/agenda/Profile/AgendaProfile.module.scss
- styles/agenda/Profile/CurrentList.module.scss
- styles/agenda/Profile/HistoryList.module.scss
- styles/agenda/utils/AgendaTag.module.scss
- types/agenda/profile/historyListTypes.ts
- responsive profile page
- 프로필 페이지 웹뷰 버전을 고려하여 UI를 개선했습니다.
- 각 List 데이터들을 하나의 AGENDA LIST 안에서 탭 형식으로 처리했습니다. (웹 뷰에서 어떻게 UI를 보여줄지 고민하다가 고안했습니다..)
> [Style] responsive profile page #1553

- README.md
- pages/agenda/detail/team/create.tsx
> [test-deploy] README 업데이트

- .github/workflows/main-deploy.yml
- .github/workflows/test-deploy.yml
- github actions aws build 자동화 off 설정
- aws build 자동화 부분 주석 처리 
- #1603
> [Fix] github actions aws build 자동화 off 설정

- hooks/calendar/admin/useAdminCalendarClassGet.ts
- hooks/calendar/admin/useAdminCalendarCreate.ts
- hooks/calendar/admin/useAdminCalendarDelete.ts
- hooks/calendar/admin/useAdminCalendarSearchGet.ts
- hooks/calendar/admin/useAdminCalendarTotalGet.ts
- 캘린더 어드민 url 변경
- [현재] calendar/admin/calendar -> [수정] calendar/admin
- #1610
> [Fix] 캘린더 어드민 url 변경
